### ISSUE TITLE
genicam package support for ARM 64

### ISSUE THREAD

**Issue by ArekMC** [genicam/harvesters#102]
Hello all,
first of all, awesome tool and thank you so much for your great job! This works great with Windows. However there is a problem installing genicam2 on aarch64.
```
ERROR: Could not find a version that satisfies the requirement genicam2 (from versions: none)
ERROR: No matching distribution found for genicam2
```
Any idea when there will be support for arm64 or if there is a workaround to install harvesters on jetson nano?
Thank you so much in advance

**Comment by kazunarikudo** [comment]
Hi, Arek. Thank you for trying out Harvester. I'm happy to hear that you like it. However, please excuse me, I'm afraid but we as the GenICam committee have not yet ported the GenApi-Python binding, `genicam2` that will be officially released as `genicam` shortly, to ARM. We have put it on the To-Do list but it would take time more or less. /Kazunari

**Comment by to266** [comment]
Hello,

Thanks for the awesome project!

We'd also like to use harvesters with arm64 architecture, and even though `genicam` seems to have been released (https://pypi.org/project/genicam/#files), it does not support arm64. 

Is there some sort of timeline when this would be available?
Alternatively, are there any workarounds / ways to port or rebuild this ourselves / generally help the effort?

Thanks

**Comment by kazunarikudo** [comment]
@to266 Hi. Thank you for your kind words. We as the GenICam committee have started to tackle to adding support of ARM to the `genicam` package have learned it would take time anyway because it's not a typical "left-to-right" porting even if the GenICam GenApi reference implementation has already supported ARMs. However, we know there is a reasonable amount of demand on the market so it would be very nice if we could release it by the end of 2020. Hope you keep paying attention to us until it's done. /Kazunari

**Comment by monzelr** [comment]
Hi @kazunarikudo,

is there any progress in developing a GenICam ARM version? I am also strongly interested in using a jetson nano with Harvester/GenICam for real time image processing. If there is any pre-version available for testing I would like to test it on my jetson nano. 

So far, the only work around I see is to use a C++ GenICam API (like Baumer GAPI SDK or Matrix Vision c++ [SDK](https://www.matrix-vision.com/manuals/SDK_CPP/index.html) to catch the images... this is too much effort for free time activities. ;-)

**Comment by tabroughton** [comment]
hi @kazunarikudo it would be great to get a version working on ARM.  Is it possible a financial contribution could help to sponsor the development?

**Comment by gittb** [comment]
Hello @kazunarikudo Sorry we have not spoke in awhile, things got very busy with work and Covid.

I would like to second @tabroughton, is there a financial contribution that could be made to fast track ARM development? This is one the major reason we shelved this project months ago.

Jetson Nano/IOT - ARM64 support is paramount in our eyes.

**Comment by ltskinner** [comment]
Agreed, extending functionality to ARM64 opens many doors for real world application of this package. 

This would put @kazunarikudo, the team, and harvesters at the forefront of bleeding edge applied CV and likely pay dividends over the coming years ;)

Any updates on the timeline for development would be much appreciated!

**Comment by danigamba** [comment]
Hello, if you can indicate me where to find sources and what to do I'm happy to try porting on Raspberry and Nvidia Jetson (nano and xavier).

**Comment by gittb** [comment]
I would like to reiterate how much my group (and a lot of others) could greatly benefit from this addition.

I am also willing to help out trying to port if you could point us in the correct direction.

Could you help us understand the effort required?

Willing to do whatever is needed to move this issue forward ASAP.

**Comment by gittb** [comment]
@kazunarikudo Any update on this?

**Comment by gittb** [comment]
Bumping this again.. Would love to help if you could inform us where to start @kazunarikudo 

Feel very in the dark.

**Comment by kazunarikudo** [comment]
Hey guys, I am sorry for having kept you waiting for long. I have just made the first step at last! Could you tell me your ARM 64 target and its default compiler and its compiler version, that would eventually build its Python 3? Anybody is welcome. Please feel free to leave your comment in this thread. I would like to find out the right target/toolchain. Thanks, Kazunari.

**Comment by clintlombard** [comment]
We're running the following:

Python version: 3.9
Python compiler: GCC 7.5.0
OS: Ubuntu 18.04 (L4T 32.4)
Target platform: Nvidia Xavier AGX

**Comment by kazunarikudo** [comment]
If you visited here to give us a comment, visit ticket #254 instead. Thanks, Kazunari.

**Comment by kazunarikudo** [comment]
Closing. Again, please keep an eye on ticket #254. Thanks!
