### ISSUE TITLE
IPython vs regular comand line execution

### ISSUE THREAD

**Issue by soad89** [genicam/harvesters#119]
Hello.

First of all, thanks for this usefull project. 
I just want to try to ask about one specific issue I face with. When I execute `add_cti_file` and `update_device_info_list` in comand line python I can succesfully open my USB3Vision camera and gather images. Do you have any idea why is that not functional in IPython kernel running in jupyter server. I guess it has something to deal with access rights but I do not know what to check, i use Win10 and runinng annaconda env with Python 3.6.
Thank you

**Comment by kazunarikudo** [comment]
@soad89 Hi. Thank you for trying out Harvester. Could you describe a bit more precisely about the issue you face on IPython? /Kazunari

**Comment by soad89** [comment]
Hi, whe I run this pcs of code in terminal under annoconda enviroment it lists device;
```
from harvesters.core import Harvester
h = Harvester()
h.add_cti_file('C:\Program Files\JAI\SDK/bin\JaiUSB3vTL.cti')
h.update_device_info_list()
print(h.device_info_list)
```
`[(id_='199E50810667_TheImagingSourceEuropeGmbH_DMK38UX304', vendor='The Imaging Source Europe GmbH', model='DMK 38UX304', tl_type='U3V', user_defined_name=None, serial_number='50810667', version='IMX253_M/1965/942 USB3c2r-IMX/11')]`

When I ran the same code in jupyter notebook under the same enviroment it results no devices.
