### ISSUE TITLE
HARVESTERS_XML_FILE_DIR getting errors

### ISSUE THREAD

**Issue by batrlatom** [genicam/harvesters#121]
**Describe the bug**
I am trying to specify where XML and zip files would be located. But I am getting an error.

**To Reproduce**

1. Use env variable; `HARVESTERS_XML_FILE_DIR=D:\\` (and all other variants like `\\\\` , `/`, `//` )
2. Run standart tutorial program. 
3. Get errors ( see screenshot section )
4. Files are located and `C:\\` (problems if I want to pack it into an app and not to
write some random files to the users `C:\\` ) and not at `D:\\`

**Expected behavior**
I should expect the XML and zip files to be stored at a specified location. 

**Screenshots**
```
2020-02-25 15:51:22,944 :: harvesters.core :: ERROR :: Error while parsing XML stream at line 418 and column 0 : 'unclosed token' : RuntimeException thrown (file 'XmlParser.cpp', line 1720)
Traceback (most recent call last):
  File "C:\ProgramData\Miniconda3\envs\pekat_vision\lib\site-packages\harvesters\core.py", line 2447, in _get_port_connected_node_map
    node_map.load_xml_from_zip_file(file_path)
  File "C:\ProgramData\Miniconda3\envs\pekat_vision\lib\site-packages\genicam\genapi.py", line 2010, in load_xml_from_zip_file
    return _genapi.NodeMap_load_xml_from_zip_file(self, ZipFileName)
_genapi.RuntimeException: File open failed in ParseXmlFile. Filename = 'C:///GenTLSystem.xml' : RuntimeException thrown (file 'XmlParser.cpp', line 131)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ProgramData\Miniconda3\envs\pekat_vision\lib\site-packages\harvesters\core.py", line 2450, in _get_port_connected_node_map
    node_map.load_xml_from_file(file_path)
  File "C:\ProgramData\Miniconda3\envs\pekat_vision\lib\site-packages\genicam\genapi.py", line 2004, in load_xml_from_file
    return _genapi.NodeMap_load_xml_from_file(self, FileName)
_genapi.RuntimeException: Error while parsing XML stream at line 418 and column 0 : 'unclosed token' : RuntimeException thrown (file 'XmlParser.cpp', line 1720)
2020-02-25 15:51:22,951 :: harvesters.core :: ERROR :: Error while parsing XML stream at line 510 and column 0 : 'unclosed token' : RuntimeException thrown (file 'XmlParser.cpp', line 1720)
Traceback (most recent call last):
  File "C:\ProgramData\Miniconda3\envs\pekat_vision\lib\site-packages\harvesters\core.py", line 2447, in _get_port_connected_node_map
    node_map.load_xml_from_zip_file(file_path)
  File "C:\ProgramData\Miniconda3\envs\pekat_vision\lib\site-packages\genicam\genapi.py", line 2010, in load_xml_from_zip_file
    return _genapi.NodeMap_load_xml_from_zip_file(self, ZipFileName)
_genapi.RuntimeException: File open failed in ParseXmlFile. Filename = 'C:///GenTLInterface.xml' : RuntimeException thrown (file 'XmlParser.cpp', line 131)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ProgramData\Miniconda3\envs\pekat_vision\lib\site-packages\harvesters\core.py", line 2450, in _get_port_connected_node_map
    node_map.load_xml_from_file(file_path)
  File "C:\ProgramData\Miniconda3\envs\pekat_vision\lib\site-packages\genicam\genapi.py", line 2004, in load_xml_from_file
    return _genapi.NodeMap_load_xml_from_file(self, FileName)
_genapi.RuntimeException: Error while parsing XML stream at line 510 and column 0 : 'unclosed token' : RuntimeException thrown (file 'XmlParser.cpp', line 1720)
2020-02-25 15:51:22,957 :: harvesters.core :: ERROR :: Error while parsing XML stream at line 619 and column 0 : 'unclosed token' : RuntimeException thrown (file 'XmlParser.cpp', line 1720)
Traceback (most recent call last):
  File "C:\ProgramData\Miniconda3\envs\pekat_vision\lib\site-packages\harvesters\core.py", line 2447, in _get_port_connected_node_map
    node_map.load_xml_from_zip_file(file_path)
  File "C:\ProgramData\Miniconda3\envs\pekat_vision\lib\site-packages\genicam\genapi.py", line 2010, in load_xml_from_zip_file
    return _genapi.NodeMap_load_xml_from_zip_file(self, ZipFileName)
_genapi.RuntimeException: File open failed in ParseXmlFile. Filename = 'C:///GenTLDevice.xml' : RuntimeException thrown (file 'XmlParser.cpp', line 131)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ProgramData\Miniconda3\envs\pekat_vision\lib\site-packages\harvesters\core.py", line 2450, in _get_port_connected_node_map
    node_map.load_xml_from_file(file_path)
  File "C:\ProgramData\Miniconda3\envs\pekat_vision\lib\site-packages\genicam\genapi.py", line 2004, in load_xml_from_file
    return _genapi.NodeMap_load_xml_from_file(self, FileName)
_genapi.RuntimeException: Error while parsing XML stream at line 619 and column 0 : 'unclosed token' : RuntimeException thrown (file 'XmlParser.cpp', line 1720)
2020-02-25 15:51:23,042 :: harvesters.core :: ERROR :: Error while parsing XML stream at line 721 and column 0 : 'unclosed token' : RuntimeException thrown (file 'XmlParser.cpp', line 1720)
Traceback (most recent call last):
  File "C:\ProgramData\Miniconda3\envs\pekat_vision\lib\site-packages\harvesters\core.py", line 2447, in _get_port_connected_node_map
    node_map.load_xml_from_zip_file(file_path)
  File "C:\ProgramData\Miniconda3\envs\pekat_vision\lib\site-packages\genicam\genapi.py", line 2010, in load_xml_from_zip_file
    return _genapi.NodeMap_load_xml_from_zip_file(self, ZipFileName)
_genapi.RuntimeException: File open failed in ParseXmlFile. Filename = 'C:///GenTLStream.xml' : RuntimeException thrown (file 'XmlParser.cpp', line 131)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ProgramData\Miniconda3\envs\pekat_vision\lib\site-packages\harvesters\core.py", line 2450, in _get_port_connected_node_map
    node_map.load_xml_from_file(file_path)
  File "C:\ProgramData\Miniconda3\envs\pekat_vision\lib\site-packages\genicam\genapi.py", line 2004, in load_xml_from_file
    return _genapi.NodeMap_load_xml_from_file(self, FileName)
_genapi.RuntimeException: Error while parsing XML stream at line 721 and column 0 : 'unclosed token' : RuntimeException thrown (file 'XmlParser.cpp', line 1720)
```
**Desktop (please complete the following information):**
 - OS: Win10
 - Python: 3.7 in MiniConda env
 - Harvester: 1.03
 - GenTL Producer: Basler
 - Camera: Basler

**Additional context**

**Comment by kazunarikudo** [comment]
@batrlatom Hi. The message `_genapi.RuntimeException: Error while parsing XML stream at line 721 and column 0 : 'unclosed token' : RuntimeException thrown (file 'XmlParser.cpp', line 1720)` is telling you that your XML file is invalid. You should consult with Basler support. You can edit that by yourself but it can be done if you are sure what is wrong with the file. Please open this ticket again if the error happens with a valid XML file. /Kazunari

**Comment by 0lru** [comment]
I'm getting the same errors with Basler & Teledyne DALSA models.
It does not relate to the vendor of the camera.
I've fixed that already locally.  Will send you a pull request soon.
Else.. works quite nice.

**Comment by kazunarikudo** [comment]
@batrlatom Hi.

> I am trying to specify where xml and zip files would be located.

File**s**? Why is that plural? The current specification allows you to specify an XML file for only the remote device. As far as I see the log that you provided, you seem to be trying to specify XML files for each GenTL module.

**Comment by kazunarikudo** [comment]
@0lru Hi. Thank you for trying out Harvester. As I commented above, do you mean you modified the original code so that even each GenTL module can specify its XML file location? It is totally fine to have such specifications but do not know why did you need to have such one. Are you trying to debug a GenTL Producer? /Kazunari

**Comment by 0lru** [comment]
I've simply added a lstrip in (because the xml-target path evaluates to something like: "c:////temp"
this doesn't work with Windows 10 (core.py, ~ Line 2363):
```python
        if location == 'local':
            file_name, address, size = others.split(';')
            file_name = file_name.lstrip('/')
```
Additionally, (~Line 2439). I wonder why we need to rstrip the buffer here (why we don't just use "wb" as a parameter to "open":
```python
        data_to_write = bytes_content.decode()
        pos = data_to_write.find('\x00')
```
Third problem was the data_format_value.  ```_buffer.pixel_format``` gives an exception
with the basler-camera I'm using. I modified it this way:
```python
    def data_format_value(self):
        """
        :return: The data type of the data component as integer value.
        """
        try:
            if self._part:
                return self._part.data_format
            else:
                return self._buffer.pixel_format
        except GenericException:
            pixel_format_string = self._node_map.PixelFormat.value
            if pixel_format_string in _inverse_symbolics:
                return _inverse_symbolics[pixel_format_string]
            else:
                raise
```

**Comment by kazunarikudo** [comment]
@0lru Thank you for your message. I will take a look at these suggestions you proposed. Thank you!

**Comment by 0lru** [comment]
for completeness:
``` python
   def _build_component(self, buffer=None, part=None, node_map=None):
        #
        try:
            if part:
                data_format = part.data_format
            else:
                data_format = buffer.pixel_format
        except:
            if node_map is not None:
                pixel_format_string = node_map.PixelFormat.value
                if pixel_format_string in _inverse_symbolics:
                    return _inverse_symbolics[pixel_format_string]
                else:
                    raise
            else:
                raise
```
and
```python
_inverse_symbolics = {v: k for k, v in symbolics.items()}
```

**Comment by kazunarikudo** [comment]
@0lru I've just committed a change for the second issue, thanks. By the way, could you tell me a `file_name` that triggers the first issue on you? It would be easier for me if you could show me a whole string of the URL that you get.

**Comment by batrlatom** [comment]
@0lru @kazunarikudo Thank you for reopening the issue. I have changed it myself by similar way like 0lru. @kazunarikudo the filename I was getting was file:///Gentl.xml so It was parsed to ///Gentl . My code for repair was 

```
    import sys
    os_system = sys.platform
    if os_system in ['win32']:
        file_name = "." + file_name
```

**Comment by kazunarikudo** [comment]
@batrlatom Hi, sorry having misinterpreted your original report. To resolve this issue, may I ask you questions a bit more? You told me the URI consists of `file:///Gentl.xml` but with that notation where would that point at exactly? I have checked [Wikipedia](https://en.wikipedia.org/wiki/File_URI_scheme) and learned `file:///` is just omitting `host` but can't understand how should I interpret the location. In addition, which model gives such a URI? The almost cameras on the market store its XML file in the internal storage and as a result, the URIs look like `local:foo.zip;940;1310` for example. This is just out of curiosity but I would like to know your case.

**Comment by 0lru** [comment]
https://www.baslerweb.com/en/products/cameras/area-scan-cameras/ace/aca2500-60um/

**Comment by kazunarikudo** [comment]
@0lru Hi. Is that model has such a URI? If so, I would appreciate it if you could tell me the location, `file:///Gentl.xml`, where batrlatom introduced me.

**Comment by 0lru** [comment]
Yes, it returns such a URI/URL (https://en.wikipedia.org/wiki/Uniform_Resource_Identifier)
* "file://" is the protocol
* /Genttl.xml is the path
where "/" means "root".

authority etc are optional. maybe we can use something like:
https://docs.python.org/3/library/urllib.parse.html

**Comment by kazunarikudo** [comment]
I understand batrlatom tried to use that protocol (`file:`) for `HARVESTERS_XML_FILE_DIR` but with your comment,

> it returns such a URI/URL

do you mean there is a case camera specifies the location using the `file:` protocol instead of `local:`?

**Comment by kazunarikudo** [comment]
@0lru By the way, you seem to be very familiar to GenICam. Could you privately send a message to my [email address](who.is.kazunari@gmail.com) when you can, please? /Kazunari

**Comment by 0lru** [comment]
> do you mean there is a case camera specifies the location using the file: protocol instead of local:?

I did a misread here. That's because I have no physical access
to the device currently (today). Sorry for the confusion. This model returns ```local```

**Comment by kazunarikudo** [comment]
> I did a misread here.
> This model returns local

Okay, that makes sense to me.

**Comment by kazunarikudo** [comment]
@batrlatom Hi. I have committed a change that aims to resolve the file URI scheme issue. Please let me know if it works for you. Excuse me, since I do not have a Windows machine here.

**Comment by kazunarikudo** [comment]
@0lru Hi. I'm going to open another ticket for your `PixelFormat` issue. I will let you know once the fixed version turned available.

**Comment by kazunarikudo** [comment]
@batrlatom Hi again. I'm going to close this ticket but feel free to let me know if the latest version did not work for you. I will reopen this ticket and try to tackle it again.
