### ISSUE TITLE
Port all this to C++ and do bindings to Python,Java ...

### ISSUE THREAD

**Issue by 0lru** [genicam/harvesters#122]
**Is your feature request related to a problem? Please describe.**
This project could reach a broader audience

**Describe the solution you'd like**
Port all this to C++ and to "lightweight" bindings

**Describe alternatives you've considered**
Port all this to Rust and do lightweight bindings

**Comment by kazunarikudo** [comment]
@0lru Thank you for having a positive impression for Harvester. To make my understanding clearer, let me make sure about some points. (1) Do you mean you want to suggest me to open up some other language versions of Harvester? I mean, now Harvester is a Python library but you say there should be Harvester C++ or Harvester Java as well? (2) Could you tell me your priority of the languages? As far as I read above, C++ comes first and then Rust follows. (3) Could you tell me your background a bit more? I'm a contributor to the official GenICam committee who regularly attends every face-to-face meeting called International Vision Standards Meeting, IVSM in short. I am responsible for developing and maintaining the GenICam Python binding that Harvester consumes. /Kazunari

**Comment by 0lru** [comment]
Harvesters consist of more than 2500 LOC. From my experience, if you write your own thing based on the Genicam-API, as an example in Java or C++, you'll end up with even more LOC.

C++ seems the be one of the most portable languages at our time. You can now run in the browser and embed it in other environments through pybind11, JNI or whatsoever. Rust is comparable.

In consequence, I wondered if it's possible to create something more generic. Why shouldn't it be possible to harvest in any other language without too much code duplication?

**Comment by kazunarikudo** [comment]
@0lru Hi. Thank you for your valuable suggestion. The positive news that I have now is the official GenICam committee has already decided to develop such a C++ library that would be ported to other languages. The decision was made in late 2019 so it would take time more or less but it's promising because one of the committee member companies has the first prototype to be reviewed in the near future. I hope you keep an eye on the progress; it should come up in the GenICam GitHub repository. /Kazunari

**Comment by Bart-van-Ingen** [comment]
Hi @kazunarikudo! do you know what the status is of the genicam committee cpp library that you are referring to?

**Comment by kazunarikudo** [comment]
@Bart-van-Ingen Hi, I could recall someone was throwing a hint at the time but I do not know if the guy still working for the company. At least I do not believe that was just a hint that never worked. /Kazunari.

**Comment by Bart-van-Ingen** [comment]
Is it still something worth revisiting ?

**Comment by kazunarikudo** [comment]
@Bart-van-Ingen I am sorry but I do not think so as of 2021.

**Comment by nocanstillbb** [comment]
The header file downloaded by genicam and the interface in the manual are even different. I have no way to abstract the SDKs of multiple camera vendors based on genicam's interface.
