### ISSUE TITLE
Buffers run out inside loop after 16 iterations

### ISSUE THREAD

**Issue by Frodo181** [genicam/harvesters#129]
**Bug description**
When calling ia.fetch_buffer() inside a loop to acquire images from a machine vision camera via a software trigger, only the first 16 calls will result in an image. 

**Steps to reproduce the behaviour:**
Connect to the camera, set up the camera for a software trigger. Trigger the camera in software inside a loop and obtain the image from the buffer each time. img_arr[16] to img_arr[20] will have a 0 (no image, see code below).

ia = h.create_image_acquirer(list_index=0)
Camera_settings = ia.remote_device.node_map 
Camera_settings.TriggerMode.value = 'On' # Trigger mode on
Camera_settings.TriggerSource.value = "Software" # Use software trigger

N_FRAMES = 20
img_arr = [None]*N_FRAMES
ia.start_image_acquisition()
while x < N_FRAMES:
    Camera_settings.TriggerSoftware.execute()
    time.sleep(0.05)
    
    try:
        # Obtain image in the buffer
        buffer = ia.fetch_buffer(timeout = 1)
        payload = buffer.payload
        component = payload.components[0]
        width = component.width
        height = component.height
        data_format = component.data_format
        
        # Reshape the image so that it can be drawn on the VisPy canvas:
        if data_format in mono_location_formats:
            content = component.data.reshape(height, width)
        img_arr[x] = content
        x = x+1    
    except TimeoutException:
        print('Buffer timeout')
        content = 0
        img_arr[x] = content
        x = x+1

ia.stop_image_acquisition()
ia.destroy()
h.reset()

**Expected behaviour**
img_arr would now contain 20 images from the time at which the camera was triggered by software. 

**Desktop:**
 - OS: Windows 10
 - Python: 3.7
 - GenTL Producer: Daheng Imaging

**Comment by kazunarikudo** [comment]
@Frodo181 You are not queueing any buffer after fetching them. Please take a look at [this section](https://github.com/genicam/harvesters#id61).
