### ISSUE TITLE
Introduce a way that makes the callback feature flexible.

### ISSUE THREAD

**Issue by kazunarikudo** [genicam/harvesters#141]
**Is your feature request related to a problem? Please describe.**
So far, the callback on new buffer arrival is done by a function but it's not flexible at all.

**Describe the solution you'd like**
Define a base class that is used as the callback.

**Describe alternatives you've considered**
None.

**Additional context**
See also issue #61.

**Comment by TKaluza** [comment]
Not sure how to do it? Because @kazunarikudo is great guy he already added some information in [FAQ:Callbacks](https://github.com/genicam/harvesters/wiki/FAQ#callbacks)

**Comment by kazunarikudo** [comment]
@TKaluza Could you tell me what you would like to know with the callback feature? /Kazunari
