### ISSUE TITLE
"[Errno 2] No such file or directory:" when looking for .xml file

### ISSUE THREAD

**Issue by MartinCicmanec** [genicam/harvesters#145]
Hello, first of all a big thanks for the work done in this project.
I have an issue with the newest Baumer GAPI SDK for Ubuntu.

**Bug description**
It seems that Harvesters joins the temporary directory with the static path to Baumer library files.
I also don't have the libbgapi2_gige.cti_2.10.25111.25119.xml file in that Baumer folder anyway.
If I export the xml file dir as an enviroment variable, the final path used just prefixes it to the static Baumer library path.
Baumer has changed the library folder from '/usr/local/lib/baumer/' to '/opt/baumer-gapi-sdk/lib/' in a recent update.
Edit:
I will install and try the mvImpactAcquire SDK from Matrix Vision as is recommended.

**To Reproduce**
1.  When I try to create the image acquirer, I recieve the error:
`FileNotFoundError: [Errno 2] No such file or directory: '/tmp/20200414120524_l6mdyngm/opt/baumer-gapi-sdk/lib/libbgapi2_gige.cti_2.10.25111.25119.xml'`
2. Run `export HARVESTERS_XML_FILE_DIR=/opt/baumer-gapi-sdk/lib/` in terminal and I get:
`FileNotFoundError: [Errno 2] No such file or directory: '/opt/baumer-gapi-sdk/lib/opt/baumer-gapi-sdk/lib/libbgapi2_gige.cti_2.10.25111.25119.xml'`
3. As test, run `export HARVESTERS_XML_FILE_DIR=/` in terminal and I recieve the error:
`PermissionError: [Errno 13] Permission denied: '/.xml'` - it does not seem to join directories now.

A quick workaround seem to be to copy the xml files from another machine to 
`/home/martin/opt/baumer-gapi-sdk/lib/` and run `export HARVESTERS_XML_FILE_DIR=/home/martin/` so the paths work.

**Expected behavior**
Creation of image acquirer.

**Screenshots**
The whole traceback:
```
Traceback (most recent call last):
  File "/usr/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/usr/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/martin/git/nn_client/camera_termal.py", line 106, in __init__
    self.camera = self.h.create_image_acquirer(list_index=None, serial_number=self.serial, file_path="/opt/baumer-gapi-sdk/lib/libbgapi2_gige.cti_2.10.25111.25119.xml")
  File "/home/martin/.local/lib/python3.7/site-packages/harvesters/core.py", line 3283, in create_image_acquirer
    file_path=file_path
  File "/home/martin/.local/lib/python3.7/site-packages/harvesters/core.py", line 1761, in __init__
    xml_dir=self._xml_dir
  File "/home/martin/.local/lib/python3.7/site-packages/harvesters/core.py", line 3000, in _get_port_connected_node_map
    port=port, file_path=file_path, logger=logger, xml_dir=xml_dir
  File "/home/martin/.local/lib/python3.7/site-packages/harvesters/core.py", line 2919, in _retrieve_file_path
    binary_data=binary_data
  File "/home/martin/.local/lib/python3.7/site-packages/harvesters/core.py", line 2977, in _save_file
    with open(file_path, mode) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/opt/baumer-gapi-sdk/lib/opt/baumer-gapi-sdk/lib/libbgapi2_gige.cti_2.10.25111.25119.xml'

```
**Desktop (please complete the following information):**
 - OS: Ubuntu 19.10
 - Python: 3.7
 - Harvester: 1.2.0
 - Genicam: 1.0
 - GenTL Producer: Baumer 
 - Camera: Baumer GiGE camera

**Additional context**
None

**Comment by kazunarikudo** [comment]
@MartinCicmanec Hi, Martin. Thank you for trying out Harvester for the bug report. Yes, I guess it's a bug. I will take a look at that and give you an update once I get some. Till then, sorry for the inconvenience. /Kazunari

**Comment by kazunarikudo** [comment]
@MartinCicmanec Hi. Just one question: The CTI file you showed me looks like a file for? The name looks like a file for an entity that is defined by the GenTL standard such as System or Interface. I would appreciate it if you could tell me a bit more about what were you trying to achieve with that way.

**Comment by MartinCicmanec** [comment]
Sorry for the late reply. I was just trying to use the camera for capture. The CTI files I use are provided by the Baumer bgapi SDK. I load both the USB and the GiGE files. I sometimes use an USB and sometimes GiGE cameras, so I load both CTI files in the program and just search for cameras connected. Previous versions of bgapi work without a problem. I just provided the path to the file with `add_cti_file` .

After I run the program, I do have a folder created in `/tmp/20200414120524_l6mdyngm/` which contains a xml file probably created and stored by harvesters, but when it tries to access it later, it uses the total filepath the the bgapi library folder between the path to the /tmp folder and the xml name.
It should have just been 
'/tmp/20200414120524_l6mdyngmlibbgapi2_gige.cti_2.10.25111.25119.xml' 
instead of 
'/tmp/20200414120524_l6mdyngm/opt/baumer-gapi-sdk/lib/libbgapi2_gige.cti_2.10.25111.25119.xml'

**Comment by kazunarikudo** [comment]
@MartinCicmanec Hi, thank you for your reply. I have just created a branch called `_issue_145`. Could you try that out when you can and tell me the outcome, please? /Kazunari

**Comment by MartinCicmanec** [comment]
Yes, thank you! This branch fixed the issue and it works without problem.

**Comment by kazunarikudo** [comment]
@MartinCicmanec Thank you for taking the time for this issue. I hope you enjoy your work with Harvester. /Kazunari
