### ISSUE TITLE
Toshiba teli GIGE camera does not work, but USB3 camere works

### ISSUE THREAD

**Issue by saruo2000-ai** [genicam/harvesters#147]
@kazunarikudo Hi there,
I have got the following exception in core.py.  Genicam(Harversters) does not seem to detect the camera.
Do you have any idea to solve this issue?
* I could get image data from a camera(Toshiba teli USB3 camera BU505MCF) by the same programs and also I could get image data from the following GIGE camera by using Toshiba Teli's SDK(python), so the GIGE camera must be working properly. 

manufactured by : Toshiba Teli
model: BG302LMG(GIGE)
OS: Windows10
Python Version: 3.7
Harvesters Version: 1.2.0

my program:

def main():
    h = Harvester()
    h.add_cti_file('d:/work/TeliCamTL64.cti')
    h.update_device_info_list()
    ia = h.create_image_acquirer(0)

core.py ( the exception occured):

3213 # Instantiate a GenTL Device module.
3214        if list_index is not None:
3215            device = self.device_info_list[list_index].create_device()

Exception has occurred: IndexError
list index out of range
  File "C:\dev\genicam\harvesters\src\harvesters\core.py", line 3215, in create_image_acquirer
    device = self.device_info_list[list_index].create_device()
  File "C:\dev\genicam\harvesters\src\imageCaptest.py", line 10, in main
    ia = h.create_image_acquirer(0)
  File "C:\dev\genicam\harvesters\src\imageCaptest.py", line 39, in <module>
    main()

**Comment by kazunarikudo** [comment]
@saruo2000-ai Hi. Thank you for trying out Harvester. One question: You say the CTI file is located at `d:/work/TeliCamTL64.cti` but is that the original installation directory? If it's not, could you try to point at the original location? /Kazunari

**Comment by kazunarikudo** [comment]
In addition, I would like you to check if another process is holding the camera control privilege when you try to run your Python program. If there's such a process please terminate it.

**Comment by saruo2000-ai** [comment]
Thanks for quick reply! @kazunarikudo 
I have done the following pg, but the same exception occured for the GIGE camera..
I found the two cti files so I tried the both. <- the USB3 camera works with the both.
I also have checked another process as you said.

def main():
    h = Harvester()
    # h.add_cti_file('d:/work/TeliCamTL64.cti')
    h.add_cti_file('C:\\Program Files\\TOSHIBA TELI\\TeliCamSDK\\TeliCamApi\\bin\\win64\\TeliCamTL64.cti')
    # h.add_cti_file('C:\\Program Files\\TOSHIBA TELI\\TeliCamSDK\\TeliCamApi\\bin\\x64\\TeliCamTL64.cti')
    h.update_device_info_list()
    ia = h.create_image_acquirer(0)

**Comment by kazunarikudo** [comment]
It would not change the result but could use the forward-slash instead of the backslash in the path?

**Comment by saruo2000-ai** [comment]
yes. I have done as follows, but the same..USB3 camera did work.
thanks for your time.
def main():
    h = Harvester()
    # h.add_cti_file('d:/work/TeliCamTL64.cti') #
    h.add_cti_file('C:/Program Files/TOSHIBA TELI/TeliCamSDK/TeliCamApi/bin/win64/TeliCamTL64.cti')
    # h.add_cti_file('C:/Program Files/TOSHIBA TELI/TeliCamSDK/TeliCamApi/bin/x64/TeliCamTL64.cti')
    # h.add_cti_file('C:\\Program Files\\TOSHIBA TELI\\TeliCamSDK\\TeliCamApi\\bin\\win64\\TeliCamTL64.cti')
    # h.add_cti_file('C:\\Program Files\\TOSHIBA TELI\\TeliCamSDK\\TeliCamApi\\bin\\x64\\TeliCamTL64.cti')
    h.update_device_info_list()
    ia = h.create_image_acquirer(0)

**Comment by kazunarikudo** [comment]
Are you sure they support GigE Vision cameras through their GenTL Producer? That would be the main concern.

**Comment by saruo2000-ai** [comment]
I have checked the follow. Not what you mean?
https://www.toshiba-teli.co.jp/en/products/industrial/gige/index.htm
This product is based on GenICam Generic Interface for Cameras Ver2.3 (CCD model) or Ver2.4 and Ver3.0 (CMOS model)

**Comment by kazunarikudo** [comment]
@saruo2000-ai No, it's not. I meant their GenTL Producer does not support GigE Vision cameras. The exception above is just telling you the cameras are GenICam compliant. It's not talking about GenTL Producer at all.

**Comment by saruo2000-ai** [comment]
Okay. I will ask them and I may get back to you then. Thank you anyhow!

**Comment by kazunarikudo** [comment]
@saruo2000-ai Hi. I guess their Producer does not support GigE Vision, do they? I'm going to close this ticket but please feel free to reopen this when needed. /Kazunari

**Comment by saruo2000-ai** [comment]
@kazunarikudo , yes, i have confirmed.  their GenTL Producer does not support GigE Vision cameras as you say. It is okay the issue is closed.thanks.
