### ISSUE TITLE
UnicodeDecodeError raised when connecting a device

### ISSUE THREAD

**Issue by severij** [genicam/harvesters#15]
**Description**

Following the example on the [main page](https://github.com/genicam/harvesters#how-to-use-harvester-core):
```
>>> from harvesters.core import Harvester
>>> h = Harvester()
>>> h.add_cti_file("/opt/mvIMPACT_Acquire/lib/x86_64/mvGenTLProducer.cti")
>>> h.update_device_info_list()
>>> for i, info in enumerate(h.device_info_list):
...     print('{0}: {1}'.format(i, info.display_name))
... 
0: Point Grey Research VID1E10_PID3300_15294589
>>> h.connect_device(0)
```
The last function call raises the following error:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/atsejaas/.local/share/miniconda3/lib/python3.6/site-packages/harvesters/core.py", line 316, in connect_device
    self._encodings[encoding]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 113: ordinal not in range(128)
```

**To Reproduce**

OS: Red Hat Enterprise Linux Workstation 7.4.
The GenTL Producer: part of Matrix Visions mvIMPACT Acquire software.
Camera: Point Grey Grasshopper3 GS3-U3-23S6C.

**Comment by kazunarikudo** [comment]
Hi Severi,

Thank you for the report. I've fixed the issue at https://github.com/genicam/harvesters/commit/72b0a78563cde034959a63032aeeaf5faa527cf6:

> Harvester was trying to encode the downloaded XML file retrieving
> its GenTL Producer's char encoding. The encoding is applied on
> the buffers that are defined by the GenTL Standard but not by the
> remote device's XML file. GenICam compliant XML files use UTF-8.

I'd appreciate if you can confirm if it resolves the issue you've faced. If it resolves the issue, please close this ticket.

Thanks,
Kazunari
