### ISSUE TITLE
Accept Path objects from pathlib for paths

### ISSUE THREAD

**Issue by TKaluza** [genicam/harvesters#153]
**Is your feature request related to a problem? Please describe.**
Accept paths objects directly for parameters like `Harvester.add_file(string_path)`. A nice-to-have feature request, but other things a much more important. :1st_place_medal: 

**Describe the solution you'd like**
Improve handling of paths with Path Class from [pathlib](https://docs.python.org/3.5/library/pathlib.html?highlight=pathlib). 

**Describe alternatives you've considered**
It is not important but would be nice. Of course, you can easly insert `Path.resolve()` as a string.
[Here](https://stackoverflow.com/questions/42513056/how-to-get-absolute-path-of-a-pathlib-path-object) are some information about .absolute vs `.resolve()`. It is still a ongoing [process](https://bugs.python.org/issue39090) with `.absolute()`.

**Comment by kazunarikudo** [comment]
@TKaluza Hi. Could you tell me your idea a bit more, please? I'm sorry but I do not understand what you expect.

**Comment by TKaluza** [comment]
@kazunarikudo 
Thank you for your time. Maybe this code snippet is better in describing my problems:
```
#!/usr/bin/env python3
from pathlib import Path
from harvesters.core import Harvester

crash = False

my_dir = Path()
path_to_cti = list(my_dir.glob("*usb.cti"))[0]
h = Harvester()
if crash:
    h.add_file(path_to_cti)  # would be nice if this could work
else:
    path_string = str(path_to_cti.resolve())
    print(path_string)
    h.add_file(path_string)  # this works :)
h.update()
ia = h.create_image_acquirer(0)
```

This feature request/enhancement is really not important, but I would say it's a bit more pytonic

**Comment by kazunarikudo** [comment]
@TKaluza Hi. Excuse me, I still do not understand why is this supported on the Harvester side. Could you give me some comments if possible?

**Comment by kazunarikudo** [comment]
Closing. Please feel free to re-open this when you get a reasonable motivation to support the suggested feature. Thanks.

**Comment by ilanbiala** [comment]
@kazunarikudo this feature would be nice to have because Python's `pathlib` library is much better at filesystem path manipulation, and it's much more convenient to work in `pathlib.Path` objects as much as possible, especially in newer versions of Python with support for different OSes built-in to the library. Could you consider adding support for this?
