### ISSUE TITLE
PermissionError: [Errno 13] Permission denied for Harvesters 1.0.3 and newer

### ISSUE THREAD

**Issue by monzelr** [genicam/harvesters#161]
First of all, big thanks to @kazunarikudo for providing this awesome and simple interface to a lot of cameras! Especially I like the new callback functionality which is provided since 1.2.0. I found the following problem when I upgraded harvesters to 1.2.0:

**Describe the bug**
During the creation of the image acquirer I got a permission denied error for Harvesters 1.2.0 (down to version 1.0.3). Using Harvesters 1.0.2 does work for me.

**To Reproduce**

1. Run this code:
```
import os
import harvesters
print(harvesters.__version__)

from harvesters.core import Harvester
h = Harvester()
# ATTENTION! Please use the CTI file in the original location!
path = os.path.abspath(r'C:\Program Files\Baumer GAPI SDK (64 Bit)\Components\Bin')
path = os.path.join(path, 'bgapi2_usb.cti')
print(path)

h.add_cti_file(path)
h.update_device_info_list()
print(h.device_info_list)

ia = h.create_image_acquirer(0)

print('done')
```

2. See output / error:
```
1.2.0
C:\Program Files\Baumer GAPI SDK (64 Bit)\Components\Bin\bgapi2_usb.cti
D:/monzelrDESK/FA/software/$DATA_SVN/sourceCode/harvestersTestForGIT:12: DeprecationWarning: add_cti_file() will be deprecated shortly. Use add_file() instead.
  h.add_cti_file(path)
D:/monzelrDESK/FA/software/$DATA_SVN/sourceCode/harvestersTestForGIT:13: DeprecationWarning: update_device_info_list() will be deprecated shortly. Use update() instead.
  h.update_device_info_list()
[(id_='282500003F03', vendor='Baumer', model='VCXU-23M', tl_type='U3V', user_defined_name=None, serial_number='', version=None)]
Traceback (most recent call last):
  File "D:/monzelrDESK/FA/software/$DATA_SVN/sourceCode/harvestersTestForGIT", line 16, in <module>
    ia = h.create_image_acquirer(0)
  File "C:\Users\monzelrDESK\Anaconda3\envs\genicam\lib\site-packages\harvesters\core.py", line 3283, in create_image_acquirer
    file_path=file_path
  File "C:\Users\monzelrDESK\Anaconda3\envs\genicam\lib\site-packages\harvesters\core.py", line 1761, in __init__
    xml_dir=self._xml_dir
  File "C:\Users\monzelrDESK\Anaconda3\envs\genicam\lib\site-packages\harvesters\core.py", line 3000, in _get_port_connected_node_map
    port=port, file_path=file_path, logger=logger, xml_dir=xml_dir
  File "C:\Users\monzelrDESK\Anaconda3\envs\genicam\lib\site-packages\harvesters\core.py", line 2919, in _retrieve_file_path
    binary_data=binary_data
  File "C:\Users\monzelrDESK\Anaconda3\envs\genicam\lib\site-packages\harvesters\core.py", line 2977, in _save_file
    with open(file_path, mode) as f:
PermissionError: [Errno 13] Permission denied: 'C:\\Program Files\\Baumer GAPI SDK (64 Bit)\\Components\\Bin\\bgapi2_usb.cti_2.10.25119.25119.xml'

Process finished with exit code 1

```

**Expected behavior**
initialization of image aquirer

**Screenshots**
NA

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Python: 3.7.6
 - Harvester Versions: 1.0.3 to 1.2.0
 - GenTL Producer: Baumer GAPI SDK (64 Bit)
 - Camera: Baumer VCXU-23M https://www.baumer.com/medias/__secure__/Baumer_VCXU_23M_DS_EN.pdf?mediaPK=8798730682398

**Additional context**
Output for Harvesters 1.0.2:
```
1.0.2
C:\Program Files\Baumer GAPI SDK (64 Bit)\Components\Bin\bgapi2_usb.cti
[(id_='282500003F03', vendor='Baumer', model='VCXU-23M', tl_type='U3V', user_defined_name=None, serial_number='', version=None)]
done

Process finished with exit code 0
```

**Comment by kazunarikudo** [comment]
@monzelr Hi. Thank you for the report. I appreciate that. I'll get you back once I get a clue. /Kazunari

**Comment by kazunarikudo** [comment]
@monzelr Have you set any value to the `HARVESTERS_XML_FILE_DIR` env variable by yourself? Could you check if any value is assigned in the variable, please?

**Comment by monzelr** [comment]
No, I did not change it myself. What I tried to use different gentl producers, thus I also installed a gentl producer from Matrix Vision and from Baumer.

Using the command prompt and type in `set` returns the following env variables (actually there is no `HARVESTERS_XML_FILE_DIR`):
```
C:\Users\monzelrDESK>set
ALLUSERSPROFILE=C:\ProgramData
anaconda3=C:\Users\monzelrDESK\Anaconda3\envs\genicam;C:\Users\monzelrDESK\Anaconda3\envs\genicam\Scripts;C:\Users\monzelrDESK\Anaconda3\envs\genicam\Library\bin;C:\Users\monzelrDESK\Anaconda3\envs\genicam\Lib\site-packages;
APPDATA=C:\Users\monzelrDESK\AppData\Roaming
BGAPI2_SDK_PATH=C:\Program Files\Baumer GAPI SDK (64 Bit)\Components\
CLIENTNAME=MONZELR
CommonProgramFiles=C:\Program Files\Common Files
CommonProgramFiles(x86)=C:\Program Files (x86)\Common Files
CommonProgramW6432=C:\Program Files\Common Files
COMPUTERNAME=DESKTOP-71L6TIH
ComSpec=C:\Windows\system32\cmd.exe
CUDA_PATH=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2
CUDA_PATH_V10_2=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2
DriverData=C:\Windows\System32\Drivers\DriverData
FPS_BROWSER_APP_PROFILE_STRING=Internet Explorer
FPS_BROWSER_USER_PROFILE_STRING=Default
GENICAM_GENTL32_PATH=C:\Program Files\MATRIX VISION\mvIMPACT Acquire\bin
GENICAM_GENTL64_PATH=C:\Program Files\MATRIX VISION\mvIMPACT Acquire\bin\x64;C:\Program Files\Baumer GAPI SDK (64 Bit)\Components\Bin
HOMEDRIVE=C:
HOMEPATH=\Users\monzelrDESK
LOCALAPPDATA=C:\Users\monzelrDESK\AppData\Local
LOGONSERVER=\\DESKTOP-71L6TIH
MVIMPACT_ACQUIRE_DATA_DIR=C:\Users\Public\Documents\MATRIX VISION\mvIMPACT Acquire\
MVIMPACT_ACQUIRE_DIR=C:\Program Files\MATRIX VISION\mvIMPACT Acquire\
MWIMAQ_GENICAM_XML_FILES=C:\Program Files\Baumer GAPI SDK (64 Bit)\Tools\Common\CameraExplorer;C:\Program Files\Baumer GAPI SDK (64 Bit)\Components\Bin;C:\Program Files\Baumer GAPI SDK (64 Bit)\Tools\GigE\IpConfigTool;
NUMBER_OF_PROCESSORS=8
NVCUDASAMPLES10_2_ROOT=C:\ProgramData\NVIDIA Corporation\CUDA Samples\v10.2
NVCUDASAMPLES_ROOT=C:\ProgramData\NVIDIA Corporation\CUDA Samples\v10.2
NVTOOLSEXT_PATH=C:\Program Files\NVIDIA Corporation\NvToolsExt\
OneDrive=C:\Users\monzelrDESK\OneDrive
OS=Windows_NT
Path=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2\bin;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2\libnvvp;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files\TortoiseSVN\bin;C:\Users\monzelrDESK\Anaconda3\envs\genicam;C:\Users\monzelrDESK\Anaconda3\envs\genicam\Scripts;C:\Program Files\NVIDIA Corporation\Nsight Compute 2019.5.0\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Users\monzelrDESK\AppData\Local\Microsoft\WindowsApps;C:\Program Files\JetBrains\PyCharm Community Edition 2019.3.3\bin;;C:\Users\monzelrDESK\Anaconda3\envs\genicam;C:\Users\monzelrDESK\Anaconda3\envs\genicam\Scripts;
PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC
PROCESSOR_ARCHITECTURE=AMD64
PROCESSOR_IDENTIFIER=Intel64 Family 6 Model 79 Stepping 1, GenuineIntel
PROCESSOR_LEVEL=6
PROCESSOR_REVISION=4f01
ProgramData=C:\ProgramData
ProgramFiles=C:\Program Files
ProgramFiles(x86)=C:\Program Files (x86)
ProgramW6432=C:\Program Files
PROMPT=$P$G
PSModulePath=C:\Program Files\WindowsPowerShell\Modules;C:\Windows\system32\WindowsPowerShell\v1.0\Modules
PUBLIC=C:\Users\Public
PyCharm Community Edition=C:\Program Files\JetBrains\PyCharm Community Edition 2019.3.3\bin;
SESSIONNAME=RDP-Tcp#3
SystemDrive=C:
SystemRoot=C:\Windows
TEMP=C:\Users\MONZEL~1\AppData\Local\Temp
TMP=C:\Users\MONZEL~1\AppData\Local\Temp
USERDOMAIN=DESKTOP-71L6TIH
USERDOMAIN_ROAMINGPROFILE=DESKTOP-71L6TIH
USERNAME=monzelrDESK
USERPROFILE=C:\Users\monzelrDESK
VS140COMNTOOLS=C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\Tools\
windir=C:\Windows
```

**Comment by kazunarikudo** [comment]
@monzelr 

Hi. Thank you for your reply. Okay, so this is not a solution but could you try setting a value to `HARVESTERS_XML_FILE_DIR` env variable? It takes a path where XML files are stored. As far as I see the log Harvester tries to store an XML file it's downloaded from the device but the program does not have the right privilege to write a file to the destination, `C:\\Program Files\\Baumer GAPI SDK (64 Bit)\\Components\\Bin\\bgapi2_usb.cti_2.10.25119.25119.xml`.

By design, those XML files should be stored in the system temporary directory if `HARVESTERS_XML_FILE_DIR` is empty. So finding out why Harvester decided to save the XML files in `C:\\Program Files\\Baumer GAPI SDK (64 Bit)\\Components\\Bin` is the key for the solution.

/Kazunari

**Comment by monzelr** [comment]
Hi @kazunarikudo ,

setting the` HARVESTERS_XML_FILE_DIR` environmental variable did not solved the problem. The error did not changed.

However, debugging showed me in harvesters\core.py, function `_save_file`, **line 2963**: `file_path = os.path.join(file_dir, file_name)` 
for the variable `file_dir ` the value `'C:\\Users\\MONZEL~1\\AppData\\Local\\Temp\\20200519185754_gxpywg2u'`
and for the variable `file_name` the value `'C:\\Program Files\\Baumer GAPI SDK (64 Bit)\\Components\\Bin\\'`

After **line 2963**, the value of the variable `file_path` is `'C:\\Program Files\\Baumer GAPI SDK (64 Bit)\\Components\\Bin\\bgapi2_usb.cti_2.10.25119.25119.xml'`.

Before line 2963 I thus add the line:
`file_name = file_name.split(os.sep)[-1]`
which solved the problem. With this additional line, the xml-file will be correctly saved into `'C:\\Users\\MONZEL~1\\AppData\\Local\\Temp\\20200519185754_gxpywg2u\\bgapi2_usb.cti_2.10.25119.25119.xml'`.

Note: I also set the environmental variable `HARVESTERS_XML_FILE_DIR` to `C:\Users\monzelrDESK\Desktop` which also worked with my additional line of code. The xml file is then saved on my Desktop without any errors.

I appreciate it if you could check this behavior and try to reproduce this error.

**Comment by kazunarikudo** [comment]
@monzelr Hi, thank you for the update with the detailed description. It sounds like issue #145; I have fixed the issue in the master branch but have not yet uploaded to PyPI. Could you try the master branch if the issue is reproduced when you can, please? /Kazunari

**Comment by kazunarikudo** [comment]
@monzelr Hi again. If the master branch resolves the issue that you are facing, I will tag the HEAD version as version 1.2.1 and upload it to PyPI. Thank you. /Kazunari

**Comment by monzelr** [comment]
The issue above looks like my issue, but on a linux machine. And yes, the master branch resolves the issue! I also debugged the code at the critical lines and everything looks fine on my windows machine.

Thank you for your support. This issue can be closed.

**Comment by kazunarikudo** [comment]
@monzelr Hi. Thank you for the confirmation. I will release version 1.2.1 soon.
