### ISSUE TITLE
Bug when Pixelformat have a pixel size of 16 bit or 32 bit

### ISSUE THREAD

**Issue by timonehr** [genicam/harvesters#165]
**Describe the bug**
When you try to get images with the pixel size 16 bit or 32 bit you receive too small arrays

**To Reproduce**
1. Grab an image with 16 bit or 32 bit pixel size

**Expected behavior**
I expect for an image with the size 640 x 480 px and 16 bit pixel size an array with the size of 307200 px but i receive 153600 px.

The same for Coord3d_ABC32f: 640 px x 480 px * 3 and 32 bit pixel size would be an array with the size of 921600 px but i receive 230400 px

** Desktop
 - Harvester: 1.2.2

**Additional context**
`        array = numpy.frombuffer(
            self._buffer.raw_buffer, count=int(count),
            dtype='uint8',
            offset=self.data_offset`

Reads the right count of pixel but after:
`return pf_proxy.expand(array)`
the array have the wrong size. 

I think the `view()` of numpy decreases the size: 16 bit by factor 2 and 32 bit pixel size by factor 4.

**Comment by kazunarikudo** [comment]
@timonehr Hi. Thank you for the valuable report. I guess you have reproduced the phenomenon when a device is running as a 3D camera as you pointed out `Coord3d_ABC32f`, but would that be the same if it's running as a pure 2D camera? /Kazunari

**Comment by kazunarikudo** [comment]
@timonehr I have just created a development branch `_issue_165`. Could you try that out when you can, please? At least that branch should give you an opportunity to check if it fixes the issue for a 3D camera.

**Comment by timonehr** [comment]
@kazunarikudo Thanks for the fast fix. Yes now everything is fine again.
`Confidence8`, `Mono16 `und `Coord3d_ABC32f` are working again. 

At the beginning only `Confidence8` with 8 bit pixel size was the only format which was correct. It was a little bit unclear in the first post.

Thanks again

**Comment by kazunarikudo** [comment]
@timonehr Hi, thank you for making a try. I appreciate that. So may I merge the branch in the master branch?

**Comment by timonehr** [comment]
@kazunarikudo From my point of view: yes please.

**Comment by kazunarikudo** [comment]
@timonehr I have just released version 1.2.3. It's been uploaded to PyPI as well.
