### ISSUE TITLE
Live image stream freezes after a few frames

### ISSUE THREAD

**Issue by neelsbrink** [genicam/harvesters#168]
When moving the image acquisition (fetch_buffer) inside a loop from a JAI camera to a function I call, the live video freezes after about 10 frames

**To Reproduce**
Successfully list connected camera using .cti file (See code)
Run code (Ex 1) below successfully
Replace lines 14-17 with a call to getlive(ia) which now contains lines 14-17, see Ex 2 below
Camera image freezes after about 10 frames

**Expected behavior**
Live image stream

**Desktop (please complete the following information):**

OS: Windows 7
Python: 3.6 in PyCharm 2018.3.5
Harvester: latest from pip
GenTL Producer: MV
Camera: Jai BM 500 GE

Code:
#################
Ex1
#################
1 from harvesters.core import Harvester
2 import cv2
3
4 h = Harvester()
5
6 h.add_cti_file(r'C:\Program Files\MATRIX VISION\mvIMPACT Acquire\bin\x64\mvGenTLProducer.cti')
7 h.update_device_info_list()
8
9 ia = h.create_image_acquirer(0)
10 ia.start_image_acquisition()
11
12 while True:
13
14     with ia.fetch_buffer() as buffer:
15         component = buffer.payload.components[0]
16         ncol = component.width
17         nrow = component.height
18         image = component.data.reshape(nrow, ncol)
19
20        cv2.imshow('win1', image)
21        if cv2.waitKey(1) & 0xFF == ord('q'):
22           break
ia.destroy()
cv2.destroyAllWindows()
ia.stop_image_acquisition()
h.reset()
##################################################

#####################
Ex 2
######################
from harvesters.core import Harvester
import cv2

h = Harvester()

def getlive(ia):

    buffer = ia.fetch_buffer()
    component = buffer.payload.components[0]
    width=component.width
    height=component.height
    image = component.data.reshape(height, width)
    ret = 1
    return (ret, image)

h.add_cti_file(r'C:\Program Files\MATRIX VISION\mvIMPACT Acquire\bin\x64\mvGenTLProducer.cti')
h.update_device_info_list()

ia = h.create_image_acquirer(0)
ia.start_image_acquisition()

while True:
    ret, image = getlive(ia)
    cv2.imshow('win1', image)
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break

ia.destroy()
cv2.destroyAllWindows()
ia.stop_image_acquisition()
h.reset()

**Comment by kazunarikudo** [comment]
@neelsbrink Hi. Thank you for trying out Harvester. I can see the following line in your failure case:
```
buffer = ia.fetch_buffer()
```
You fetch a buffer. Good. So when do you queue the buffer back to Harvester? Harvester will not have a buffer to fill up until you queue it back. If you do not queue any buffer back to Harvester then it will have nothing to fill up the coming images. 

You can queue a buffer back calling its `queue()` method:
```
buffer.queue()
```
I hope it helps.
Regards, Kazunari.

**Comment by kazunarikudo** [comment]
@neelsbrink Please feel free to re-open this ticket if the suggestion above does not fix the issue.

**Comment by neelsbrink** [comment]
Hi and thank you. I have looked at the example in Harvesters Doc where the buffer.queue() is performed after fetch_buffer, but in my code the image data is then all zeros. Or do I need to apply the queue elsewhere?

**Comment by kazunarikudo** [comment]
@neelsbrink Hi. Queueing here I mean is to allow Harvester (it's actually a GenTL Producer) to overwrite the buffer content. If you want to hold it after queueing it, you would need to copy the content to another object. Does this make sense? /Kazunari

**Comment by neelsbrink** [comment]
I am missing something. I use 
buf=buffer
component = buf.payload.components[0]
width=component.width
height=component.height
image = component.data.reshape(height, width)
buffer.queue()

but still the image I get is zeros

**Comment by kazunarikudo** [comment]
@neelsbrink Okay. So I would suggest you to check what “copy” and “assignment” mean in Python.

**Comment by neelsbrink** [comment]
Yes, I have tried buf=copy.copy(buffer) but still  the image data has no contents

**Comment by kazunarikudo** [comment]
@kazunarikudo Thank you for the update. So would you be able to reproduce the phenomenon with Harvester 1.2.1? You can try version 1.2.1 executing the following command:
```
$ pip uninstall harvesters
$ pip install harvesters==1.2.1
```
You can check the version with the following Python code:
```
import harvesters
print(harvesters.__version__)
```

**Comment by kazunarikudo** [comment]
By the way, have you already resolved the "live image stream freezes" issue?

**Comment by neelsbrink** [comment]
Unfortunately not, v 1.2.1 causes no change.

**Comment by kazunarikudo** [comment]
@neelsbrink One more question, could you tell me the pixel format, please?

**Comment by kazunarikudo** [comment]
> Unfortunately not, v 1.2.1 causes no change.

Which issue do you mean, the all-zero issue, or the "image stream freezes" issue?

**Comment by neelsbrink** [comment]
Without the queue the image feezes, with the queue as I am using it currently I don't get an image back. Pixel format is Mono8.

**Comment by kazunarikudo** [comment]
So could you tell me when an image turns all-zero, please?

**Comment by neelsbrink** [comment]
When I use the queue here, I get the message:
 _image = component.data.reshape(height, width)
ValueError: cannot reshape array of size 5054448 into shape (0,0)_

   buffer = ia.fetch_buffer()
    buf=copy.copy(buffer)
    buffer.queue()
    component = buf.payload.components[0]
    width=component.width
    height=component.height
    image = component.data.reshape(height, width)
    ret = 1
    return (ret, image)

and when I use it as shown below, the image is black and I dont know whether it freezes. I can only see that it freezes when I dont use queue:
    buffer = ia.fetch_buffer()
    buf=copy.copy(buffer)
    component = buf.payload.components[0]
    width=component.width
    height=component.height
    image = component.data.reshape(height, width)
    ret = 1
    buffer.queue()
    return (ret, image)

**Comment by kazunarikudo** [comment]
Would you be able to reproduce the phenomenon with another camera? As far as I heard the information from you, I think your use case is not special and so many people have confirmed it works with Harvester. I would expect you to keep researching the issue by yourself a bit more if possible.

**Comment by neelsbrink** [comment]
Ok thanks will do so, dont have another camera to check

**Comment by kazunarikudo** [comment]
@neelsbrink Hi. I'm sorry that I could not point out the root cause for you. However, I believe the issue you are facing is not so twisted. You would say "a-ha!" in the end. PS. I understand there always be a reason but it's worth owning several cameras; they help you to compare the results to narrow out the root cause.
