### ISSUE TITLE
Mono16 format returns a shorter image array.

### ISSUE THREAD

**Issue by ThermoGnad** [genicam/harvesters#169]
Hello kazunarikudo, 
thank you very much for your great work, it makes my live so much easier. However, I have two problems to get my acquisition working properly.
OS: Windows 10, 64 bit
Python: Python 3.6.8
Harvester: 1.2.3
GenTL Producer: Matrix Vision
Camera: IRS640, (Automation Technology), Mono16, nominal FPS: 94.8 (due to ROI)
- When I try to get images I receive too small arrays (related issu #165 )
It's exactly the same behavior described by timonehr. When debugging the my script, the buffer properties are: "640 x 256, Mono16, 81920 elements,... ", so I got exactly the half of the needed elements.
- The aquisition framerate is too low (related issu #131 )
Unfortunately, I don't get higher framerates than around 20FPS (If the desired framrate is set to any value lower than 20 it works accurate.) 
I wonder if the problem maybe caused by operator errors, a bug in the library, wrong setup...
Hopefully, you can help me to find the solution.

**Comment by kazunarikudo** [comment]
@ThermoGnad Hi, thank you for the report. Please excuse me, at least the first issue is a bug of Harvester. I have just created branch `_issue_169` so could you try that out when you can please? In addition, I am afraid but I would appreciate it if you could create another issue ticket for the latter issue. /Kazunari

**Comment by ThermoGnad** [comment]
@kazunarikudo Hi, I tested the branch and it works fine! Thanks. Of course I will create another Ticket for the latter issue.
ThermoGnad
