### ISSUE TITLE
USB-API not available

### ISSUE THREAD

**Issue by theytaz3** [genicam/harvesters#186]
**Describe the bug**

Hello,

Want to make a driver compatible with two cameras from two different manufacturers (ids and basler) accepting genicam. I would like to use your library.

So I installed as in the tutorial the GenTL Producers from Matrix vision (mvGenTL_Acquire-x86_64-2.38.0.exe) with my cameras connected in usb3.

I recovered the file mvGenTLProducer.cti and I copied/pasted it in the folder of my pycharm project. 

 I have in my python script :

h = Harvester()
h.add_file('mvGenTLProducer.cti')
h.update()

I retrieve with print(h.device_info_list[0]) the following information : 

(id_='VID1409_PID8000_4103771196', vendor='IDS Imaging Development Systems', model='U3-328xCP-C', tl_type='U3V', user_defined_name=None, serial_number='4103771196', version='1.1.1.100002b.1')

but when I attempt a 

ia = h.create_image_acquire(0)

I have the following error:

  File "C:/Users/User/Documents/[Dev]/test_genicam/test_camera.py", line 16, in <module>
    ia = h.create_image_acquire(0)

  File "C:\Users\AppData\Roaming\Python37\site-packages\harvesters\core.py", line 3209, in create_image_acquirer
    device.open(_privilege)

  File C:UsersAppDataRoamingPython37site-packagesgenicam.py", line 3189, in open.
    return _gentl.Device_open(self, accessFlags)

AccessDeniedException: GenTL exception: Requested operation is not allowed. (Message from the source: Failed to open device 'VID1409_PID8000_4103771196'. USB-API not available) (ID: -1005)

**Desktop:**
 - OS:  Windows 10
 - Python: 3.7
 - Harvester: 1.2.6
 - GenTL Producer: Matrix vision
 - Camera: Ids

**Comment by theytaz3** [comment]
I did a little research and found that ids had their own GenTL. So I installed their driver and I copied their cti file (ids_u3vgentlk.cti)

I get the following error: 

![Capture](https://user-images.githubusercontent.com/33628286/86133536-b7f9c580-bae8-11ea-83af-22d2ce3855b0.JPG)

**Comment by kazunarikudo** [comment]
@theytaz3 Hi, thank you for trying out Harvester. 

>  I copied/pasted it in the folder of my pycharm project.

Could you try to read [this artcile](https://github.com/genicam/harvesters/wiki/FAQ#i-pointed-out-a-cti-file-but-harvester-says-the-image-doesnt-exist-part-2), please? /Kazunari

**Comment by theytaz3** [comment]
thanks for your reply, i find the solution !

I delete Matrix Vision Driver and now i can open the camera. It's due by a incompatibility between ids driver and Matrix vision driver. 

Bug resolved.

**Comment by kazunarikudo** [comment]
Congratulations!
