### ISSUE TITLE
Support Bayer16 formats

### ISSUE THREAD

**Issue by kazunarikudo** [genicam/harvesters#19]
**Is your feature request related to a problem? Please describe.**
Support the following Bayer16 formats:

* ``BayerGR16``
* ``BayerRG16``
* ``BayerGB16``
* ``BayerBG16``

**Describe the solution you'd like**
Harvester Core should support those formats.

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by severij** [comment]
@kazunarikudo I'm only able to test `BayerRG16` with our camera, but it works. :+1:

**Comment by kazunarikudo** [comment]
For people who those confirmed any of pixel formats didn't work: Please reopen this issue again once you noticed it.
