### ISSUE TITLE
Mono14 support?

### ISSUE THREAD

**Issue by mikeoconnor0308** [genicam/harvesters#190]
To add Mono14 pixel format support.

**Describe the solution you'd like**

To be able to use Mono14 pixel format. 

**Describe alternatives you've considered**

Using the genicam python api directly. 

**Additional context**

Based on the documentation, it appears that [Mono14 is not supported](https://harvesters.readthedocs.io/en/latest/#pixel-formats-that-harvester-core-supports).

However, from looking in the code, it looks like there is [some support](https://github.com/genicam/harvesters/blob/5f8d0a235328ab692bf348938632c635239d0b5e/src/harvesters/test/test_harvester_core.py#L820) for Mono14

Could you confirm if Mono14 is supported or not, and if not, what would be required to add it?

**Comment by kazunarikudo** [comment]
@mikeoconnor0308 Hi, thank you for your message.

> Based on the documentation, it appears that Mono14 is not supported.

Please excuse me, that content has been obsolete. The current version supports Mono14. Please let me know if did not work. /Kazunari.

**Comment by mikeoconnor0308** [comment]
Excellent, thanks for the speedy reply! I'll report back if it doesn't work.

**Comment by mikeoconnor0308** [comment]
Turns out the camera actually uses Mono16 (despite what the specs said), which works.
