### ISSUE TITLE
Inconsistent Image height retrieved from genicam producers with FLIR A325 camera

### ISSUE THREAD

**Issue by mikeoconnor0308** [genicam/harvesters#193]
**Describe the bug**

Thanks for the great library, and apologies in advance for what I'm sure is going to be a niche issue. 

The first frame acquired from an FLIR A325 camera correctly detects 320x240 image size, and allocates the correct numpy array accordingly. From the second frame onwards, however, a height of 246 is returned when getting the [buffer height](https://github.com/genicam/harvesters/blob/f437a2d41d419198dc4a5b0818d003f92bb2b538/src/harvesters/core.py#L867), which results in numpy array having the wrong size: 

```
ValueError: buffer is smaller than requested size
```

The raw buffer is the _correct_ size (320\*240\*2 = 153600 bytes), but the numpy array ends up being 320\***246**\*2 = 157440 bytes.
If I force Harvesters to use the node map values for the width and height, then the image acquisition works perfectly. 

It seems the buffer width and height from genicam cannot be relied upon?

**To Reproduce**
* Acquire a very specific camera (FLIR A325) (sorry).
* Acquire a couple of frames: 

```python
from harvesters.core import Harvester

N_FRAMES = 60
h = Harvester()

cti_path = '/opt/mvIMPACT_Acquire/lib/x86_64/mvGenTLProducer.cti'
#cti_path = '/opt/baumer-gapi-sdk/lib/libbgapi2_gige.cti'

h.add_file(cti_path)
h.update()

print(len(h.device_info_list))
print(h.device_info_list)

ia = h.create_image_acquirer(0)

ia.remote_device.node_map.Width.value = 320
ia.remote_device.node_map.Height.value = 240

ia.remote_device.node_map.PixelFormat.value = 'Mono16'
ia.remote_device.node_map.IRFrameRate.value = 'Rate15Hz'

ia.start_acquisition(run_in_background=False)

for i in range(N_FRAMES):
    print('frame', i)
    with ia.fetch_buffer() as buffer:
        image_component = buffer.payload.components[0]
        # typically I would do something with the image here.

ia.stop_acquisition()
ia.destroy()
h.reset()
```

```
frame 0
reported frame size: 320, 240
frame 1
reported frame size: 320, 246
Traceback (most recent call last):
  File "/home/mike/code/genicam-starter/harvesters/acquire_test.py", line 57, in <module>
    with ia.fetch_buffer() as buffer:
  File "/home/mike/anaconda3/envs/harvester/lib/python3.6/site-packages/harvesters/core.py", line 2728, in fetch_buffer
    logger=self._logger
  File "/home/mike/anaconda3/envs/harvester/lib/python3.6/site-packages/harvesters/core.py", line 1132, in __init__
    logger=self._logger
  File "/home/mike/anaconda3/envs/harvester/lib/python3.6/site-packages/harvesters/core.py", line 1265, in _build_payload
    buffer=buffer, node_map=node_map, logger=logger
  File "/home/mike/anaconda3/envs/harvester/lib/python3.6/site-packages/harvesters/core.py", line 1441, in __init__
    buffer=buffer, node_map=node_map
  File "/home/mike/anaconda3/envs/harvester/lib/python3.6/site-packages/harvesters/core.py", line 1364, in _build_component
    logger=self._logger
  File "/home/mike/anaconda3/envs/harvester/lib/python3.6/site-packages/harvesters/core.py", line 837, in __init__
    self._data = self._to_np_array(proxy)
  File "/home/mike/anaconda3/envs/harvester/lib/python3.6/site-packages/harvesters/core.py", line 885, in _to_np_array
    offset=self.data_offset
ValueError: buffer is smaller than requested size
Process finished with exit code 1

```

**Expected behavior**
The height should consistently be 240 pixels.

**Desktop (please complete the following information):**
 - OS: Ubuntu18.04
 - Python: 3.6.11
 - Harvester: 1.2.8
 - GenTL Producer: mvIMPACT_Acquire, and Baumer
 - Camera: FLIR A325

**Additional context**

**Comment by kazunarikudo** [comment]
@mikeoconnor0308 Hi, Mike. Thank you for the report. Can the issue be reproduced with both MATRIX VISION and Baumer? In general, GenTL consumer, a roll that Harvester plays, should follow the information that its GenTL Producer provides. One thing I have in my mind is the hight `246` is coming from a fact such as an image has additional padding 6 lines in the bottom due to a transport layer related requirement, etc. Unfortunately, I can't work for Harvester during the daytime because Harvester is just a private project but I will try to give you some items to debug the issue. /Kazunari

**Comment by BrianOfrim** [comment]
@mikeoconnor0308 Hi Mike, FLIR is planning to release their own genTL producer in an upcoming release of the FLIR Spinnaker Image Acquisition SDK. There is a beta release available that includes the genTL producer here for Ubuntu 18.04 amd64: https://flir.box.com/s/xta9oxqq89ndej0yeyd1pe44nls9eosr (spinnaker-2.1.0.82-amd64-pkg.tar.gz) It might be worth a shot to try the producer installed with Spinnaker to see if the behavior is the same as the mvIMPACT_Acquire/Baumer producers or not.

**Comment by kazunarikudo** [comment]
@BrianOfrim Hi, Brian. Thank you for sharing the information with us. I appreciate that. /Kazunari.

**Comment by BrianOfrim** [comment]
For the record the production releases of Spinnaker now include a GenTL producer. Download location: https://www.flir.com/products/spinnaker-sdk/
