### ISSUE TITLE
problem with cti file

### ISSUE THREAD

**Issue by tahasadr** [genicam/harvesters#200]
Hi there!
I have installed python and harvesters successfully and also tried to install mvGenTL Acquire from matrix vision website. I have a TheImagingSource camera.
you said to find a cti file in the installation folder of mvGenTL. I've found one in "/opt/mvIMPACT_Acquire/lib/x86_64/mvGenTLProducer.cti". I copied that file in another directory and added this file by "h.add_file(CTI_FILE_LOCATION)" command and then updated the 'h'. I finally connected my camera using USB3 and got the length of device list but it was zero.
what is the probelm? Is it about cti file? I searched for GenTL from TheImagingSource but found nothing.

**Comment by kazunarikudo** [comment]
@tahasadr Hi. An CTI file is a shared library so it must be placed in the right locations and you should not move it as long as you do not know where should it be. /Kazunari

**Comment by kazunarikudo** [comment]
JFYI: https://github.com/genicam/harvesters/wiki/FAQ#answer-13

**Comment by tahasadr** [comment]
Thanks a lot. It's done!
