### ISSUE TITLE
Reconnect and Alive function

### ISSUE THREAD

**Issue by tobiasf88** [genicam/harvesters#202]
It would be nice to get a possibility to reconnect. In a test, I disconnected the camera and then reconnected it. I have to reload the harvesters library completely, otherwise no more cameras will be found. 

Also a function would be good to see if the camera is still available without stop_acquisition() (an advantage for hardware triggers).

**Comment by binflo13** [comment]
I would like to know if there has been any advance in this issue. I would like to be able to diconnect and reconnect the camera at any time, but the acquirer is not finding any cameras.

**Comment by kazunarikudo** [comment]
Hi, the issue could be resolved but we need to admit that it needs a GenTL producer that can detect such an event and that is not a mandatory feature. Of course, it should be a great feature but it may take some time to start working on this. Please excuse me! Regards, Kazunari.
