### ISSUE TITLE
problem with start_acquisition()

### ISSUE THREAD

**Issue by theytaz3** [genicam/harvesters#203]
hello,

I have a problem with the start_acquisition method. 

I create my camera with : 
self.camera =  harvest.create_image_acquirer(serial_number=self.serial_number)

I have no problem with the creation of my camera object.

I set up my camera with these parameters : 

        self.node_map.UserSetSelector = "Default"
        self.node_map.UserSetLoad.execute()
        self.node_map.PixelFormat = "RGB8"
        self.node_map.AcquisitionMode.value = "SingleFrame"
with : 
      self.node_map = self.camera.remote_device.node_map

when I call the method self.camera.start_acquisition(), I get the following error message : 

![image](https://user-images.githubusercontent.com/33628286/94163146-c9543300-fe87-11ea-9cbd-e17c23c09ebf.png)

ps : i use ids producer ( ids_u3vgentlk.cti) because my cameras are ids

**Comment by kazunarikudo** [comment]
@theytaz3 Thank you for the report. As far as I read the backtrace, it's telling us the buffer memory that Harvester prepared was small for the data the source is trying to transmit. I will check the detail when I can and get you back. In the meantime, could you check if there's another pixel format that works for you, please? /Kazunari

**Comment by theytaz3** [comment]
Hi ! 

I change pixelFomart and this action work with Mono8, BayerRG but not with rgb8 or bgr8. 

How can increase my buffer size for have rgb8 format ?

**Comment by theytaz3** [comment]
so, i see that the buffer dimensions can be modified in the start_acquisition method of the ImageAcquire class. 

![image](https://user-images.githubusercontent.com/33628286/94279699-c4a58280-ff4c-11ea-8db8-87ec57c1ca47.png)

However, I do not wish to modify the code of the harvesters.core.py script to solve my problem. 
So I tried to modify data_stream.payload_size directly in my init method of my class camera encapsulating ImageAcquire object : 

![image](https://user-images.githubusercontent.com/33628286/94279948-1b12c100-ff4d-11ea-840a-4ea2b13d5230.png)

self.camera being my object ImageAcquire.

but i have this error : 

can't set attribute on my line : 

![image](https://user-images.githubusercontent.com/33628286/94280252-7a70d100-ff4d-11ea-8f0a-5a7b83b9e1ea.png)

how do I set this attribute?

**Comment by kazunarikudo** [comment]
@theytaz3 Sorry for having kept you waiting on this. This issue is implying there could be a defect in the array conversion. I do not mind if you modify the code but the task should be done by Harvester by design. I wish I could start to work on this as soon as possible but there are some other prioritized tasks (Harvester is just one of my hobby project in reality). I will let you know once I started to work on this. Until then, please excuse me!
