### ISSUE TITLE
 Parameter not valid or out of range. (Message from the source: Error Inquire buffer info) (ID: -1009)

### ISSUE THREAD

**Issue by leitoxve** [genicam/harvesters#204]
**I have done the code example in python and I have problems calling the function `ia.fetch_buffer`
this is my code :**
` #!/usr/bin/env python3
import numpy as np
from harvesters.core import Harvester
h = Harvester()

print (h.add_cti_file('/opt/cvb/drivers/genicam/libGevTL.cti'))

print("file",h.files)
print("update",h.update())
print ("list",h.device_info_list)
ia = h.create_image_acquirer(serial_number="S1220901")
print ("ia",ia)
ia.remote_device.node_map.Width.value = 5120
ia.remote_device.node_map.Height.value = 5120
ia.remote_device.node_map.PixelFormat.value = 'Mono8'

ia.start_acquisition(run_in_background=False)
print("device",ia.device)
ia.remote_device.node_map.AcquisitionStart.value = True

with ia.fetch_buffer(timeout=1) as buffer:
    # Work with the Buffer object. It consists of everything you need.
    print ("--------------with1---")
    print(buffer)
    print ("--------------with2---")
    component = buffer.payload.components[0]
    print ("--------------with3---")
    # The buffer will automatically be queued.

ia.stop_acquisition()

ia.destroy()

h.reset()`

**and this is the output** 

 python3 camera_nano.py 
None
file ['/opt/cvb/drivers/genicam/libGevTL.cti']
GenTL producer does not implement IFGetParentTL
GenTL producer does not implement DevGetParentIF
GenTL producer does not implement DSGetParentDev
GenTL producer does not implement DSGetNumBufferParts
GenTL producer does not implement DSGetBufferPartInfo :+1: 
update None 
list [(id_='::ID->00-01-0D-C4-C4-CC::10.104.0.10', vendor='Teledyne DALSA', model='NanoXL-M5100', tl_type='GEV', user_defined_name='S1220901', serial_number='S1220901', version=None)] :+1: 
ia <harvesters.core.ImageAcquirer object at 0x7fad91e247f0> :+1: 
device <harvesters.core.Device object at 0x7fad91db30f0> :+1: 
Traceback (most recent call last):  :-1: 
  File "camera_nano.py", line 47, in <module> :-1: 
    with ia.fetch_buffer(timeout=1) as buffer:
  File "/home/roc1/.local/lib/python3.6/site-packages/harvesters/core.py", line 2725, in fetch_buffer
    logger=self._logger
  File "/home/roc1/.local/lib/python3.6/site-packages/harvesters/core.py", line 1129, in __init__
    logger=self._logger
  File "/home/roc1/.local/lib/python3.6/site-packages/harvesters/core.py", line 1262, in _build_payload
    buffer=buffer, node_map=node_map, logger=logger
  File "/home/roc1/.local/lib/python3.6/site-packages/harvesters/core.py", line 1438, in __init__
    buffer=buffer, node_map=node_map
  File "/home/roc1/.local/lib/python3.6/site-packages/harvesters/core.py", line 1361, in _build_component
    logger=self._logger
  File "/home/roc1/.local/lib/python3.6/site-packages/harvesters/core.py", line 837, in __init__
    self._data = self._to_np_array(proxy)
  File "/home/roc1/.local/lib/python3.6/site-packages/harvesters/core.py", line 867, in _to_np_array
    h = self._buffer.height
  File "/home/roc1/.local/lib/python3.6/site-packages/genicam/gentl.py", line 4371, in _get_height
    return _gentl.Buffer__get_height(self)
_**gentl.InvalidParameterException: GenTL exception: Parameter not valid or out of range. (Message from the source: Error Inquire buffer info) (ID: -1009)**  :-1: 

Anyone have any ideas ?? I am using a Genie Nano XL
python 3 and Harvester 1.2.8???

**Comment by kazunarikudo** [comment]
@leitoxve Hi, sorry having kept you waiting. Please make a try with the latest one in the master branch. /Kazunari
