### ISSUE TITLE
Harvester GUI : No device with  TLSimu.cti  

### ISSUE THREAD

**Issue by PLICHET** [genicam/harvesters#205]
Hi,
Thanks for this library.

I'm on Windows 10, I'm using Python 3.6 for tensorflow object recognition API.
I would like to use a Genicam camera.
I installed Harvester core & GUI without issue but when i put the CTI file at C: \ Users \ME\ AppData \ Local \ Programs \ Python \ Python36 \ Lib \ site-packages \ genicam \ TLSimu.cti but i have no device in the list !
In the consol log i have just:
WARNING: QCssParser :: parseColorValue: Specified color without alpha value but alpha given: 'rgb 0, 0, 0, 0%'
WARNING: QCssParser :: parseColorValue: Specified color without alpha value but alpha given: 'rgb 0, 0, 0, 0%'
WARNING: QCssParser :: parseColorValue: Specified color without alpha value but alpha given: 'rgb 0, 0, 0, 0%'

Can you help me ?
  Thanks.

**Comment by PLICHET** [comment]
I do not use Anaconda, I will try with ...

**Comment by PLICHET** [comment]
![image](https://user-images.githubusercontent.com/11979923/95987860-4ab83900-0e28-11eb-84f0-882f22e07135.png)
Same issue with Anaconda

**Comment by kazunarikudo** [comment]
@PLICHET Hi. Would [this](https://github.com/genicam/harvesters/wiki/FAQ#harvester-fails-to-load-tlsimu-whats-happening) resolve the issue? /Kazunari

**Comment by PLICHET** [comment]
Thanks for answering,

I did not have a typical error "harvesters.core :: ERROR :: GenTL exception: Failed to load CTI file; The specified module could not be found. (ID: -10001)

![image](https://user-images.githubusercontent.com/11979923/95997731-5e699c80-0e34-11eb-8180-df79c1628e6d.png)

Just a empty liste :(
I have add a dependency DLL called VirtualFG to the PATH environment variable with same probleme.

**Comment by PLICHET** [comment]
I tried with another cti file with "baumer gap"i and "Basler gapi" but no work.
I think I forgot something...

**Comment by PLICHET** [comment]
Hello,

Can you explain this 👍 
<bound method Harvester.add_file of <harvesters.core.Harvester object at 0x000002A52F71CCF8>> thanks

**Comment by PLICHET** [comment]
Hi 
I find the error  


> @PLICHET Hi. Would [this](https://github.com/genicam/harvesters/wiki/FAQ#harvester-fails-to-load-tlsimu-whats-happening) resolve the issue? /Kazunari

I copy paste VirtualFG.dll to C:\Windows\System32
Now it s ok 👍

**Comment by afiqmuzaffar** [comment]
> Hi I find the error
> 
> > @PLICHET Hi. Would [this](https://github.com/genicam/harvesters/wiki/FAQ#harvester-fails-to-load-tlsimu-whats-happening) resolve the issue? /Kazunari
> 
> I copy paste VirtualFG.dll to C:\Windows\System32 Now it s ok 👍

Hi @PLICHET ,

is there any sample source code we could refer for tensorflow with genicam?

**Comment by afiqmuzaffar** [comment]
Found one https://github.com/BrianOfrim/harvesters-inference if someone looking for reference although in Pytorch..

Looking forward on tensorflow site. 

May everything good, lets coding :)

**Comment by saki87** [comment]
> efer for tensorflow with genica

what is the linux version of this action?
