### ISSUE TITLE
Open device by IP address?

### ISSUE THREAD

**Issue by StefanD986** [genicam/harvesters#208]
**Is your feature request related to a problem? Please describe.**
Opening a GigE Vision camera device with harvester requires the following steps
  1. Create Harvester instance
  2. Load CTI files
  3. Update camera list
  4. Open device from (updated) device list

For GigE Vision cameras Step *3.* takes quite a while (for me 20-30 seconds). Especially on computers with multiple NICs this is the case because I assume all NICs are scanned for cameras.

**Describe the solution you'd like**
Give that the camera device has a constant IP, I'd like to skip the step 3. and just open the device by its IP address directly, e.g. by passing an IP address to Harvesters `create_image_acquirer` function.

**Describe alternatives you've considered**
I don't know of an alternative solution. Ideas are welcome.

**Comment by minewarriorsSchool** [comment]
I myself do not have this problem. I use 2 gigE camera's and they pretty much load instantly. using the MATRIX VISION .cti file.

**Comment by StefanD986** [comment]
How many network interfaces do you have?

I have 10 network interfaces (some are virtual due to VMs and VPN connections), and I think that is why it takes quite long to load because I can see in the logs (if I enable them) that it looks for cameras on all network interfaces.

but I’ll try your suggestion with the matrix vision cti aswell. Currently I am using the cti from the camera manufacturer (allied vision).

**Comment by mahmoudabderahman** [comment]
Hi @StefanD986, have you found a way to connect to the camera through an IP Address?

Best,

**Comment by StefanD986** [comment]
No unfortunately not.

**Comment by kazunarikudo** [comment]
Hi, I am afraid, as far as I know, GenTL does not define a way to open a device by using an interface-specific information piece such as an IP address as a key. To open a device we need to use an ID that the accompanying GenTL Producer tells its GenTL Consumer such as Harvester. If the software were very close to the machine vision standard, assume a GEV-specific software, it should be able to offer a way to achieve your expectation but we are on some higher layer where we cannot touch the information.
