### ISSUE TITLE
Random crash caused by _gentl.pyd

### ISSUE THREAD

**Issue by wuyuanyi135** [genicam/harvesters#211]
**Describe the bug**
I have been running a usb3vision industrial camera with this library. I noticed random crash that brought down the python kernel without throwing any error. The frequency varies from several minutes to hours. The trigger of this crash is still unclear. I included the event log from Windows event logger.

**To Reproduce**
Random behavior. Unable to provide reproduce steps

**Expected behavior**
No crash or crash with catchable exception

**Screenshots**
Not available

**Desktop (please complete the following information):**
 - OS: Windows
 - Python: 3.8.5
 - Harvester: 1.2.8
 - GenTL Producer: Hikvision producer
 - Camera: Hikvision MV-CA016-10UM

**Additional context**
This is the only error log I found relating to the problem in windows event logger. Please let me know if more useful log file should be retrieved from a different location.

```xml
Log Name:      Application
Source:        Application Error
Date:          11/11/2020 3:07:58 AM
Event ID:      1000
Task Category: (100)
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      DESKTOP-5DGC6MF
Description:
Faulting application name: python.exe, version: 3.8.5150.1013, time stamp: 0x5f6cc7c6
Faulting module name: _gentl.pyd, version: 0.0.0.0, time stamp: 0x5ee19a48
Exception code: 0xc0000005
Fault offset: 0x00000000000ca373
Faulting process id: 0x5484
Faulting application start time: 0x01d6b7f63ac7cc0e
Faulting application path: C:\Users\wuyua\anaconda3\envs\RxExperiments\python.exe
Faulting module path: C:\Users\wuyua\anaconda3\envs\RxExperiments\lib\site-packages\genicam\_gentl.pyd
Report Id: b38eeca5-a4d5-4eab-8b24-64b0696d15eb
Faulting package full name: 
Faulting package-relative application ID: 
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application Error" />
    <EventID Qualifiers="0">1000</EventID>
    <Version>0</Version>
    <Level>2</Level>
    <Task>100</Task>
    <Opcode>0</Opcode>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2020-11-11T08:07:58.2142368Z" />
    <EventRecordID>82596</EventRecordID>
    <Correlation />
    <Execution ProcessID="0" ThreadID="0" />
    <Channel>Application</Channel>
    <Computer>DESKTOP-5DGC6MF</Computer>
    <Security />
  </System>
  <EventData>
    <Data>python.exe</Data>
    <Data>3.8.5150.1013</Data>
    <Data>5f6cc7c6</Data>
    <Data>_gentl.pyd</Data>
    <Data>0.0.0.0</Data>
    <Data>5ee19a48</Data>
    <Data>c0000005</Data>
    <Data>00000000000ca373</Data>
    <Data>5484</Data>
    <Data>01d6b7f63ac7cc0e</Data>
    <Data>C:\Users\wuyua\anaconda3\envs\RxExperiments\python.exe</Data>
    <Data>C:\Users\wuyua\anaconda3\envs\RxExperiments\lib\site-packages\genicam\_gentl.pyd</Data>
    <Data>b38eeca5-a4d5-4eab-8b24-64b0696d15eb</Data>
    <Data>
    </Data>
    <Data>
    </Data>
  </EventData>
</Event>
```

**Comment by wuyuanyi135** [comment]
Apparently the c0000005 is due to memory access violation. I am not sure if this problem may relate to 
* The callback I used for harvesters
* The harvesters library
* The gentl upstream code
* The producer

**Comment by kazunarikudo** [comment]
Hi, I guess that'd be a bug in the `genicam` package. According to your report, the frequency is random so do you think you can narrow down the event it is caused? I would appreciate it if you could narrow down the possible events. As far as I hear the information, if the issue can happen in several minutes then other people must have faced the same issue. Again, I would admit that's a bug but I would like to know the characteristics of the behavior. Thank you. /Kazunari.

**Comment by wuyuanyi135** [comment]
Thank you @kazunarikudo . I could not narrow down the issue since its random nature. I could only assume that the vendor's cti implementation is broken because this never happens to me when using the Allied Vision cameras. I have switched to the C-API provided by Hikvision at this moment and I will close this issue for now. I would be glad to help if later the similar problems being reported by others.
