### ISSUE TITLE
Fix error when harvesters receives incomplete buffer

### ISSUE THREAD

**Issue by timonehr** [genicam/harvesters#214]
**Describe the bug**
When you have a high load on you network card or work with a virtual machine, you can get a incomplete buffer.

The incomplete buffer produces an error and the buffer is not requeued.

After 15 errors the producer have no buffer in the queue.

**To Reproduce**
Take a virtual machine and use a bridged network interface and grab images. When the buffer is incomplete you receive will receive an error:

> Traceback (most recent call last):
  File "/home/test/.local/lib/python3.8/site-packages/harvesters/core.py", line 2567, in fetch_buffer
    self._update_chunk_data(buffer=_buffer)
  File "/home/test/.local/lib/python3.8/site-packages/harvesters/core.py", line 2430, in _update_chunk_data
    if buffer.num_chunks == 0:
  File "/usr/lib/python3/dist-packages/genicam/gentl.py", line 4395, in _get_num_chunks
    return _gentl.Buffer__get_num_chunks(self)
_gentl.InvalidHandleException: GenTL exception: Given handle does not support the operation. (Message from the source: Given handle does not support the operation) (ID: -1006)

Harvesters try to access the `num_chunks` even though the buffer is incomplete.

**Expected behavior**
The buffer should not be delivered and discarded and requed by harvesters

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Python: 3.8
 - Harvester: 1.2.8

**Solution**

The method `fetch_buffer()` have a bug in handles incomplete buffer. 

Furthermore i'm not sure if the indention is right:
https://github.com/genicam/harvesters/blob/482b143a5cb8ba36e5259f9a1d6a5e55535164e0/src/harvesters/core.py#L2740
I think harvesters shouldn't deliver a `_buffer` when is incomplete? Otherwise we could save the check for incomplete buffer.

My suggestion:
https://github.com/genicam/harvesters/blob/482b143a5cb8ba36e5259f9a1d6a5e55535164e0/src/harvesters/core.py#L2723
```python
                   # Check if the delivered buffer is complete:
                    if event_manager.buffer.is_complete():
                        #
                        if _is_logging_buffer_manipulation:
                            self._logger.debug(
                                'Acquired Buffer module #{0}'
                                ' containing frame #{1}'
                                ' from DataStream module {2}'
                                ' of Device module {3}'
                                '.'.format(
                                    event_manager.buffer.context,
                                    event_manager.buffer.frame_id,
                                    event_manager.parent.id_,
                                    event_manager.parent.parent.id_
                                )
                            )

                        # Get the latest buffer:
                        _buffer = event_manager.buffer
                    else:
                        # Discard/queue the latest buffer when incomplete
                        self._logger.debug(
                            'Acquired buffer is complete: {0}'.format(
                                event_manager.buffer.is_complete()
                            )
                        )
                        # Queue the incomplete buffer; we have nothing to do
                        # with it:
                        data_stream = event_manager.buffer.parent
                        data_stream.queue_buffer(event_manager.buffer)
```

**Comment by kazunarikudo** [comment]
Hi, thank you for the report. Okay, I will look at the code and let you know the fixed version is ready. /Kazunari.

**Comment by kazunarikudo** [comment]
@timonehr Hi, sorry for having kept you waiting. I have just committed the suggested change to the master branch. Please feel free to close if it resolves the issue. Thank you, Kazunari.
