### ISSUE TITLE
Using port to write to a register

### ISSUE THREAD

**Issue by mrevah** [genicam/harvesters#215]
**Describe the issue**
I have a custom register in my camera at address 0x00080104, but it's not defined as a node in the XML file.
I am trying to write a value to that register using the `Port` function.
I use `ia.remote_device.port` but it throws an exception:
`{AttributeError}'NoneType' object has no attribute 'remote_port'`

**To Reproduce**
Write to a register without using it's node reference .

**Expected behavior**
Write a value to a specific register.

**Desktop**
OS: Windows
Python: 3.7
Harvester: 1.2.8
GenTL Producer: Matrix-Vision

**Comment by kazunarikudo** [comment]
Hi, thank you for the report. Could you show me the full message that you get when the exception is raised, please? /Kazunari.

**Comment by mrevah** [comment]
Hi Kazunari, I will post a screenshot, I think it's the best illustration of the issue.

![h_test](https://user-images.githubusercontent.com/43699073/102474117-ec464b80-4060-11eb-8ce9-f479bf061c89.jpg)
 
I have to note that everything works perfectly (acquisition, writing to and reading from nodes).
Thank you.

**Comment by kazunarikudo** [comment]
Hi, I have just fixed the issue and have committed the change to the master branch. I would appreciate it if you could make a try with that. /Kazunari.

**Comment by mrevah** [comment]
Hi Kazunari,
I implemented the changes you have committed, and I'm glad to say that it works.
I'm able to read and write memory blocks using the port function.
Thank you!

**Comment by kazunarikudo** [comment]
Hi, I am glad to hear that it worked for you. I hope you enjoy working on your project with Harvester. Cheers, Kazunari.

**Comment by denarolt** [comment]
Hi Kazunari,
i had the same issue here and the change in master worked for me as well for the port write function. I'm pretty sure i'm just missing something, but how would i accomplish the read of a port thats not defined in the XML?
thanks,
lee

**Comment by kazunarikudo** [comment]
@denarolt Hi Lee, I am sorry having kept you waiting so long, I had overlooked your message. You can read/write register space as follows:
```
        # instantiate an acquirer:
        ia = self.harvester.create_image_acquirer(0)

        #
        address = 0x104
        access_size = 4

        # read a piece of data through the remote device port:
        data_size, data_returned = ia.remote_device.port.read(
            address, access_size)
        self.assertEqual(data_size, access_size)
        self.assertEqual(data_returned, b'\x00\x02\x00\x00')

        # overwrite the data through the remote device port:
        data_to_write = b'\x00\x01\x00\x00'
        ia.remote_device.port.write(address, data_to_write)

        # then read it back to make sure that it worked:
        data_size, data_returned = ia.remote_device.port.read(
            address, access_size)
        self.assertEqual(data_size, access_size)
        self.assertEqual(data_returned, data_to_write)
```
Regards, Kazunari
