### ISSUE TITLE
Getting empty list after executing h.device_info_list

### ISSUE THREAD

**Issue by lfvm0001** [genicam/harvesters#216]
**Describe the bug**
Hi, Im using a JAI camera (CM140 GE UV), and I want to obtain the images by python using harvesters, I've followed the installation instructions, however when I add the cti file and then do a "h.device_info_list" I got an empty result: "[ ]" 
I've tried loading the cti from the JAI SDK  folder and the one from Matrix Vision without any success.  

**To Reproduce**
What I have done:
1. Install the GenTL producer ("mvGenTL_Acquire_x86_64_2.29.msi") (With the programs installed, Im able to see the camera, its properties and the images )
2. Install Harvester Core (pip install harvesters)
3. Then I create a python script:

```
from harvesters.core import Harvester

h = Harvester()
h.add_file('C:\\Program Files\\JAI\\SDK\\bin\\JaiCLTL.cti')
h.add_file('C:\\Program Files\\JAI\\SDK\\bin\\JaiGevTL.cti')
h.add_file('C:\\Program Files\\JAI\\SDK\\bin\\JaiUSB3vTL.cti')
h.add_file('C:\\Program Files\\JAI\\SDK\\bin\\TLProxy.cti')
h.add_file('C:\\Program Files\\MATRIX VISION\\mvIMPACT Acquire\\bin\\x64\\mvGenTLProducer.cti')

h.update
print(h.device_info_list)
```
4. When I execute the program, with the camera conected i get: [ ] 

Is there something I am doing wrong? this is new for me. Really apreciate any help :)

**Expected behavior**
The list of the devices I can control, in this case the JAI camera.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Python: 3.8 (64 bits)
 - Harvester: 1.2.8
 - GenTL Producer: JAI
 - Camera: CM140 GE UV (JAI)

**Comment by kazunarikudo** [comment]
Hi,
```
h.update
print(h.device_info_list)
```
Is this the code you execute? Is that a typo? I see it's missing `()` after `update`. Executing `h.update` and `h.update()` is completely different. Please let me know if you executed `h.update()` anyway.
/Kazunari.

**Comment by lfvm0001** [comment]
Yes i was missing the "( )" 
Now i get the camera in the device list. 

GenTL producer does not implement IFGetParentTL
GenTL producer does not implement DevGetParentIF
GenTL producer does not implement DSGetParentDev
GenTL producer does not implement DSGetNumBufferParts
GenTL producer does not implement DSGetBufferPartInfo
['C:\\Program Files\\JAI\\SDK\\bin\\JaiGevTL.cti']
[(id_='MAC->00-0C-DF-02-F2-76::JAI Ltd., Japan::CM-140GE-UV', vendor='JAI Ltd., Japan', model='CM-140GE-UV', tl_type='GEV', user_defined_name=None, serial_number='S141940', version=None), (id_='MAC->00-0C-DF-02-F2-76::JAI Ltd., Japan::CM-140GE-UV', vendor='JAI Ltd., Japan', model='CM-140GE-UV', tl_type='GEV', user_defined_name=None, serial_number='S141940', version=None)]


Thanks for your help and sorry for the dumb question

**Comment by kazunarikudo** [comment]
That's not dumb at all. You are welcome and good to hear that it worked for you. I hope you enjoy your work with Harvesters. /Kazunari.
