### ISSUE TITLE
IoException during long-run camera capture

### ISSUE THREAD

**Issue by JackOsprey** [genicam/harvesters#217]
**Describe the bug**
Harvesters/the GenTL Producer raises a communication error (`GC_ERR_IO -1010`) after several hours of continuous capture in a multi-camera hardware-triggered 10-Gigabit network configuration. 

Immediately after this error is captured, I poll for the device's status & the GenTL Producer lists the individual camera's state as `DEVICE_ACCESS_STATUS_OPEN_READONLY`. I am then unable to stop capture, access device properties, or close the device. The only method to recover the device is to stop & restart my code.
Notably, once the communication error has occurred & the GenTL Producer considers the device as read-only, I am able to run a separate Python script with Harvesters & connect to the same camera device.

This behaviour happens consistently with long-run hardware-triggered continuous capture with the failure occurring anytime after ~12hrs. The camera that raises the exception is random each time. RAM & CPU usage is stable through-out. Varying packet delay values are configured across the camera devices. MTU size is 9000. The PC machine's Rx & Tx buffers for the camera's network interface are set to their max (8184). The PC machine's socket buffer size is increased to ~32MB (33554432 Bytes). I've tested with a newer version of Harvesters, a newer version of Matrix Vision's GenTL Producer (both listed below), with different cameras & across different machines. 

**Error Traceback**
```
Camera 3 - exception during image handling.
Traceback (most recent call last):
  File "/home/dev/core/build/device/camera/harvester.py", line 267, in device_temp
    device_temp = self._acquirer.device.node_map.DeviceTemperature.value
  File "/home/dev/.venv/lib/python3.8/site-packages/genicam/genapi.py", line 2234, in _get_value
    return self._primal_get_value()
  File "/home/dev/.venv/lib/python3.8/site-packages/genicam/genapi.py", line 2147, in _primal_get_value
    return _genapi.IFloat__primal_get_value(self, Verify, IgnoreCache)
  File "/home/dev/.venv/lib/python3.8/site-packages/harvesters/_private/core/port.py", line 57, in read
    buffer = self.port.read(address, length)
  File "/home/dev/.venv/lib/python3.8/site-packages/genicam/gentl.py", line 5003, in read
    return _gentl.Port_read(self, address, buffer)
_gentl.IoException: GenTL exception: Communication error, read or write to remote device failed. (Message from the source: Could not read data from 0x10100030(4 bytes). No answer from device.
) (ID: -1010)
```

**To Reproduce**
1. Setup a 8-camera 10-gigabyte network configuration. 
2. Hardware trigger at 0.25 fps with 2 second exposure.
3. Run code similar to what's shown below.
4. Wait >12hrs for error to occur

```python
# Begin image acquisition loop
while self._capturing.is_set():
    try: 
        # Get image buffer
        with self._acquirer.fetch_buffer(timeout=timeout) as buffer:
    
            # Generate meta data from buffer
            device_timestamp = buffer.timestamp / 1e9  # device timestamp (s)
            img = buffer.payload.components[0].data
            height, width = buffer.payload.components[0].height, buffer.payload.components[0].width
            img = np.array(img.reshape(height, width))
    
            device_temp = self._acquirer.device.node_map.DeviceTemperature.value
    
            # Send image data
            output_queue.put_nowait((img, device_timestamp, device_temp))
        
        self._n_captured += 1

    except Exception as err:
        self.logger.error(f"Exception raised in Camera {self.id}'s capture thread", exc_info=True)
    finally:
        if self._acquirer.is_acquiring_images:
            if self._acquirer.device.access_status == DEVICE_ACCESS_STATUS_LIST.DEVICE_ACCESS_STATUS_OPEN_READWRITE:
                self._acquirer.stop_image_acquisition()
        self._capturing.clear()
    self.logger.debug(f"Camera ID {self.id} stopped capturing.")
```

**Expected behavior**
It is expected that this `gentl.IoException` does not occur at random during long-run camera capture.
It is expected that the GenTL Producer does not lose read/write access to cameras.

**Screenshots**
Please see error trace & code for more information.

**Desktop:**
 - OS: Ubuntu18.04
 - Python: 3.8
 - Harvester: 0.2.12 & 1.2.8
 - GenTL Producer: Matrix Vision 2.37.1 & 2.40.3
 - Camera: LucidVision

**Additional context**
Wireshark monitoring can be performed, if required to look for any specific anomalies.

**Comment by kazunarikudo** [comment]
@JackOsprey Hi, Jack. Thank you for the report. I could be wrong but Lucid Vision may have their GenTL Producer. Do you have any contact person at Lucid Vision who you can reach out? I would like to recommend you to give it try with theirs as the first shot. I can't guarantee but it's worth letting them know that this is Kazunar's suggestion for you; their CEO and the software development team leader should know me in person. Please feel free to come back here if there's no clue. Regards, Kazunari.

**Comment by kazunarikudo** [comment]
Please open this again when needed.

**Comment by hazza203** [comment]
@JackOsprey How did you get on with this? We're encountering practically the same issue and also using LucidVision cameras
