### ISSUE TITLE
Unable to install Harvesters on Jetson Nvidia Xavier AGX [ genicam package for python 3.6 ]

### ISSUE THREAD

**Issue by afridi26** [genicam/harvesters#218]
**Describe the bug**

 Pip cannot find the genicam package. I looked at this issue [genicam package for python 3.8
](https://github.com/genicam/harvesters/issues/125) but didn't help me.

Detail description:

I am trying to install harvesters on Jetson Nvidia Xavier AGX. As we all know that Nvidia AGX is closed source due to which I am not able to install anaconda or miniconda. Therefore, I setup the virtualenv and then tried to install harvesters, but there was no success. However,  (for cross verification) then I tried to install on my local PC (Ubuntu 20.04) with same python version (3.6) without virtualenv and I was able to install it . Now, I am not able to figure it whether it is not supported on the NVIDIA AGX platform or there is something else that I am missing. I am getting the same error with virtualenv or without on Nvidia AGX. Can any one nudge me in the right direction.

**To Reproduce**
1. Activate virtual environment
2. Then run the installation command ``` pip install harvesters```
3. See error
```
Collecting harvesters
  Using cached https://files.pythonhosted.org/packages/2d/12/d36f7abaef6cbbc491691877b98719e890ca412d38e7ac736158f2e6799d/harvesters-1.2.8-py3-none-any.whl
Collecting numpy (from harvesters)
Collecting genicam==1.0.0 (from harvesters)
  Could not find a version that satisfies the requirement genicam==1.0.0 (from harvesters) (from versions: )
No matching distribution found for genicam==1.0.0 (from harvesters)
```

**Expected behavior**

It should successfully install harvesters.

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Python: 3.6
 - Harvester:  1.2.8
 - GenTL Producer: Stemmer Imaging AG
 - Camera: TeleDyne  Dalsa Genie Nano C1930

**Comment by kazunarikudo** [comment]
Hi, the issue is caused by a fact that we as the GenICam committee have not ported the `genicam` package to any ARM yet as it's brought up by ticket #102. Long story short, that's my bad; I could not have enough time to push the progress forward during 2020. I hope I can work for it in 2021 and deliver it to you. Regards, Kazunari.

**Comment by afridi26** [comment]
@kazunarikudo 

That's sad to hear. Anyways thank you so much for your valuable time. I would love to see it action for arm.

Regards,
Aftab
