### ISSUE TITLE
SyntaxWarning: "is" with a literal. Did you mean "=="?

### ISSUE THREAD

**Issue by TKaluza** [genicam/harvesters#219]
Syntax check, highlighted one tiny small thing for the attached line. 
In the used context I can't see it beeing any problem!

Maybe you want to change "is" with "=="?

https://github.com/genicam/harvesters/blob/aababc87f9718d51b6e4451a50e91d821c344441/src/harvesters/core.py#L353

**Comment by kazunarikudo** [comment]
@TKaluza Hi, thank you for the information. I have fixed that. Regards, Kazunari.
