### ISSUE TITLE
start_acquisition don't work 

### ISSUE THREAD

**Issue by riccardosemprevivo** [genicam/harvesters#221]
**Describe the bug**
I try to acquire image from a Dalsa camera, using the JAI SDK GenTL.
My programm detect the same device two times and the programm end without any information during the 
start_acquisition function.

**To Reproduce**
from harvesters.core import Harvester

import numpy as np 
import cv2

h = Harvester()

h.add_file('JaiGevTL.cti')

h.update()

print("Number of connected devices = " + str(len(h.device_info_list)))

for i in range(len(h.device_info_list)):
    print(h.device_info_list[i])

ia = h.create_image_acquirer(1)

ia.remote_device.node_map.Width.value = 4112

ia.remote_device.node_map.Height.value = 2176

ia.remote_device.node_map.PixelFormat.value = 'Mono8'

ia.start_acquisition(run_in_background=False)

with ia.fetch_buffer() as buffer:
    component = buffer.payload.components[1]

    image = component.data.reshape( component.height, component.width )
    cv2.imshow('image',image)
    cv2.waitKey(2)

ia.stop_acquisition()
ia.destroy()
h.reset()

This is the console output
GenTL producer does not implement IFGetParentTL
GenTL producer does not implement DevGetParentIF
GenTL producer does not implement DSGetParentDev
GenTL producer does not implement DSGetNumBufferParts
GenTL producer does not implement DSGetBufferPartInfo
Number of connected devices = 2
(id_='MAC->00-01-0D-C3-86-11::Teledyne DALSA::Nano-C4030', vendor='Teledyne DALSA', model='Nano-C4030', tl_type='GEV', user_defined_name='S1167916', serial_number='S1167916', version=None)
(id_='MAC->00-01-0D-C3-86-11::Teledyne DALSA::Nano-C4030', vendor='Teledyne DALSA', model='Nano-C4030', tl_type='GEV', user_defined_name='S1167916', serial_number='S1167916', version=None)

**Desktop (please complete the following information):**
 - OS: Window10
 - Python: 3.8
 - Harvester: 0.4.4
 - GenTL Producer: JAI SDK GenTL
 - Camera: Teledyne dalsa c4030

**Comment by riccardosemprevivo** [comment]
> 
> 
> **Describe the bug**
> I try to acquire image from a Dalsa camera, using the JAI SDK GenTL.
> My programm detect the same device two times and the programm end without any information during the
> start_acquisition function.
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> from harvesters.core import Harvester
> 
> import numpy as np
> import cv2
> 
> h = Harvester()
> 
> h.add_file('JaiGevTL.cti')
> 
> h.update()
> 
> print("Number of connected devices = " + str(len(h.device_info_list)))
> 
> for i in range(len(h.device_info_list)):
> print(h.device_info_list[i])
> 
> ia = h.create_image_acquirer(1)
> 
> ia.remote_device.node_map.Width.value = 4112
> 
> ia.remote_device.node_map.Height.value = 2176
> 
> ia.remote_device.node_map.PixelFormat.value = 'Mono8'
> 
> ia.start_acquisition(run_in_background=False)
> 
> with ia.fetch_buffer() as buffer:
> component = buffer.payload.components[1]
> 
> ```
> image = component.data.reshape( component.height, component.width )
> cv2.imshow('image',image)
> cv2.waitKey(2)
> ```
> 
> ia.stop_acquisition()
> ia.destroy()
> h.reset()
> 
> This is the console output
> GenTL producer does not implement IFGetParentTL
> GenTL producer does not implement DevGetParentIF
> GenTL producer does not implement DSGetParentDev
> GenTL producer does not implement DSGetNumBufferParts
> GenTL producer does not implement DSGetBufferPartInfo
> Number of connected devices = 2
> (id_='MAC->00-01-0D-C3-86-11::Teledyne DALSA::Nano-C4030', vendor='Teledyne DALSA', model='Nano-C4030', tl_type='GEV', user_defined_name='S1167916', serial_number='S1167916', version=None)
> (id_='MAC->00-01-0D-C3-86-11::Teledyne DALSA::Nano-C4030', vendor='Teledyne DALSA', model='Nano-C4030', tl_type='GEV', user_defined_name='S1167916', serial_number='S1167916', version=None)
> 
> **Desktop (please complete the following information):**
> 
>     * OS: Window10
> 
>     * Python: 3.8
> 
>     * Harvester: 1.2.8
> 
>     * GenTL Producer: JAI SDK GenTL
> 
>     * Camera: Teledyne dalsa c4030

**Comment by divyasaxenaa** [comment]
Did you get any work around? I am facing the same issue.

**Comment by kazunarikudo** [comment]
Hi, it is hard to list up possible causes where Harvester fails to acquire such a trivial pixel format. I would recommend all of you to try another GenTL Producer. As far as I know, JAI has already stopped maintaining their GenTL Producer. Regards, Kazunari.

**Comment by divyasaxenaa** [comment]
I am getting very weird error message while acquiring the image
I am getting PixelFormat values as "('Mono8', 'Mono10', 'Mono10Packed', 'Mono12', 'Mono12Packed')". So I don't think this is the case for me. After ia.start_image_acquisition(), I am getting "Process finished with exit code -1073741819 (0xC0000005)".

Can you suggest any other GenTL Producer that I can try?

 OS: Window10

* Python: 3.6

* Harvester: 1.2.8

* GenTL Producer: JAI SDK GenTL

* Camera: AD 080 GE(JAI)
