### ISSUE TITLE
Calling non standard functions of a GenTL producer

### ISSUE THREAD

**Issue by maikelmeyers** [genicam/harvesters#224]
**Is your feature request related to a problem? Please describe.**
We want to connect to our GigEVision Sensor via harvester in combination with the MATRIX VISION mvIMPACT Acquire GenTL Producer.
Unfortunately harvester does not find the sensor because only a Directed Broadcast is used for Device Discovery but our sensor only supports Limited Broadcast (255.255.255.255). We wondered why the mv-Tools can find the sensor, but harvester not, even though the same GenTL Producer is used. We found out that the mvGenTLProducer.cti has some additional non-standard functions to setup the Broadcast method. These are used by the mv-Tools.

**Describe the solution you'd like**
Is there any way to make calls to these vendor specific functions of a GenTL producer within a python script that uses harvester?

**Comment by kazunarikudo** [comment]
@maikelmeyers I am afraid but Harvester can't access such vendor-specific functions. Regards, Kazunari.
