### ISSUE TITLE
Error while try to use the ExposureTime Chunk

### ISSUE THREAD

**Issue by Schwoerer** [genicam/harvesters#225]
**Describe the bug**
I thry to grep the Exposuretime from the Chunk Data of my Basler Came.
But I allways get the same Error if I  set the ChunkMode to active.
If someone could help me it would really be greate. 

**To Reproduce**
1. run the following code:
```
import os
from harvesters.core import Harvester

os.environ['HARVESTERS_XML_FILE_DIR'] = 'C:\\...\\Version_2.11xml_cti'
h = Harvester()
if not h.files:
    h.add_file('C:\\...\\ProducerGEV.cti')
h.update()

ia = h.create_image_acquirer(0)
ia.remote_device.node_map.ChunkModeActive.value = True
ia.remote_device.node_map.ChunkSelector.value = 'ExposureTime'
ia.remote_device.node_map.ChunkEnable.value = True

ia.start_acquisition(run_in_background=True)
with ia.fetch_buffer() as buffer:
    component = buffer.payload.components[0]
    pic = component.data.reshape(component.height, component.width).astype(float))
```

2. see the following error:
```
Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2020.3\plugins\python-ce\helpers\pydev\pydevd.py", line 1477, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2020.3\plugins\python-ce\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:/.../AppData/Roaming/JetBrains/PyCharmCE2020.3/scratches/scratch_12.py", line 34, in <module>
    with ia.fetch_buffer() as buffer:
  File "C:\...\site-packages\harvesters\core.py", line 2722, in fetch_buffer
    _buffer = Buffer(
  File "C:\...\site-packages\harvesters\core.py", line 1126, in __init__
    self._payload = self._build_payload(
  File "C:\...\site-packages\harvesters\core.py", line 1261, in _build_payload
    payload = PayloadImage(
  File "C:\...\site-packages\harvesters\core.py", line 1437, in __init__
    self._build_component(
  File "C:\...\lib\site-packages\harvesters\core.py", line 1357, in _build_component
    symbolic = dict_by_ints[data_format]
KeyError: 0
```

**Expected behavior**
I would ecpect, that I could grep the Chunk Data

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Python: 3.8
 - Harvester: 1.2.8
 - Camera: Basler Ace Gig E

**Comment by kazunarikudo** [comment]
@Schwoerer Hi, just a quick question: Which pixel format are you applying to the device? Regards, Kazunari.

**Comment by Schwoerer** [comment]
Oh, sorry, 
I forgot to copy the line. I use Mono8.

`ia.remote_device.node_map.PixelFormat.value = 'Mono8'`

**Comment by monzelr** [comment]
> **Describe the bug** I thry to grep the Exposuretime from the Chunk Data of my Basler Came. But I allways get the same Error if I set the ChunkMode to active. If someone could help me it would really be greate.
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. run the following code:
> 
> ```
> import os
> from harvesters.core import Harvester
> 
> os.environ['HARVESTERS_XML_FILE_DIR'] = 'C:\\...\\Version_2.11xml_cti'
> h = Harvester()
> if not h.files:
>     h.add_file('C:\\...\\ProducerGEV.cti')
> h.update()
> 
> ia = h.create_image_acquirer(0)
> ia.remote_device.node_map.ChunkModeActive.value = True
> ia.remote_device.node_map.ChunkSelector.value = 'ExposureTime'
> ia.remote_device.node_map.ChunkEnable.value = True
> 
> ia.start_acquisition(run_in_background=True)
> with ia.fetch_buffer() as buffer:
>     component = buffer.payload.components[0]
>     pic = component.data.reshape(component.height, component.width).astype(float))
> ```
> 
> 2. see the following error:
> 
> ```
> Traceback (most recent call last):
>   File "C:\Program Files\JetBrains\PyCharm Community Edition 2020.3\plugins\python-ce\helpers\pydev\pydevd.py", line 1477, in _exec
>     pydev_imports.execfile(file, globals, locals)  # execute the script
>   File "C:\Program Files\JetBrains\PyCharm Community Edition 2020.3\plugins\python-ce\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
>     exec(compile(contents+"\n", file, 'exec'), glob, loc)
>   File "C:/.../AppData/Roaming/JetBrains/PyCharmCE2020.3/scratches/scratch_12.py", line 34, in <module>
>     with ia.fetch_buffer() as buffer:
>   File "C:\...\site-packages\harvesters\core.py", line 2722, in fetch_buffer
>     _buffer = Buffer(
>   File "C:\...\site-packages\harvesters\core.py", line 1126, in __init__
>     self._payload = self._build_payload(
>   File "C:\...\site-packages\harvesters\core.py", line 1261, in _build_payload
>     payload = PayloadImage(
>   File "C:\...\site-packages\harvesters\core.py", line 1437, in __init__
>     self._build_component(
>   File "C:\...\lib\site-packages\harvesters\core.py", line 1357, in _build_component
>     symbolic = dict_by_ints[data_format]
> KeyError: 0
> ```
> 
> **Expected behavior** I would ecpect, that I could grep the Chunk Data
> 
> **Desktop (please complete the following information):**
> 
> * OS: Windows 10
> * Python: 3.8
> * Harvester: 1.2.8
> * Camera: Basler Ace Gig E


Hi @Schwoerer ,
could you please try the following code? (currently I have no camera here) If you want to enable the Chunk mode you need to add "Image" to the chunk data! Thus the acquired image is also transferred.


```python
import os
from harvesters.core import Harvester

os.environ['HARVESTERS_XML_FILE_DIR'] = 'C:\\...\\Version_2.11xml_cti'
h = Harvester()
if not h.files:
    h.add_file('C:\\...\\ProducerGEV.cti')
h.update()

ia = h.create_image_acquirer(0)
ia.remote_device.node_map.ChunkModeActive.value = True
ia.remote_device.node_map.ChunkSelector.value = 'Image'
ia.remote_device.node_map.ChunkEnable.value = True
ia.remote_device.node_map.ChunkSelector.value = 'ExposureTime'
ia.remote_device.node_map.ChunkEnable.value = True

ia.start_acquisition(run_in_background=True)
with ia.fetch_buffer() as buffer:
    component = buffer.payload.components[0]
    pic = component.data.reshape(component.height, component.width).astype(float))
```

The problem was also mine a year ago, see here: #176
