### ISSUE TITLE
Cant connect to Teledyne Dalsa Calibir

### ISSUE THREAD

**Issue by Shorlaks** [genicam/harvesters#226]
Hello

**Describe the bug**
I'm trying to connect to a **Teledyne DALSA-Calibir GXM640** and this is the error I get.
```
2021-03-17 13:40:42,702 :: harvesters.core :: ERROR :: GenTL exception: Address is out of range or invalid. (Message from the source: Device returned GEV_STATUS_INVALID_ADDRESS while trying to read 512 bytes from address 0x600) (ID: -1015)
Traceback (most recent call last):
  File "C:\Users\spike\anaconda3\lib\site-packages\harvesters\core.py", line 1696, in __init__
    xml_dir_to_store=self._xml_dir, file_path=file_path_
  File "C:\Users\spike\anaconda3\lib\site-packages\harvesters\core.py", line 2207, in _get_port_connected_node_map
    port=port, file_path_to_load=file_path, logger=logger, xml_dir_to_store=xml_dir_to_store
  File "C:\Users\spike\anaconda3\lib\site-packages\harvesters\core.py", line 2262, in _retrieve_file_path
    if len(port.url_info_list) > 0:
  File "C:\Users\spike\anaconda3\lib\site-packages\genicam\gentl.py", line 5183, in _get_url_info_list
    return _gentl.Port__get_url_info_list(self)
_gentl.InvalidAddressException: GenTL exception: Address is out of range or invalid. (Message from the source: Device returned GEV_STATUS_INVALID_ADDRESS while trying to read 512 bytes from address 0x600) (ID: -1015)
```

**Desktop (please complete the following information):**
 - OS: Win10
 - Python: 3.7
 - Harvester: 1.2.8
 - GenTL Producer: MatrixVision
 - Camera: Teledyne Dalsa Calibir

Is this problem occurs on my side? or maybe the camera implements some protocols differently?
Have you ever stumbled across anything like this? and what can I do?
Thank you,
Shorlaks

**Comment by kazunarikudo** [comment]
@Shorlaks Could you try another GenTL Producer or other versions if possible? It sounds like a trivial defect but there is nothing Harvester can commit. Regards, Kazunari.

**Comment by Shorlaks** [comment]
Hi @kazunarikudo.
I tried JAI SDK but it doesn't have a CTI file.
I also tried Baumer GAPI SDK (Baumer Optronic) and Common Vision Blox (STEMMER IMAGING).
Both of them throw these errors:
```
2021-03-22 13:04:11,419 :: harvesters.core :: ERROR :: Error while parsing XML stream at line 412 and column 39 : 'not well-formed (invalid token)' : RuntimeException thrown (file 'XmlParser.cpp', line 1720)
Traceback (most recent call last):
  File "C:\Users\spike\anaconda3\lib\site-packages\harvesters\core.py", line 2221, in _get_port_connected_node_map
    node_map.load_xml_from_zip_file(file_path)
  File "C:\Users\spike\anaconda3\lib\site-packages\genicam\genapi.py", line 2010, in load_xml_from_zip_file
    return _genapi.NodeMap_load_xml_from_zip_file(self, ZipFileName)
_genapi.RuntimeException: File open failed in ParseXmlFile. Filename = 'C:\Users\spike\AppData\Local\Temp\20210322130411_87w_zfbj\teledynedalsa_calibir_0_2_53330331.xml' : RuntimeException thrown (file 'XmlParser.cpp', line 131)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\spike\anaconda3\lib\site-packages\harvesters\core.py", line 2224, in _get_port_connected_node_map
    node_map.load_xml_from_file(file_path)
  File "C:\Users\spike\anaconda3\lib\site-packages\genicam\genapi.py", line 2004, in load_xml_from_file
    return _genapi.NodeMap_load_xml_from_file(self, FileName)
_genapi.RuntimeException: Error while parsing XML stream at line 412 and column 39 : 'not well-formed (invalid token)' : RuntimeException thrown (file 'XmlParser.cpp', line 1720)
```
And this is the XML file referenced in the error: (zipped so I can upload it)

[teledynedalsa_calibir_0_2_53330331.zip](https://github.com/genicam/harvesters/files/6180764/teledynedalsa_calibir_0_2_53330331.zip)

Thank you,
Shorlaks

**Comment by kazunarikudo** [comment]
@Shorlaks Hi, as far as I checked the file, the XML file parser is arguing a piece of data that seems to be represent an apostrophe; I can confirm about 6 places in the file. There seems to be an issue in the encoding handling. One more thing I can notice is there are some apostrophes that have been correctly represented. Let me guess a bit more... (By the way, how did you get the XML file above?) Regards, Kazunari.

**Comment by Shorlaks** [comment]
@kazunarikudo Hi.
Yes, you are absolutely right.
Harvester works 100%, the problem is genicam's xmlParser dll.
As far as I can tell, xml's from Dalsa have unusual characters which break most xmlParsers.
The characters from the xml I uploaded are: `’`, `°` and `µ`.

To your question, Harvester =]
When building the `remote_device` node map, Harvester retrieves the xml from the camera and saves it locally, I just followed the debug to get the path.
This is also how I managed to fix it, right after Harvester retrieves the xml (`binary_data` (line 2372)) I iterate over the binary data and remove the occurrences of the characters I mentioned above.
Ill post the code that fixed it for me on Sunday (code is at work).

**Comment by kazunarikudo** [comment]
> the problem is genicam's xmlParser dll.

To be honest, I do not think so. The XML parse is just working on its job. Rather, I am afraid of a case where Harvester is unintentionally altering the file data before it's passed to the parser. However, if the XML file is provided as a Zip file then Harvester should directly pass the file to the parser so there should never be a chance to alter particular characters. Hm, there should be something wrong...

**Comment by binflo13** [comment]
> 
> 
> @kazunarikudo Hi.
> Yes, you are absolutely right.
> Harvester works 100%, the problem is genicam's xmlParser dll.
> As far as I can tell, xml's from Dalsa have unusual characters which break most xmlParsers.
> The characters from the xml I uploaded are: `’`, `°` and `µ`.
> 
> To your question, Harvester =]
> When building the `remote_device` node map, Harvester retrieves the xml from the camera and saves it locally, I just followed the debug to get the path.
> This is also how I managed to fix it, right after Harvester retrieves the xml (`binary_data` (line 2372)) I iterate over the binary data and remove the occurrences of the characters I mentioned above.
> I know it's a weak solution, but other solutions are recompiling genicam or burning a new xml into the camera (couldn't find a way to do it).
> Ill post the code that fixed it for me on Sunday (code is at work).

Hi Shorlaks,

I'm facing the same problem with a Teledyne Dalsa Linea 2K camera. Could you post the code you used in order remove this unusual characters?

**Comment by Shorlaks** [comment]
in Harvesters.core, add these lines to `_save_file` function before the return statement
```
if file_name[:13] == 'teledynedalsa':
        with open(file_path, 'r') as file:
        	data = file.read()
        data = data.replace('’', '')
        data = data.replace('°', '')
        data = data.replace('µ', 'micro')
        with open(file_path, 'w') as file
        	file.write(data)
```
Basically, the xml file is saved locally and then loaded into Harvester.
This code alters the xml before it gets loaded into Harvester.

**Comment by Shorlaks** [comment]
@kazunarikudo Hi

> I am afraid of a case where Harvester is unintentionally altering the file data before it's passed to the parser

I managed to extract the XML from the camera without using Harvester, and the XML is exactly as the one Harvester saves locally.
I think it means that Harvester is not altering the file data.

**Comment by binflo13** [comment]
> 
> 
> @binflo13 Hi
> in Harvesters.core, add these lines to `_save_file` function before the return statement
> 
> ```
> if file_name[:13] == 'teledynedalsa':
>         with open(file_path, 'r') as file:
>         	data = file.read()
>         data = data.replace('’', '')
>         data = data.replace('°', '')
>         data = data.replace('µ', 'micro')
>         with open(file_path, 'w') as file
>         	file.write(data)
> ```
> 
> Basically, the xml file is saved locally and then loaded into Harvester.
> This code alters the xml before it gets loaded into Harvester.

Hi again @Shorlaks ,

Thank you for your help, it worked! I just needed to remove also " character. The strange thing is that some months ago I tested the same camera in other PC and it worked without making any changes in the harvesters repository. If I have time, I will try to find out why.

**Comment by kazunarikudo** [comment]
@Shorlaks Thank you for the suggestion and for telling me that the extracted file is not being altered by Harvester. A piece of information that I would like to tell you is the GenApi itself accepts a Zip file, so Harvester does not pass the extracted plain text file, in general. If the file is not altered by Harvester so other libraries, including the one from its camera manufacturer, must face the same issue but I would not believe the issue is really happening... Yeah, anyway, I will make sure if I can reproduce the encoding issue from the GenApi reference implementation side. Let me keep your suggestion as the final workaround to be implemented in Harvester. Thank you again. Regards, Kazunari.

**Comment by kazunarikudo** [comment]
@Shorlaks Update: I have just confirmed that some special characters can't be handled by the GenApi reference implementation. I will circulate this topic in the committee.

**Comment by kazunarikudo** [comment]
@Shorlaks, @binflo13 Hi, probably the latest commit at ff862dea22a1eb53610417a3d8f9e2c39c680509 should fix the issue. I would highly appreciate it if you could try it out when you can. Thank you. Best regards, Kazunari.

**Comment by Shorlaks** [comment]
hi @kazunarikudo 
Sorry for taking it so long.
I've checked your commit.... It does connect to the Dalsa camera but it throws these exceptions:
```
2021-06-20 18:06:40,132 :: harvesters.core :: ERROR :: GenTL exception: Address is out of range or invalid. (Message from the source: Device returned GEV_STATUS_INVALID_ADDRESS while trying to read 512 bytes from address 0x600) (ID: -1015)
Traceback (most recent call last):
  File "C:\Users\uaer\anaconda3\envs\harv_check\lib\site-packages\harvesters\core.py", line 1705, in __init__
    file_dict=self._file_dict, do_clean_up=self._do_clean_up)
  File "C:\Users\uaer\anaconda3\envs\harv_check\lib\site-packages\harvesters\core.py", line 2217, in _get_port_connected_node_map
    file_dict=file_dict)
  File "C:\Users\uaer\anaconda3\envs\harv_check\lib\site-packages\harvesters\core.py", line 2284, in _retrieve_file_path
    if len(port.url_info_list) > 0:
  File "C:\Users\uaer\anaconda3\envs\harv_check\lib\site-packages\genicam\gentl.py", line 5183, in _get_url_info_list
    return _gentl.Port__get_url_info_list(self)
_gentl.InvalidAddressException: GenTL exception: Address is out of range or invalid. (Message from the source: Device returned GEV_STATUS_INVALID_ADDRESS while trying to read 512 bytes from address 0x600) (ID: -1015)

Process finished with exit code -1
```
I must say that before I start the acquisition, I'm using the image acquirer to get the IP from the camera.
I think some of the exceptions come from there, it only happens with the Dalsa Teledyne camera's.

Thank you
