### ISSUE TITLE
Frame Rate of a Teledyne DALSA GigE Genie Nano C4020

### ISSUE THREAD

**Issue by aspini** [genicam/harvesters#227]
**Describe the bug**
I can connect to my camera but the problem is to stream the images with the frame rate of the camera. 

**To Reproduce**
```

from harvesters.core import Harvester
from harvesters.util.pfnc import mono_location_formats, \
    rgb_formats, bgr_formats, \
    rgba_formats, bgra_formats, bayer_location_formats
import numpy as np
import cv2

scale_factor = 0.6

h = Harvester()
h.reset()
h.add_file('C:/Program Files/MATRIX VISION/mvIMPACT Acquire/bin/x64/mvGenTLProducer.cti')
h.update()
print(h.device_info_list)
print(h.device_info_list[0])

ia = h.create_image_acquirer(0)
ia.start_acquisition()
component = ia.fetch_buffer().payload.components[0]
width = component.width
height = component.height #  ia.start_acquisition()
ia.stop_acquisition()
while True:
    ia.stop_acquisition()
    ia.start_acquisition()
    component = ia.fetch_buffer().payload.components[0]

    img = cv2.resize(cv2.cvtColor(component.data.reshape(height, width, int(component.num_components_per_pixel)), cv2.COLOR_BayerRG2RGB),(int(width*scale_factor), int(height*scale_factor)),interpolation = cv2.INTER_AREA)  

    cv2.namedWindow("image", cv2.WINDOW_NORMAL)
    cv2.resizeWindow("image", img.shape[1], img.shape[0])
    cv2.imshow("image", img)
    key = cv2.waitKey(1) & 0xFF
    # ia.stop_acquisition()
    if key == ord("q"):
        ia.stop_acquisition()
        ia.destroy()
        h.reset()
        exit()

```

**Expected behavior**
The code I previously mentioned it's what I'm trying to use to stream the live acquisition of my camera. 
I expected a delay but what I see it's around 2.7 fps. 
I'm looking for an optimized version of this code to reach the highest fps of the camera.
From the image below it's possibile to see that the maximum fps without turbodrive is 9.5 fps.

**Desktop (please complete the following information):**
 - OS: Win10
 - Python: 3.8
 - Harvester: 1.2.8
 - GenTL Producer: MatrixVision
 - Camera: Teledyne DALSA GigE Genie Nano C4020
![image](https://user-images.githubusercontent.com/74358189/112295446-34928c80-8c94-11eb-86dd-6c375f89e4b1.png)

**Comment by kazunarikudo** [comment]
@aspini Hi, let me point out some points in your code. (1) It is not necessary to toggle start/stop_acquisition every time. Once you called the start_acquisition then the camera turns ready to be triggered. Once it's triggered then it will transmit an image. (2) Do you really need to display every image that you acquire? If you don't, do you really need to convert the pixel format every image? At least these issues may drag the acquisition rate that you get. Regards, Kazunari.

**Comment by aspini** [comment]
@kazunarikudo Thanks for your answer. 

1.  Yes, of course but wihout start/stop my python code crashes after 8 or 16 frame depending on the operation in the middle of while loop. Probably  it's due to cv2.imshow(). Therefore, i used it to display as many frame as possibile.
2. It is not mandatory but sometimes it could be necessary.

If I have a problem with harvester_GUI should I open another issue?
Thanks, Andrea.

**Comment by kazunarikudo** [comment]
> Probably it's due to cv2.imshow()
I would not think so. You are not queuing any buffers back to the image acquirer. If you do not queue a buffer back then there will never be a buffer where the image acquirer can fill out an image.
