### ISSUE TITLE
genapi.RuntimeException: Invalid layout of buffer attached to chunk parser!

### ISSUE THREAD

**Issue by minewarriorsSchool** [genicam/harvesters#230]
**Describe the Bug**
Hi there! I am busy with a machine vision project annd one of the steps is that the code is competiable with different kinds of cameras. I already tested the code on my OMRON SEMTECH cameras, but wanted to try it on a different kind of GigE vision camera now. That camera is an Allied Vision camera. However, when I try to run my code it now gives a runtimeexception when trying to grab the buffer from the allied vision camera.

**To Reproduce**
1. Use the Matrix vision CTI, 1 omron semtech camera and one allied vision camera
2. activate the ia of the ALLIED VISION camera and fetch the buffer.
![image](https://user-images.githubusercontent.com/41070384/113302783-b0c64900-9300-11eb-85ac-768edf8cf084.png)

**Expected Behavior**
I would expact it to just fetch the buffer, but I can not seem to find out what the issue is. #210 seems to have the same issue that could had been fixed by editing the GevSCPSPacketSize to 1500, but I have no clue how to do this being honest and can't seem to figure it out.

or to turn ChunkModeActive off, but same story there.

**Screenshots**
```
    def createImage(self):
        # Standard harvester 1D buffer creation
        self.activate_ia()
        with self.image_acquirer.fetch_buffer() as buffer:    #<--------- Throws exception
            self.buffer = buffer
            self.imageA = self.Reshape_1D_Array()
            self._image = self.imageA.copy()
            self._image = cv.cvtColor(self.imageA, cv.COLOR_BayerRG2RGB)
        self.deactivate_ia()
```

**Configuration**

 - OS: [Windows 10]
 - Python: [3.7]
 - Harvester: [1.2.8.post0.dev17]
 - GenTL Producer: [Matrix Vision]
 - Camera: [Allied Vision]

**Actions You Have Taken** 
- [X] I've read the [Harvester FAQ page](https://github.com/genicam/harvesters/wiki/FAQ).
- [X] if I turn of chuckmode the assertion of the image fails:
![image](https://user-images.githubusercontent.com/41070384/113306488-7068ca00-9304-11eb-8a8f-9c8d7cf2f65f.png)
Same counts if I just want to return a default image that is not calibrated
![image](https://user-images.githubusercontent.com/41070384/113306793-c0e02780-9304-11eb-9caf-3c48a8942b07.png)

**Comment by kazunarikudo** [comment]
@minewarriorsSchool Hi, if my memory is correct someone reported a similar issue before. Is the phenomenon observed in every image? Best regards, Kazunari.
