### ISSUE TITLE
Installing mvIMPACT

### ISSUE THREAD

**Issue by jmdelahanty** [genicam/harvesters#232]
Hello fellow Harvesters!

I'm trying to follow along with the installation process for using Harvesters and am embarrassingly stuck at the the mvIMPACT step. I've downloaded the mvIMPACT_AcquireMergeModules zip folder, but I'm not sure where to extract them to. Should I place them in my Anaconda environment dedicated to using Harvesters?

I apologize for the simple question, but any help would be greatly appreciated.

**Comment by kazunarikudo** [comment]
@jmdelahanty Hi, I do not know which OS you are running but you need to grab mvGenTL_Acquire-*.*. These packages have an installer or an installer script. Once the package is installed there you will find a CTI file and that is the file you need to load on the Harvester object. Keep in mind that a CTI file is a DLL / a shared object so please leave them where they were. If you move them then they would fail to work. Good luck! Regards, Kazunari.

**Comment by barriebarry** [comment]
Excellent timing as I too just got stuck on this point of install.  The instructions are clearly calling for mvIMPACT... but should be changed to mvGenTL...   I was guessing this would be the needed file since it's the only one with the installer extension (msi).

Related to this step, the instructions specify version 2.29.0 and I inadvertently installed 2.29.1 and I would hope the difference is minor.  However, the latest version is at 2.42.0 so would you recommend sticking with 2.29.x?  Or will it likely be safer/better to use the latest version?

**Comment by kazunarikudo** [comment]
@barriebarry Hi, they have just changed the package name for some business reasons. I will revise the information but please note that it is not possible to make everything up to date because I’m running this project on a hobby basis. Concerning the version number, I’d not mind go with the latest version as long as I know who MATRIX VISION are. Regards, Kazunari.

**Comment by jmdelahanty** [comment]
Thanks for the comments barrie and Kazunari! I think I've installed mvGenTL successfully using their installer. I'm on Windows10 by the way. I'm getting stuck on the iPython example now.

When I do the following...

```Python
Python 3.8.8 (default, Feb 24 2021, 15:54:32) [MSC v.1928 64 bit (AMD64)]
Type 'copyright', 'credits' or 'license' for more information
IPython 7.22.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: from harvesters.core import Harvester

In [2]: import numpy as np

In [3]: h = Harvester()

In [4]: h.add_file("C:/Users/jdelahanty/.conda/envs/genicam/Lib/site-packages/genicam/TLSimu.cti")

In [5]: h.update()

In [6]: h
Out[6]: <harvesters.core.Harvester at 0x1695cf83520>

In [7]: len(h.device_info_list)
Out[7]: 0
```
it looks like I'm not getting any devices added to the system. Any advice?

**Comment by barriebarry** [comment]
@jmdelahanty I'm at the same point of getting zero in response to len(h.device_info_list).  And I see you just discovered what I was about to point out that you need to down grade to Python 3.7 yet doing that did not solve the problem.  Here are instructions on how to change the version of Python using Anaconda:
https://stackoverflow.com/questions/43592879/how-to-change-python-version-in-anaconda-spyder
Also, this is sort of described in issue #125 in the closed tickets which would be useful to have this ticket pegged at the top.

**Comment by jmdelahanty** [comment]
Interesting that this also didn't solve the problem.

I'm currently trying to find the .cti file from the mvGenTL install to use the camera directly since I can't get TLSimu to work yet. 
 Unfortunately, there doesn't appear to be one from the install. Perhaps I've installed the incorrect thing accidentally?

I installed it for all users on this machine so it's been placed in a Public folder in this path:
```C:\Users\Public\Documents\MATRIX VISION\mvIMPACT Acquire\ GenICam```
And I get the following files:
```MATRIXVISION_GenTL_Interface_12_0_1``` and ```MATRIXVISION_GenTL_System_9_0_0```

There's also a Cache folder but all that's present is two bin files that I don't know what they are for/do. Is that something you're seeing as well @barriebarry ?

**Comment by kazunarikudo** [comment]
If you are trying to get it working with a U3V camera then check if you have installed the U3V driver to the target camera. This procedure will bridges between Harvester and MV’s GenTL Producer and the target U3V camera. I don’t mind if you play with TLSimu but that’s for my testing purpose. Our Wiki or Issue page should have mentioned your missing piece but I do not think there would learn much from TLSimu so I would recommend to work with your real target.

**Comment by jmdelahanty** [comment]
Okay, got it. I'll continue to try doing that.

I'm using a Teledyne DALSA Genie Nano and it's connected through ethernet using a power-over-ethernet protocol. I'm not sure if that makes it a U3V device or not, I'm pretty new to this.

The mvGigE Configure program recognizes the camera, but I just can't seem to find the .cti file. Do you think I [downloaded/installed] the wrong thing Kazunari?

I'd attach a screenshot of the camera being connected, but it doesn't look like I can attach photos here...

**Comment by kazunarikudo** [comment]
Your target is GEV camera. Okay, so have made sure you can acquire images from DALSA’s app?

**Comment by jmdelahanty** [comment]
Okay! That's great to know, thanks for teaching me.

I have! I get images through the Sapera CamExpert app. I've also successfully gotten images using MATLAB, but am hoping to use Python to control the camera alongside our work.

**Comment by kazunarikudo** [comment]
Where did you search to find out the CTI file? I guess you’ll find it in their installation folder. Of course, I’m not fully sure because I’ve not been working with their package as I didn’t know the name change.

**Comment by kazunarikudo** [comment]
In addition, there still be a case where they have hidden the CTI file for some business reasons.
Anyway, just execute a search in the installation folder, and eventually in the whole hard disk if you can’t find it in the installation folder.

**Comment by jmdelahanty** [comment]
I was looking in the wrong folder! I got the iPython example to work by looking in the correct location noted below:
```C:/Program Files/MATRIX VISION/mvIMPACT Acquire/bin/x64/mvGenTLProducer.cti"

Thank you Kazunari!

**Comment by barriebarry** [comment]
Thanks for the help and sharing the details.  I managed to make it work too.
