### ISSUE TITLE
Customize the trigger

### ISSUE THREAD

**Issue by aspini** [genicam/harvesters#233]
I need to define manually the trigger.
I saw your example:

```

n = ia.remote_device.node_map # Just to make a line shorter.
n.TriggerMode.value = "On" # Turns trigger mode on.
n.TriggerSource.value = "Hardware" # Use hardware trigger.
n.TriggerActivation.value = "RisingEdge" # Could be omitted; triggers with the rising edge of the signal.
n.TriggerSource.value = "Line1" # Use line #1 as the trigger source

```

I need to define n.TriggerMode.value, n.TriggerSource.value and n.TriggerSource.value so that the camera captures at a distance of an a pre-defined time interval.
For example, once I defined the time interval = 0.5 seconds I need the camera to acquire exactly every 0.5 seconds.
My doubts are:

can I generate this trigger solution? I didn’t find how to customize trigger variables inside core.py and geneapi.py.
If the answer of the previous point is positive and the camera is set to 4 fps, i.e. the interval between each frame is 0.25 seconds and I set the camera to acquire after 0.55 seconds (my dt is always 0.5 sec) from image_start_acquisition(), i.e. I’m between second and third frame, do I have to wait 0.2 sec to get my acquisition?
Or, once I defined the trigger mode, which in this case it’s every 0.5 sec, am I sure that I will acquire exactly in that instant?
(P.S. Can I modify the frame rate from node_map variables?

OS: Win10
Python: 3.8
Harvester: 1.2.8
GenTL Producer: MatrixVision
Camera: Teledyne DALSA GigE Genie Nano C4020

**Comment by sshsurabhi** [comment]
Hi, I also have the same issue which you have raised. I am using Baumer TXG50 camera. 

How did you resolved this issue. Can you explain please.
