### ISSUE TITLE
GenICam 32bit

### ISSUE THREAD

**Issue by Shorlaks** [genicam/harvesters#235]
Hello
Following this closed issue: https://github.com/genicam/harvesters/issues/43

> The development of the 32bit version will come after the version 3.2 release so it would be some time in 2020

well, GenICam is version 3.3 and it's 2021, I couldn't find any information on EMVA website regarding the 32 bit version.
Is it released yet?

Thank you,
Shorlaks

**Comment by kazunarikudo** [comment]
@Shorlaks Please excuse me, we are not working on it and can't give you any feasible release plan for the 32-bit version. Please excuse me. Regards, Kazunari.

**Comment by Shorlaks** [comment]
@kazunarikudo It's alright, Thank you
