### ISSUE TITLE
harvesters.core.PayloadUnknown object when running ia.fetch_buffer() with Daheng Camera

### ISSUE THREAD

**Issue by Bart-van-Ingen** [genicam/harvesters#239]
**Describe the Bug**
receiving the following error: 
```<harvesters.core.PayloadUnknown object at 0x7fa8ace1abe0>```
when running ia.fetch_buffer() as can be seen in code
All code before does seem to run.

I think that because of payload unknown i am unable to index it
```Traceback (most recent call last):
  File "/home/bart/Desktop/haverster_basic_test.py", line 15, in <module>
    print('component buffer: {0}'.format(component[0]))
IndexError: list index out of range
```

With the GUI i am able to get the camera to work. but this use an older version of harvester

**To Reproduce**
```
from harvesters.core import Harvester
import numpy as np 

h = Harvester()
h.add_file('/opt/mvIMPACT_Acquire/lib/x86_64/mvGenTLProducer.cti')
h.update()
print(h.files)
print(h.device_info_list[0])
ia = h.create_image_acquirer(serial_number='XE0200090011')
ia.start_acquisition()
buffer = ia.fetch_buffer()
print(buffer)
```

**Expected Behavior**
I dont think that it should be payload unknown, and i should be able to index it, as indicated in the example of the readme.md 

**Configuration**

 - OS: Ubuntu 20.04
 - Python: 3.85
 - Harvester: 1.3.1
 - GenTL Producer: mvIMPACT_Acquire
 - Camera: vendor='Daheng Imaging', model='MER-2000-19U3C' [(link)](https://www.vision-camera.nl/20MP-USB-Camera-Sony-IMX183-MER-2000-19U3C)
**Actions You Have Taken**
 
- [X] I've read the [Harvester FAQ page](https://github.com/genicam/harvesters/wiki/FAQ).

**Comment by kazunarikudo** [comment]
@Bart-van-Ingen Hi, thank you for the report. As far as I check the code, Harvester instantiates a `PayloadUnkonw` object only if the GenTL Producer tells it that the acquired buffer is `PAYLOAD_TYPE_UNKNOWN`. If Harvester really does not know the payload type, you will get the `None` object instead. The latest version is 1.3.1; I would appreciate it if you could check if there are some other versions that do not reproduce the phenomenon. Regards, Kazunari.

**Comment by Bart-van-Ingen** [comment]
Hi @kazunarikudo thanks for the quick response.

I have found out that the camera currently has its default set to trigger using ```ia.remote_device.node_map.TriggerSoftware.execute()```. I found this by playing around with the GUI. I greatly appreciate that you have made this useful tool.


Using this new information I have done as you asked and have tried different versions of harvesters. I have been able to get it to work up to 1.1.1. It is showing ```bayerRG8``` format. in  harvesters 1.2 I am back to ```harvesters.core.PayloadUnknown ```

In order to do this test I had to use the previous notation of harvesters to rewrite the code as followed:

```
h = Harvester()
h.add_cti_file('/opt/mvIMPACT_Acquire/lib/x86_64/mvGenTLProducer.cti')
h.update_device_info_list()
print(h.cti_files)
print(len(h.device_info_list))
print(h.device_info_list)
ia = h.create_image_acquirer(0)
ia.start_image_acquisition()
ia.remote_device.node_map.TriggerSoftware.execute()
buffer = ia.fetch_buffer()
```

**Comment by kazunarikudo** [comment]
@Bart-van-Ingen Hi, thank you for your reply. May I ask you a question? How did you get this string, `bayerRG8`? I feel it is a bit strange because the word begins with a lowercase letter. Is that just a typo?

**Comment by Bart-van-Ingen** [comment]
Hi! sorry that is a typo, it is supposed to be capital! 

so ```BayerRG8```

**Comment by kazunarikudo** [comment]
Thank you. I just guessed a case where Harvester found the format invalid because Harvester tries to identify the pixel format in a case sensitive way.

**Comment by kazunarikudo** [comment]
This is just for your information, the payload type is not the pixel format! They are completely different information.

**Comment by Bart-van-Ingen** [comment]
so if the payload type is unknown, does that mean that I am still able to retrieve the sensor data in terms of pixel data?

**Comment by Bart-van-Ingen** [comment]
At the moment I do not have another camera to work with. I also understand that maintaining unofficial specification is not a good idea.

I am having difficult understand what is happening, is the problem with the camera or with the genTL library ?
Because I can try a different library.

**Comment by kazunarikudo** [comment]
The information source of payload type is in the streaming data that the camera transmits. And then, a GenTL producer read out the information attaching it to the corresponding buffer and tells Harvester / a GenTL consumer when it inquires the information. Yes, if you get the same result with another GenTL Producer then you should be able to conclude the camera is not providing the right information.

**Comment by Bart-van-Ingen** [comment]
right that makes sense, i will close the issue then.
