### ISSUE TITLE
Fix stop_acquisition() when camera is disconnected

### ISSUE THREAD

**Issue by tobiasf88** [genicam/harvesters#246]
**Describe the Bug**
When I initialize the camera and start an acquisition, all is fine. When i physically remove the camera and reconnected it, i can't reinitialize the camera. Reset doesn't work as expected. I have to restart python. 

The Exeption when i wan't to destroy the image_acquirer:
```
AccessDeniedException : 
GenTL exception: Requested operation is not allowed. (Message from the source: No write access to device 
BVS CA-GX0-0124AC (current access DEVICE ACCESS STATUS_NOACCESS)) 
(ID: -1005) 
```
Ok, i unterstand. But the Probem ist, that this exeptions is not catched and the method return. 

when i now `h.resest` then following Exeption returned:

```
BusyException : GenTL exception: Operation cannot be performed. Responsible module is  busy. (Message from the source: A queued buffer can't be revoked) (ID: -1022)
```
When i now setup harvester again, my camera would not be found anymore (when i reconnect the camera). 

**To Reproduce**
```
def init_harvester():
    h = harvesters.core.Harvester(logger=logging)
    h.add_file('C:\\Program Files\\MATRIX VISION\\mvIMPACT Acquire\\bin\\x64\\mvGenTLProducer.cti')
    h.update()
    return h

h = init_harvester()

print(h.device_info_list)
ia = h.create_image_acquirer(0)
ia.start_acquisition()

```

NOW disconnect the camera

```
ia.destroy() # --> AccessDeniedException 
h.reset() # --> BusyException 
```

NOW Connect the camera.

```
h = init_harvester()
h.update()
print(h.device_info_list)
```
The Camera won't be recognized anymore.

**FIXING**

I believe it can be fixed with a try/expect in the stop_acquisition()

https://github.com/genicam/harvesters/blob/20798d159b808fa760197671649349b0a243c0f2/src/harvesters/core.py#L2952

I fixed it with this code in my implementation:

```
def fix_stop_acquisition(acquirer):
    try: 
        acquirer.stop_acquisition()
        print("image acquisition is stopped.")
    except Exception as e:
        print(e)

# FIX: this part from stop_acquisition is not executed during an Expetion in the upper part of the Method
    for data_stream in acquirer._data_streams:
        try:
            data_stream.stop_acquisition(
                 ACQ_STOP_FLAGS_LIST.ACQ_STOP_FLAGS_KILL
            )
        except GenericException as e:
            print(e)
        acquirer._flush_buffers(data_stream)
```

**Configuration**

 - OS: [Windows10]
 - Python: [3.8.10]
 - Harvester: [1.3.1]
 - GenTL Producer: [e.g. Comapny ABC]
 - Camera: [e.g. Company DEF]

 
- [X] I've read the [Harvester FAQ page](https://github.com/genicam/harvesters/wiki/FAQ).

**Comment by kazunarikudo** [comment]
@tobiasf88 Hi Tobias, thank you for the valuable report. I will fix that. Thanks, Kazunari.
