### ISSUE TITLE
_gentl.AccessDeniedException when trying to create image acquirer for FLIR GigE camera

### ISSUE THREAD

**Issue by ilanbiala** [genicam/harvesters#247]
I'm using the FLIR Spinnaker SDK's provided GenTL producer for a FLIR GigE camera. I'm able to see the device info list containing my GigE camera, but when I try to create an image acquirer I get the following error:

```
>>> h.create_image_acquirer(0)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ibiala/python/lib/python3.8/site-packages/harvesters/core.py", line 3325, in create_image_acquirer
    device.open(_privilege)
  File "/home/ibiala/python/lib/python3.8/site-packages/genicam/gentl.py", line 3189, in open
    return _gentl.Device_open(self, accessFlags)
_gentl.AccessDeniedException: GenTL exception: Requested operation is not allowed. (Message from the source: Error opening device list) (ID: -1005)
```

**To Reproduce**
1. Install FLIR Spinnaker SDK, including GenTL producer library
2. Install Harvesters on Python3.8
3. Run the following commands:
```
>>> from harvesters.core import Harvester
>>> h = Harvester()
>>> h.add_file("/opt/spinnaker/lib/flir-gentl/FLIR_GenTL.cti")
>>> h.update()
>>> len(h.device_info_list)
1
>>> h.create_image_acquirer(0)
```

**Expected Behavior**
The image acquirer is created successfully.

**Configuration**

 - OS: Ubuntu 20.04
 - Python: 3.8
 - Harvester: 1.3.1
 - GenTL Producer: FLIR
 - Camera: FLIR GigE

**Actions You Have Taken**
 
- [X] I've read the [Harvester FAQ page](https://github.com/genicam/harvesters/wiki/FAQ).

**Comment by kazunarikudo** [comment]
@ilanbiala Hi. Here's just one thing I would like to ask you to double-check. Are you an app running in the background while you are trying to run the script above? If another app has already acquired the control privilege of the device, the scrip will fail to open the device. Regards, Kazunari.

**Comment by ilanbiala** [comment]
I was not running an app in the background, but I did notice that the camera seemed to be in an errored state in general, so I tried power cycling it and just getting back to a fresh state and I haven't had issues since. Probably something I did initially that was not ideal.
