### ISSUE TITLE
Communication error has occurred (ID: -1010)

### ISSUE THREAD

**Issue by Schwoerer** [genicam/harvesters#249]
**Describe the Bug**
the code below is part of a bigger code. In my Project I have to change the exposure time, 
for this I have to stop the Image acquisition and there I allways get an error...

**To Reproduce**
Run the following script:

     from harvesters.core import Harvester
    def get_pic(ib):
        try:
            ia.start_acquisition()
        except:
            pass
        img = []
        while len(img) == 0:
            with ib.fetch_buffer(timeout=2) as buffer:  # timeout=t_out
                component = buffer.payload.components[0]
                img = component.data.reshape(
                    # Auslesen der Aufnahme (Helligkeitswerte) und Umwandlung in ein 2d-Array
                    component.height, component.width).astype(float)
        return img
    
    h = Harvester()
    h.add_file('ProducerGEV.cti')
    h.update()
    ia = h.create_image_acquirer(serial_number='23403068')
    ia.remote_device.node_map.ExposureTimeAbs.value = 52
    ia.remote_device.node_map.AcquisitionMode.value = 'Continuous'
    ia.remote_device.node_map.PixelFormat.value = 'Mono8'
    ia.start_acquisition(run_in_background=True)
    pic = get_pic(ia)
    ia.stop_acquisition()
    ia.destroy()
    h.reset()

Then I get the followin Error-Message:
`Traceback (most recent call last):
  File "C:\...\lib\site-packages\harvesters\core.py", line 2861, in stop_acquisition
    self.remote_device.node_map.AcquisitionStop.execute()
  File "C:\...\lib\site-packages\genicam\genapi.py", line 2624, in execute
    return _genapi.ICommand_execute(self, Verify)
  File "C:\...\lib\site-packages\harvesters\_private\core\port.py", line 54, in write
    self.port.write(address, value)
  File "C:\...\lib\site-packages\genicam\gentl.py", line 5016, in write
    return _gentl.Port_write(self, address, buffer)
_gentl.IoException: GenTL exception: Communication error, read or write to remote device failed. (Message from the source: Communication error has occurred) (ID: -1010)`

**Expected Behavior**
I would expect that the acquisition stops and no error Message occours

**Configuration**

 - OS: Windows
 - Python: 3.8.5
 - Harvester: 1.2.8
 - GenTL Producer: Basler
 - Camera: Basler ace

**Reproducibility**

This phenomenon can be reproduced by other versions:
- I havn't checked it

**Actions You Have Taken**
- restart/ reset the cams but it hasnt't worked or just for one or two runs
If someone could help me, it would be really great. Thanks a lot.

**Comment by kazunarikudo** [comment]
Hi, could you check what would it happen if the `get_pic` method return anything as follows?
```
def get_pic(ib):
    try:
        ia.start_acquisition()
    except:
        pass
    img = []
    while len(img) == 0:
        with ib.fetch_buffer(timeout=2) as buffer:  # timeout=t_out
            component = buffer.payload.components[0]
            img = component.data.reshape(
                # Auslesen der Aufnahme (Helligkeitswerte) und Umwandlung in ein 2d-Array
                component.height, component.width).astype(float)
```
