### ISSUE TITLE
switch the hardware and software trigger

### ISSUE THREAD

**Issue by Yingliangzhe** [genicam/harvesters#250]
Hello Everyone,
does someone know, that if is it possible to switch the Hardware and software setting? 
For example, that I set the AcquisitionMode to 'SingleFrame' and the Matrix Vision Camera can already take photo, once I call the `image_acquirer.start_acquisition()`. And I set the following features for NodeMap
`remote_device.node_map.TriggerSelector.value = 'FrameSelector'`
`remote_device.node_map.TriggerMode.value = 'on'`
`remote_device.node_map.TriggerSource.value = 'Line4'`
`remote_device.node_map.TriggerActivation.value = RisingEdge`
If I call the `start_acquisition()` again after setting the features, the camera should wait for a hardware trigger, and give me a image back. 

What if I want to switch reset the hardware feature setting and back to the normal Software trigger. The camera give me a image right after I call `start_acquisition()` ? Is that possible in genicam or in harvesters? 
I have tried to set the `remote_device.node_map.TriggerSelector.value = ''` and set it to `None`. Both of them are not allowed. 

Thank you

**Comment by kazunarikudo** [comment]
Hi, first, you'd need to set up the following features:
```
remote_device.node_map.TriggerSelector.value = 'FrameSelector'  # you can change this depending your use case.
remote_device.node_map.TriggerActivation.value = 'RisingEdge'
remote_device.node_map.TriggerMode.value = 'On'
```
Then, you would back and forth between the hardware trigger and the software trigger with:
```
remote_device.node_map.TriggerSource.value = 'Line4'
```
And:
```
remote_device.node_map.TriggerSource.value = 'Software'
```
While the device is working with the software trigger, you will trigger the device with the following line:
```
remote_device.node_map.TriggerSoftware.execute()
```
To get further in-depth knowledge I would recommend you to check out SFNC that is a collection of feature names and those definitions. You can download the latest version at [here](https://www.emva.org/wp-content/uploads/GenICam_SFNC_v2_6.pdf).

Good luck, Kazunari

**Comment by kazunarikudo** [comment]
> The camera give me a image right after I call start_acquisition() ?
If you set `AcquisitionStart` to `TriggerSelector` then you can get an image by calling `fetch_buffer()`. Please try to read through [this tutorial](https://github.com/genicam/harvesters#id49) to get the outline.

**Comment by Yingliangzhe** [comment]
Hello @kazunarikudo,
I have tried the another way, I have set the `remote_device.node_map.TriggerMode.value = 'On'` to 'Off' to switch the mode to Software. I have tried with the mvPropView, a software from  Matrix Vision. 

Thank you. 
And thank you for making harversters Lib for us. 
I hope, the support for arm64 is coming soon in this year.
