### ISSUE TITLE
Opening cameras in separate processes

### ISSUE THREAD

**Issue by aphilip442** [genicam/harvesters#252]
**Is your feature request related to a problem? Please describe.**
I would like to handle separate cameras in separate processes, however my attempts at giving the Harvester handle to separate processes have been unfruitful so far.

**Describe the solution you'd like**
Having a way to spawn image acquirers independently without having them under the same Harvester object would be ideal.

**Describe alternatives you've considered**
Having a way to pass a common Harvester handle to separate objects.

**Questions**
Am I missing something? 
If not, is there a reason this use case is not valid?

**Comment by kazunarikudo** [comment]
@aphilip442 Hi, visit [this page](https://github.com/genicam/harvesters/blob/master/src/harvesters/test/test_acq_frame_rate.py), and please take a look at a test called `test_multiple_access`. It demonstrates handling multiple image acquisition threads; each thread is responsible for image acquisition from a single camera. As far as I have tested, it should show you reasonable performance. Regards, Kazunari.

**Comment by aphilip442** [comment]
@kazunarikudo thank you for your reply (and for the neat library!).

test_multiple_access tests for one camera accessed by multiple threads to get the image acquisition statistics, not multiple image acquisitions? If not, could you show me the part where it does multiple image acquisitions? I am failing to see that.

I take from your answer that the feature I suggested is not reasonably achievable, and that the solution is to sequentially fetch the buffers like shown in _test_image_acquirers, with eventually a timeout of 0 if the number of cameras connected becomes high (3-5) to avoid having their respective performances interfere. Is that correct?

**Comment by kazunarikudo** [comment]
@aphilip442 Hi, please excuse me, I meant test_multiple_image_acquirers in [this file](https://github.com/genicam/harvesters/blob/master/src/harvesters/test/test_harvester_core.py)!
