### ISSUE TITLE
Any Sample script for acquiring images from a JAI Multispectral camera?

### ISSUE THREAD

**Issue by TahaAnwar** [genicam/harvesters#256]
I have a multispectral jai camera, [this one](https://www.jai.com/products/fs-3200d-10ge).  This has an RGB channel and NIR Channel, I was wondering if there is a way I can use harvester to read and store images from both channels. Would appreciate any guidance on the matter. 

Thanks.

**Comment by 104H** [comment]
I have the same camera and I am looking for the .cti file which is needed to connect to the camera, and I am unable to find the same.

**Comment by kazunarikudo** [comment]
Hi, sorry for having kept you waiting. If you have the right GenTL Producer, you should be able to acquire hyper-spectral information as you do for an ordinary image. I would recommend asking JAI people if they have their own GenTL Producer that can handle hyperspectral images, or if they know another GenTL Producer from the 3rd parties. Regards, Kazunari.
