### ISSUE TITLE
How can I read the value of a node_map?

### ISSUE THREAD

**Issue by LukasBernhardt00** [genicam/harvesters#263]
Hello,

I'm trying to read the current value of the node_map 's. I can write to them by using: 
"image_acquirer.remote_device.node_map.AcquisitionFrameRate.value = fps" for example but how can I read them?

Thanks in advance,

Lukas

**Comment by kazunarikudo** [comment]
@LukasBernhardt00 Hi Lukas, the following line is an example that reads the value from a feature node:
```
print(image_acquirer.remote_device.node_map.AcquisitionFrameRate.value)
```
Hope it is sufficient to get the idea. Regards, Kazunari.

**Comment by LukasBernhardt00** [comment]
Oh that's actually obivous, I've been staring at this for too long already I think :D 

Thank you very much!

**Comment by kazunarikudo** [comment]
Excuse me, the comment had been deleted by an accident; I meant to leave this:
```
if node_map.AcquisitionFrameRate.value > 0:
    print("that's greater than 0.")
```
