### ISSUE TITLE
GigE Camera can't detected by Harvesters

### ISSUE THREAD

**Issue by mirfani28** [genicam/harvesters#265]
Hi All

I'm currently having a trouble when using a harvester
I'm using this camera : http://www.contrastech.com/en/productview/1024.html
MARS4096S-13GM

I'm using Baumer SDK and it is detected by its own default Camera Explorer
but when I tried to connect it according tutorial, I don't found any specific info about the device. Only a blank space [ ]

![image](https://user-images.githubusercontent.com/90766716/133423294-2f20d805-cf65-4347-ab91-3a6a440fecb9.png)

I have tried using Matrix Vision SDK but it has the same problem, and the default GigE Program can't detect my camera.
My camera is already GenICam compliant

I'm using Python 3.6.13 in Anaconda virtual env and Windows 10
Really need your help where I went wrong

Thank you :)

**Comment by fabiosala** [comment]
Hello 
I had the same issue in Windows and I solved using the UNIX format in the path strings (using / instead of \\ ).
There is also an entry in the FAQ talking about this (https://github.com/genicam/harvesters/wiki/FAQ#i-pointed-out-a-cti-file-but-harvester-says-the-image-doesnt-exist-part-1).

Regards

**Comment by kazunarikudo** [comment]
@fabiosala Hi, thank you for the help you offered. I appreciate that! Regards, Kazunari.

**Comment by Alik-Mirzoyan** [comment]
I'm struggling with the same problem and can't connect my camera
I use this camera: https://integrys.com/product/hikvision-mv-ca016-10um/)
Camera: MV-CA016-10UM
i have downloaded the required GenTL Producer as mentioned in the documentation
https://harvesters.readthedocs.io/en/latest/INSTALL.html
But failed to load camera .cti file

**Comment by licongchao** [comment]
Encountering the issue in my environment, will update it if i find any solution

**Comment by licongchao** [comment]
@Alik-Mirzoyan after changing the cti file, i can connect the camera and get the image in memory
