### ISSUE TITLE
Connecting to a camera using IP address and configuring transmission mode

### ISSUE THREAD

**Issue by mahmoudabderahman** [genicam/harvesters#266]
Hi all,

I am trying to connect to the camera through the IP address instead of the direct (automatic) way and configure the transmission mode to be Unicast. As I am trying to let harvesters run in a docker container later and this container wrapping harvesters should communicate with other docker containers, that is why a specific/static IP address must be given to the camera.

Have anyone got to connect to a camera directly using an IP address or change the transmission mode?

Could someone give me some insights?

**Comment by kazunarikudo** [comment]
Hi, I am afraid, it is not possible to open a device by using an IP address as a key since Harvester is based on the GenTL standard; as far as I know, the GenTL standard does not offer a way to open a device by using a machine vision interface-specific information piece such as an IP address.
