### ISSUE TITLE
Best practice for stopping a triggered camera

### ISSUE THREAD

**Issue by danigamba** [genicam/harvesters#267]
Hello, I'm curious to know if there is a best practice for stopping a camera that is waiting the trigger.
In the main thread we launch a second one that stops on 
```
buffer = acq.fetch_buffer()
```
waiting for the camera aquiring a triggered frame of the next object. How could we stop this thread if the main tread needs to be stopped?
Thank you

**Comment by kazunarikudo** [comment]
@mahwhat Hi Matheus, thank you for the help. Those are the right approaches to resolve the issue.

This is completely a side note, we can rewrite the above code as follows:
```
acq.start()
with acq.fetch() as buffer:
    # work with the buffer
acq.stop()
```
Or,
```
acq.start(run_as_thread=True)
```
(I've learned that I was too verbose. ;-))

**Comment by kazunarikudo** [comment]
@danigamba I'm closing this but please feel free to create another one or reopen if you faced an issue. Thanks, Kazunari.
