### ISSUE TITLE
zero-sized buffers and _gentl.NotAvailableException returned during acquisition

### ISSUE THREAD

**Issue by aqc-carlodri** [genicam/harvesters#268]
**Describe the Bug**
First of all thank you for the great package! By running the simple script here below:

```python
from harvesters.core import Harvester

h = Harvester()
h.add_file(
    "C:\\Program Files\\MATRIX VISION\\mvIMPACT Acquire\\bin\\x64\\mvGenTLProducer.cti"
)
h.update()

ia = h.create_image_acquirer(0)
nmap = ia.remote_device.node_map
nmap.PixelFormat.value = "RGB8"
nmap.AcquisitionLineRate.value = 5000
nmap.Width.value = 4096
nmap.Height.value = 4096

ia.start_acquisition()

for num_frame in range(20):
    with ia.fetch_buffer() as buffer:
        print(buffer)

ia.stop_acquisition()


ia.destroy()

h.reset()
```

what I get is a random occurrence of zero-sized buffers and the below exception (not always happening together).
```
4096 x 4096, RGB8, 50331648 elements,
[0 0 0 ... 0 1 0]
4096 x 4096, RGB8, 50331648 elements,
[0 0 0 ... 0 0 0]
0 x 0, RGB8, 0 elements,
[]
0 x 0, RGB8, 0 elements,
[]
0 x 0, RGB8, 0 elements,
[]
4096 x 4096, RGB8, 50331648 elements,
[0 0 0 ... 0 0 0]
4096 x 4096, RGB8, 50331648 elements,
[0 0 0 ... 0 0 0]
0 x 0, RGB8, 0 elements,
[]
4096 x 4096, RGB8, 50331648 elements,
[0 0 0 ... 0 0 1]
4096 x 4096, RGB8, 50331648 elements,
[0 0 0 ... 0 0 0]
4096 x 4096, RGB8, 50331648 elements,
[0 1 0 ... 0 0 0]
4096 x 4096, RGB8, 50331648 elements,
[0 0 0 ... 0 0 0]
4096 x 4096, RGB8, 50331648 elements,
[0 0 0 ... 0 0 0]
4096 x 4096, RGB8, 50331648 elements,
[0 0 0 ... 0 0 0]
4096 x 4096, RGB8, 50331648 elements,
[0 0 0 ... 0 0 0]
4096 x 4096, RGB8, 50331648 elements,
[0 0 0 ... 0 0 0]
4096 x 4096, RGB8, 50331648 elements,
[0 0 0 ... 0 0 0]
4096 x 4096, RGB8, 50331648 elements,
[0 0 0 ... 0 1 0]
Traceback (most recent call last):
  File "issue.py", line 20, in <module>
    with ia.fetch_buffer() as buffer:
  File "C:\Users\xxxxx\Miniconda3\envs\genicam\lib\site-packages\harvesters\core.py", line 2778, in fetch_buffer
    if event_manager.buffer.is_complete():
  File "C:\Users\xxxxx\Miniconda3\envs\genicam\lib\site-packages\genicam\gentl.py", line 4562, in is_complete
    return _gentl.Buffer_is_complete(self)
_gentl.NotAvailableException: GenTL exception: Resource or information is not available. (Message from the source: Information 'BUFFER_INFO_IS_INCOMPLETE' is currently not available for this buffer) (ID: -1014)
```

When the zero-sized buffers occur, often the script hangs and never terminates.

**Expected Behavior**
No zero-content frames (or an exception if that happens). Or should I handle this case internally in my code?

**Configuration**

 - OS: Win10x64
 - Python: 3.8.12
 - Harvester: 1.3.2
 - GenTL Producer: MATRIX VISION mvIMPACT_Acquire 2.45.0
 - Camera: Teledyne DALSA Linea 4k Color
 - Camera interface: GigE Vision

**Reproducibility**
I haven't tried with other Harvesters versions. The appearance of the zero-sized buffers and of the exception are quite random and not always reproducible.

**Actions You Have Taken**
I have also tried to use `nmap.TestPattern.value = "GreyHorizontalRamp"` and the issue occurs identically.

 - [X] I've read the [Harvester FAQ page](https://github.com/genicam/harvesters/wiki/FAQ).

**Additional context**
I'm using a network adapter with 9K jumbo frames and all the recommended NIC settings from the DALSA network configuration guide.

**Comment by aqc-carlodri** [comment]
Thank you for your kind feedback @kazunarikudo! By using your code snippet above I cannot see the the "GigE Vision Host Controls" nodes. I think the problem is that the standard MATRIX VISION GenTL producer is likely not aware of those nodes since they are DALSA-specific. Sadly, DALSA does not distribute a GenTL producer (the `*.cti` file) for their Linea cameras, so I'm forced to use other generic producers. I will probably try the Common Vision Blox producer that seems to have some support for DALSA-specific features (like TurboDrive).

**Comment by StefanD986** [comment]
Hi @kazunarikudo I am facing the same issue as @aqc-carlodri .
Can you explain the details on the node injection that you  mentioned above?
> Node injection can be technically possible

How would I go about that?

**Comment by StefanD986** [comment]
Hi @aqc-carlodri try the new 1.3.4 release, it fixed this issue for me, I guess this will also fix it for you.

**Comment by aqc-carlodri** [comment]
Thanks for the heads up @StefanD986! At the moment I'm using the Common Vision Blox GenTL producer, and it seems that the issue does not occur any more. But I'm not sure it is the producer's fault, since actually I've seen the issue sometimes also with the CVB producer. For the moment I will close this issue, but will re-open in case I face it again.

Although I have to say I'm a little worried by the fact that I could not understand what was going on...
