### ISSUE TITLE
Check of camera disconnected

### ISSUE THREAD

**Issue by EnricoBeltramo** [genicam/harvesters#272]
**Is your feature request related to a problem? Please describe.**
There is an event or exception to catch in order to detect camera disconnected during acquisition?

**Describe the solution you'd like**
A event like "camera disconnected"

**Describe alternatives you've considered**
I tried to catch acquisition exceptions, but I'm not able to detect this kind of error

**Additional context**

**Comment by mahwhat** [comment]
Hi @EnricoBeltramo ,

I know that the Harvesters have the following events:

- ImageAcquirer.Events.TURNED_OBSOLETE - This event occurs after releases all preserved external resources such as buffers or the connected remote device.
- ImageAcquirer.Events.NEW_BUFFER_AVAILABLE - This event occurs after acquiring a new buffer/image.
- ImageAcquirer.Events.RETURN_ALL_BORROWED_BUFFERS - This event occurs to notify that he has to return/queue buffers back.
- ImageAcquirer.Events.READY_TO_STOP_ACQUISITION - This event occurs when the number of images to be acquired is equal zero.
- ImageAcquirer.Events.INCOMPLETE_BUFFER - This event occurs when acquired buffer was incomplete.


To use you must add a new callback

**Comment by EnricoBeltramo** [comment]
Thank for support, I was able to detect the status checking this flag:
ia.device.module.access_status
when the camera is disconnected, the value is set to 3
Anyway, I tried to reset all e restart communication in order to recovery the camera acquisition, but the driver after reset look not able to reconnect again. There is a procedure to close all pending action and restart the acquisition from scratch?

**Comment by mahwhat** [comment]
This is a problem I have too. In my project I have to kill all processes linked to the devices to perform the reconnection.

I imagine that it is possible to perform the reconnection to the device through the manipulation of the network interface and GenTL, but I haven't had time to work on that yet.

**Comment by kazunarikudo** [comment]
I am afraid, the expected feature requires a feature on the GenTL Producer side and it is not standardized. For now, please accept a fact that there is nothing that Harvester can help you. (I will discuss this issue with my GenICam colleagues.) Regards, Kazunari.
