### ISSUE TITLE
Accessing camera without cti file

### ISSUE THREAD

**Issue by revathib01** [genicam/harvesters#273]
We have four cameras in our application( two allied vision cameras and two mstar vision cameras). Allied vision cameras manufacturer has provided the cti file, using the CTI file, we are able to grab the frames, whereas the mstar cameras manufacturer has not provided the cti file (When contacted them they told they don't have cti file). 

Can we access mstar vision cameras without cti files. If not, can you let us know there is any  way to generate cti files for mstar cameras and Does Harvester supports other  cameras  which are not mentioned in readme file of harvestor

Thanks 
Revathi

**Comment by StefanD986** [comment]
AFAIK the cti files are somewhat universal, so you should try whether you can use the Mstar cameras with the allied vision cti file. However I can already say it doesn't always work. We have two cameras, one Allied vision, one Xenics Bobcat, and the Xenics does not work well with the Allied vision CTI file. For us the solution was to use a cti file from Matrix vision instead.

**Comment by AlmeidaAlin3** [comment]
Hi! I'm trying to use the FX17 camera from SPECIM, but they do not provide the cti files. Would it be a good idea to use these Allied vision cti files you mentioned? Could please help me getting them?

**Comment by StefanD986** [comment]
The CTI files are part of the Allied Vision Vimba SDK. You can download it on the Allied Vision website, install it and then search the installation directory for *.cti files.

**Comment by kazunarikudo** [comment]
Hi guys, some GenTL Producers, especially the ones from camera manufacturers, intentionally drop cameras from their competitors. This is just for your information. Regards, Kazunari.

**Comment by kazunarikudo** [comment]
Here's [the list](https://github.com/genicam/harvesters#id46) of GenTL Producers. Of course, there are some more but you may find a one that works for you.

**Comment by kazunarikudo** [comment]
One more thing, the first entry I recommend to use is the one from MATRIX VISION; they have [a Windows version](http://static.matrix-vision.com/mvIMPACT_Acquire/2.46.1/mvGenTL_Acquire-x86_64-2.46.1.exe) and [a Linux version](http://static.matrix-vision.com/mvIMPACT_Acquire/2.46.1/install_mvGenTL_Acquire.sh).
