### ISSUE TITLE
Error when chunk data is enabled with FLIR Grasshopper camera

### ISSUE THREAD

**Issue by harriojanen** [genicam/harvesters#276]
**Describe the Bug**
Using a FLIR Grasshopper USB3 camera with the FLIR drivers and .cti file. If I enable chunk data then already the first call to fetch_buffer throws a RuntimeException (every time). It does not matter which parameters are enabled for the chunk data. This happens every time, so it does not appear to be any random data corruption.

**To Reproduce**

```
import os
from harvesters.core import Harvester

h = Harvester()
h.add_file(r'C:\Program Files\FLIR Systems\Spinnaker\cti64\vs2015\FLIR_GenTL_v140.cti')
h.update()

ia = h.create_image_acquirer(0)
ia.remote_device.node_map.ChunkModeActive.value = True
ia.remote_device.node_map.ChunkSelector.value = 'Gain' # or any other supported value
ia.remote_device.node_map.ChunkEnable.value = True
    
ia.start_acquisition()

with ia.fetch_buffer() as buffer:
    component = buffer.payload.components[0]
    img = component.data.reshape(component.height, component.width)
img.shape, img.dtype
```

**Expected Behavior**
fetch_buffer should not throw an exception, and valid chunk data should be available.

**Configuration**
 - OS: Windows 10
 - Python: 3.7.9
 - Harvester: 1.3.2
 - GenTL Producer: FLIR Spinnaker SDK 2.5.0.80 (x64)
 - Camera: FLIR/Point Grey Research Grasshopper3 GS3-U3-23S6C both with older firmware 2.14 and latest firmware 2.30

**Reproducibility**
Error happens with the FLIR software (driver and GenTL producer + harvester) as described above.

Tested also with Matrix Vision mvGenTL_Acquire(x64) version 2.45.0 (i.e., MV driver and MV GenTL producer): chunk data works corretly, no error is thrown, and the values returned in the chunks appear to be correct.

**Actions You Have Taken**
Tried upgrading the firmware on the camera, but that provided do help.

Tested with the GUI software from FLIR ("Spinview"): chunk data works correctly with their GUI.

Tested also with Matrix Vision software, and that works correctly with this camera.
 
- [X] I've read the [Harvester FAQ page](https://github.com/genicam/harvesters/wiki/FAQ).

There is mention of chunk data problems in the FAQ. The camera and data transmissions seem to be fine, since it works correctly with software from another party. Then the question remains if this is an incompatibility between harvester and FLIR software, or a clear bug in one of them. 

**Additional context**
```
The full error message:
---------------------------------------------------------------------------
RuntimeException                          Traceback (most recent call last)
~\AppData\Local\Temp\ipykernel_149904\25613793.py in <module>
     12 ia.start_acquisition()
     13 
---> 14 with ia.fetch_buffer() as buffer:
     15     component = buffer.payload.components[0]
     16     img = component.data.reshape(component.height, component.width)

c:\a\venv-cams\lib\site-packages\harvesters\core.py in fetch_buffer(self, timeout, is_raw, cycle_s)
   2804         if _buffer:
   2805             #
-> 2806             self._update_chunk_data(buffer=_buffer)
   2807 
   2808             # Then update the statistics using the buffer:

c:\a\venv-cams\lib\site-packages\harvesters\core.py in _update_chunk_data(self, buffer)
   2695                     )
   2696                 else:
-> 2697                     self._chunk_adapter.attach_buffer(buffer.raw_buffer)
   2698             except GenericException as e:
   2699                 # Failed to parse the chunk data. Something must be wrong.

c:\a\venv-cams\lib\site-packages\genicam\genapi.py in attach_buffer(self, buffer, statistics)
   2961     def attach_buffer(self, buffer, statistics=None):
   2962         self._buffer = buffer
-> 2963         self._adapter.attach_buffer(self._buffer, statistics)
   2964 
   2965     def detach_buffer(self):

c:\a\venv-cams\lib\site-packages\genicam\genapi.py in attach_buffer(self, pBuffer, pAttachStatistics)
   3128 
   3129     def attach_buffer(self, pBuffer, pAttachStatistics=None):
-> 3130         return _genapi._ChunkAdapterU3V_attach_buffer(self, pBuffer, pAttachStatistics)
   3131 _ChunkAdapterU3V_swigregister = _genapi._ChunkAdapterU3V_swigregister
   3132 _ChunkAdapterU3V_swigregister(_ChunkAdapterU3V)

RuntimeException: Invalid layout of buffer attached to chunk parser! : RuntimeException thrown (file 'ChunkAdapterU3V.cpp', line 95)
```

**Comment by harriojanen** [comment]
FLIR technical support replied that they can reproduce the problem and they are investigating further. I will update here their findings.

**Comment by harriojanen** [comment]
@olofsjo Thanks for your work on this, but unfortunately it does not seem to resolve the issue with this camera. Testing with commit cade876: the call to fetch_buffer does not return any image any more, when chunk data is enabled. The error messages are different also:

`2022-02-23 10:59:45,504 :: harvesters.core :: ERROR :: GenTL exception: Requested operation not implemented. (Message from the source: Invalid enum. BUFFER_INFO_CMD iInfoCmd = 23 Expected range from 0 to 25.) (ID: -1003)
Traceback (most recent call last):
  File "c:\a\venv-cams-harvester-testing\lib\site-packages\harvesters-0.0.0-py3.7.egg\harvesters\core.py", line 2307, in _update_chunk_data
    if (len(buffer.raw_buffer) > buffer.delivered_chunk_payload_size):
  File "c:\a\venv-cams-harvester-testing\lib\site-packages\genicam\gentl.py", line 4404, in _get_delivered_chunk_payload_size
    return _gentl.Buffer__get_delivered_chunk_payload_size(self)
_gentl.NotImplementedException: GenTL exception: Requested operation not implemented. (Message from the source: Invalid enum. BUFFER_INFO_CMD iInfoCmd = 23 Expected range from 0 to 25.) (ID: -1003)
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
~\AppData\Local\Temp\ipykernel_11904\3539931620.py in <module>
     14 
     15 with ia.fetch_buffer() as buffer:
---> 16     component = buffer.payload.components[0]
     17     img = component.data.reshape(component.height, component.width)
     18 img.shape, img.dtype

AttributeError: 'NoneType' object has no attribute 'components'`

**Comment by olofsjo** [comment]
@harriojanen I do not have the camera you are using available but I know @kazunarikudo did some more adaptions on the commit you have tested on so it might be worth to test commit 677c3a9ebfcd0eedec4755c74049cd6d7d3bc25c as well.
I have not tested this latest commit myself yet on our camera, will see if I get time to do that today or later this week.

**Comment by harriojanen** [comment]
I tested now the commit 677c3a9 also: there is the same problem as with commit cade876: there is no image returned. The only difference seems to be that the error message "harvesters.core :: ERROR :: GenTL exception: Requested operation not implemented..." is not shown.

**Comment by kazunarikudo** [comment]
@harriojanen Hi, thank you for the update. I'll look into it and get you back. Thanks, Kazunari.

**Comment by kazunarikudo** [comment]
@harriojanen Hi, I need to interview you some. Could you show me the outputs from the following code?
```
with ia.fetch_buffer() as buffer:
    print(buffer.payload_type)  # <--- I need the output from here.
    print(buffer.payload)  # <--- I need the output from here.
    # I do not need to have any output from the following lines because I know it throws as reported.
    component = buffer.payload.components[0]
    img = component.data.reshape(component.height, component.width)
```
I believe the original issue has been resolved and guess you are facing the second one. Thanks!

**Comment by kazunarikudo** [comment]
@harriojanen It may be valuable to try another GenTL until the issue is resolved even if you can't use it on your production stage. I would recommend trying [a GenTL producer](http://static.matrix-vision.com/mvIMPACT_Acquire/2.46.1/mvGenTL_Acquire-x86-2.46.1.exe) from MATRIX VISION. Please do not forget to use MATRIX VISION's U3V driver to work with their GenTL Producer.

**Comment by harriojanen** [comment]
@kazunarikudo Thanks for looking into this. The outputs from the two prints you suggested are:

`1001
None`

With chunk data disabled the outputs are:

`1
1920 x 1200, Mono8, 2304000 elements,
[8 7 8 ... 8 8 9]`

**Comment by kazunarikudo** [comment]
@harriojanen Thank you for the update. The ID `1001` is a custom ID so nobody except FLIR people knows what it is. Do you have any FLIR documents that mention that? The ID is called `PAYLOADTYPE_INFO_IDS` and is defined by the GenTL standard.

**Comment by harriojanen** [comment]
@kazunarikudo In the FLIR SDK header files there is an enum PayloadTypeInfoIDs with values 0 to 10 called the same as in the GenTL standard. There are a number of ids with value over 1000. The value 1001 is called "PAYLOAD_TYPE_EXTENDED_CHUNK" in the header.

**Comment by kazunarikudo** [comment]
@harriojanen The word "Custom" here means the payload is NOT defined by the standard. If FLIR is willing to help you to work with Harvester, you should ask them what the payload would look like so that I can give you the expected data pieces. Otherwise, I will never have anything to do for you.

**Comment by harriojanen** [comment]
Thank you @kazunarikudo, your help has been very useful in trying to understand this issue. I'll contact FLIR and provide them with the things we've found out here. Perhaps by default they should use one of the standard payload types, instead of one of their own custom types... Somehow I think that should be possible, since the camera and chunk data work with the Matrix Vision producer, so if I understand this properly the camera can provide standard payloads, but FLIR producer does something strange, so that the buffers are in their custom format. I'll update here when I here back from them.

**Comment by harriojanen** [comment]
@kazunarikudo FLIR support replied that indeed they have switched to using a custom payload. They follow by suggesting the following:

> ... we translated FLIR camera extended chunk data payloads to a custom payload type we defined as "PAYLOAD_TYPE_EXTENDED_CHUNK". 
> 
> In the GenTL.h, there is the following defined:
> 
> PAYLOAD_TYPE_CHUNK_DATA = 4, /* GenTL v1.2, Deprecated in GenTL 1.5*/ 
> 
> Although the header says this payload type is deprecated in 1.5, we could try this out and this should allow GenTL consumers to better handle chunk payload types.

Do you think it would make sense if they switched to using the above payload type, even though it is deprecated?

**Comment by kazunarikudo** [comment]
Hi, thank you for the update. Okay, I have just created a branch (resolve-issue-276) so that you can check if it works for you; it tries to interpret the delivered payload as an image if the payload type is a custom type. If the actual payload is an image with chunk data, then it should work. Please let me know the outcome if you get a chance to give it a try. Thanks!

**Comment by harriojanen** [comment]
@kazunarikudo Thanks for the workaround. I tested the branch resolve-issue-276 and it seems to be working (well, at least with the type of camera that we are using): both the images and the chunk data appear correct.

**Comment by kazunarikudo** [comment]
@harriojanen Hi, thank you for the update. Please create another ticket if you get another issue. Good luck! /Kazunari.
