### ISSUE TITLE
urlparse() leaves an extra slash at the beginning of the path on Windows

### ISSUE THREAD

**Issue by k2arjun** [genicam/harvesters#277]
**Describe the bug**
The call to urlparse() in line 2338 of core.py returns with an extra '/' at the beginning of the string of its "path" member. This seems to have been addressed for the location == "local" case, but not for the location == "file" case. (#128)

Camera returns the following url: 'file:///C:/ProgramData/GenICam/xml/cache/Optronis_Cyclone_V1_7_8.xml'

urlparse().path = '/C:/ProgramData/GenICam/xml/cache/Optronis_Cyclone_V1_7_8.xml'

**Expected Behavior**
The leading slashes should be stripped, like with the _location == "local"_ case.

**Screenshots**
![image](https://user-images.githubusercontent.com/91284784/154353035-7e0f9207-8148-451a-a1f9-5510e7f26d6e.png)

**Configuration**

 - OS: Windows 10
 - Python: 3.7.10
 - Harvester: 1.2.8
 - GenTL Producer: BitFlow, Inc
 - Camera: Optronis

- [x] I've read the [Harvester FAQ page](https://github.com/genicam/harvesters/wiki/FAQ).

**Comment by kazunarikudo** [comment]
@k2arjun Hi, thank you for the report. I will fix that. Regards, Kazunari.
