### ISSUE TITLE
Main thread slow after PR #286

### ISSUE THREAD

**Issue by blaine141** [genicam/harvesters#291]
**Describe the Bug**
The background thread slows down the main thread after PR #286.

**To Reproduce**
1. Run a general streaming program with background thread on a commit before the PR.
2. Run it again after the PR and notice the lag in the main thread.

**Expected Behavior**
Main thread should continue to be uninterrupted

**Actions You Have Taken**

Found the issue and will be submitting a PR
 
- [X] I've read the [Harvester FAQ page](https://github.com/genicam/harvesters/wiki/FAQ).

**Additional context**

**Comment by kazunarikudo** [comment]
@blaine141 Hi, please feel free to close this ticket if you can confirm the issue has been fixed. Regards, Kazunari.
