### ISSUE TITLE
Unable to detect or connect to Lucid Vision Labs-TRI023S-C

### ISSUE THREAD

**Issue by nznobody** [genicam/harvesters#294]
**Describe the Bug**

I am unable to get a Lucid Vision Labs GigE camera to be detected. I understand that this could be because Lucid's cameras are problematic, but I'd appreciate some confirmation that I am approaching this correct. What could be done to enable this software to work with their cameras? Would a wrapper around their ArenaSDK (in python) be suitable?

**To Reproduce**
1. 
```python
from harvesters.core import Harvester
import numpy as np
h = Harvester()
h.add_file("\some\valid\path\mvGenTLProducer.cti")
h.update()
len(h.device_info_list)
>>> 0
```
2.

**Expected Behavior**

I expect the camera to be detected. It is connected via Ethernet and if I open ArenaView it is detected and I can stream from it. If I open wxPropView (from mvGenTL_Acquire-x86_64-2.46.1.exe) then I can view the device and access it.

**Screenshots**
If applicable, add screenshots to help explain your problem; Note that it is not necessary to put everything as a screenshot! If the source is a text just paste the text because that is much helpful for us.

![image](https://user-images.githubusercontent.com/4408977/156499591-36e5cc2e-4fab-45ab-a364-bfcd13962ba0.png)
![image](https://user-images.githubusercontent.com/4408977/156501118-9209978a-f309-492a-8a68-fd56bd0acb79.png)

**Configuration**

 - OS: Microsoft Windows 10 Enterprise 10.0.18363 Build 18363
 - Python: Python 3.8.10
 - Harvester: `genicam==1.1.0
harvesters==1.3.2`
 - GenTL Producer: mvGenTLProducer.cti 2.46.1
 - Camera: Lucid Vision Labs-TRI023S-C

**Reproducibility**

This phenomenon can be reproduced by other versions:

- [ ] Yes

If so, please list up the reproducible versions you have confirmed:

* a.b.c

**Actions You Have Taken**
Tried using https://github.com/AravisProject/aravis and it can roughly detect the camera (but has many issues)
 
- [X] I've read the [Harvester FAQ page](https://github.com/genicam/harvesters/wiki/FAQ).

**Additional context**

**Comment by kazunarikudo** [comment]
Hi, thank you for the report; here are few questions:

* Did you change the location of the CTI file by yourself?
* I can confirm you have used the backslash symbol as the path separator; have you put the `r` symbol at the beginning of the path to prevent the backslashes escape the following letter? You could intentionally use the forward-slash instead. (See this [link](https://docs.python.org/3/reference/lexical_analysis.html#string-and-bytes-literals) about the `r`.)

Regards, Kazunari.

**Comment by nznobody** [comment]
Hello @kazunarikudo :)

Thanks for your super fast response! I can confirm that adding the `r` to the actual path (I had changed it for the issue) solved it and I know get:
```
[(id_='TRI023S-C(1c:0f:af:00:fb:93)', vendor='Lucid Vision Labs', model='TRI023S-C', tl_type='GEV', user_defined_name=None, serial_number='213902307', version='1.69.0.0')]
```

I will check tomorrow that it actually captures images, but will close this for now!

I am surprised that it did not generate any errors, but I should have known about `r` on windows! Would a PR addressing this with a warning or error when the `add_file` argument can't be found be useful? I'd be happy to implement that.
