### ISSUE TITLE
Fetch_buffer locks program if camera uses external trigger

### ISSUE THREAD

**Issue by tanzerlana** [genicam/harvesters#304]
Hi all,

I would need to run the camera with a external trigger. so far all ok, managed to do so. but while the camera is in aquisition, until when the trigger arrives, the whole program is locked. 

Is it possible to run harvester ona different thread to avoid locking all up?

thank you!

best regards

**Comment by kazunarikudo** [comment]
Hi, you can run the image acquisition thread by calling as follows:
```
ia.start_acquisition(run_in_background=True)
```
It does not block other threads. Regards, Kazunari.

**Comment by tanzerlana** [comment]
thank you!

**Comment by kazunarikudo** [comment]
Hi Igor, please feel free to close this ticket if you can confirm the issue has been resolved. Thanks.
