### ISSUE TITLE
pip doesn't find genicam with Python 3.7

### ISSUE THREAD

**Issue by SharpFGC** [genicam/harvesters#317]
Hi! I'm trying to install both harvesters and genicam through pip for a project but when I use the command "pip install genicam" it returns:

"ERROR: Could not find a version that satisfies the requirement genicam (from versions: none)
ERROR: No matching distribution found for genicam"

If I try to install harvesters than it gives a dependecy error as expected:

"The conflict is caused by:
    harvesters 1.3.4 depends on genicam<1.2"

**Expected Behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem; Note that it is not necessary to put everything as a screenshot! If the source is a text just paste the text because that is much helpful for us.

**Configuration**

 - OS: Windows 10 64-bit
 - Python: 3.7.7

**Actions You Have Taken**
- Tried both in my own pc's CMD and in a Visual Studio Code virtual enviroment
,

 
- [X] I've read the [Harvester FAQ page](https://github.com/genicam/harvesters/wiki/FAQ).

Thanks for your time in advance.

**Comment by kazunarikudo** [comment]
@SharpFGC Hi, could you show me the output from the following command?
```
pip list
```
This is just for your information, I could not reproduce the reported phenomenon so I guess there should be a reasonable solution for you. By the way, please note that neither `harvesters` nor `genicam` work on Cygwin because the GenApi reference implementation does not support Cygwin GCC. Regards, Kazunari.

**Comment by kazunarikudo** [comment]
Here's one more request; I would like to see the output from the following command as well:
```
python -c "import sys;print(sys.version)"
```

**Comment by SharpFGC** [comment]
Firstly thanks for the quick response. Much appreciated.

pip list returns:

Package            Version
certifi            2021.10.8
charset-normalizer 2.0.12
idna               3.3
pip                22.0.4
PyQt5              5.15.6
PyQt5-Qt5          5.15.2
PyQt5-sip          12.9.1
requests           2.27.1
requests-toolbelt  0.9.1
setuptools         60.10.0
six                1.16.0
slumber            0.7.1
urllib3            1.26.9

And python -c "import sys;print(sys.version)" returns:

3.7.7 (tags/v3.7.7:d7c567b08f, Mar 10 2020, 09:44:33) [MSC v.1900 32 bit (Intel)]

**Comment by kazunarikudo** [comment]
Hi, thank you for the update. Are you trying to run it on a 32-bit architecture? If so, I’m afraid, we do not support any of them. I hope you have a 64-but as an option. Regards, Kazunari.

**Comment by SharpFGC** [comment]
Hello again, I didn't know at the time that I downloaded a 32-bit version of P3.7, I installed a 64 one and was able to find genicam nd install harvesters.

Sorry for the trouble and thanks!
