### ISSUE TITLE
More data returned in the buffer than what the components indicate

### ISSUE THREAD

**Issue by TouchTheFishy** [genicam/harvesters#318]
**Describe the Bug**
Hi,

I am using a linear hyperspectral camera SpecimFX17. 

When the binning is low (1 or 2), no issue is present. Although, when I try to set the binnings both for x and y to 8, Harvesters returns the following error 
```
Traceback (most recent call last):
  File "/home/bota/Desktop/apic-bench/bota/specim_capture.py", line 236, in scan
    _1d = component.data.reshape(wavelength, x)
ValueError: cannot reshape array of size 2560 into shape (28,80)
```
And when I print the component height and width it says 28 and 80 respectively. Although, 28x80 is equal to 2240, not 2560.

When I set a lower binning (e.g. 4 for x and 4 for y) I get the same issue but with different values
```
Traceback (most recent call last):
  File "/home/bota/Desktop/apic-bench/bota/specim_capture.py", line 236, in scan
    _1d = component.data.reshape(wavelength, x)
ValueError: cannot reshape array of size 9216 into shape (56,160)
```

But when I set only one of the binnings high (e.g. x = 1 and y = 8 or x = 8 and y = 1) everything works perfectly.

 - OS: Linux Ubuntu 20.04.4
 - Python:  3.8.10
 - Harvester: 1.3.4
 - GenTL Producer: MvImpact 2.45.0
 - Camera: Specim FX17

**Comment by kazunarikudo** [comment]
@TouchTheFishy Hi, thank you for the report. Could you show me the output from the following code? It would be great if you could try to run the code with some binning settings:
```
ia.start()
with ia.fetch() as buffer:
   component = buffer.payload.components[0]
    attributes = ["width", "height", "x_offset", "x_padding", "y_offset", "y_padding"]
    for attribute in attributes:
        print("{}: {}".format(attribute, getattr(component, attribute, None)))
ia.stop()
```
Regards, Kazunari.

**Comment by TouchTheFishy** [comment]
Hi Kazuna

Here's what I got:
BinningVertical = 8 , BinningHorizontal = 8:
```
width: 80
height: 28
x_offset: 0
x_padding: 0
y_offset: 132
y_padding: 640
```

BinningVertical = 4 , BinningHorizontal = 4:
```
width: 160
height: 56
x_offset: 0
x_padding: 0
y_offset: 132
y_padding: 512
```

BinningVertical = 2 , BinningHorizontal = 2: (This one works)
```
width: 320
height: 112
x_offset: 0
x_padding: 0
y_offset: 132
y_padding: 0
```

BinningVertical = 1 , BinningHorizontal = 8: (This one works as well)
```
width: 640
height: 28
x_offset: 0
x_padding: 0
y_offset: 132
y_padding: 0
```

BinningVertical = 8 , BinningHorizontal = 1: (This one works too)
```
width: 80
height: 224
x_offset: 0
x_padding: 0
y_offset: 132
y_padding: 0
```
Thanks for your help,
Paolo

**Comment by TouchTheFishy** [comment]
Hi Kazunari (Sorry for misspelling your name in the last comment),

Your change seems to have done the trick

Thanks for the help! 
Fishy

**Comment by kazunarikudo** [comment]
@TouchTheFishy Hi, thank you for the reply. You're welcome, I'm glad it worked for you (and I hope it does not break anything for the others, either). Regards, Kazunari.

**Comment by gsainsbury86** [comment]
Sorry to reply to a closed issue, but would you be able to share some more information about your environment and code @TouchTheFishy ? I am working with an FX10 and I can't get to the point of receiving any data from the camera. My code hangs when I try to call `h.create()` . I suspect it might be because I'm not sending the correct information about binning etc. ahead of time..
