### ISSUE TITLE
Bump major version for non-backward compatible API changes

### ISSUE THREAD

**Issue by StefanD986** [genicam/harvesters#323]
I saw in the code that some methods are deprecated in 1.3.5 with the comment stating that they will be **removed** in 1.4.0. If they are indeed removed in harvesters 1.4.x would not be backward compatible with code that used harvesters 1.3.x.

I am not sure whether Harvesters follows [semantic versioning](https://semver.org/) guidelines, but if indeed it is, then technically a non-backwards compatible change in the API should cause a bump of the major version number (=> bump to 2.x).

Otherwise this might cause some surprise in projects that depend on Harvesters and pinned the version to 1.x to allow for feature upgrades but prevent accidental breaking updates.

**Comment by StefanD986** [comment]
I actually see now that 1.3.5 already has some breaking API changes (e.g. signature of the `Harvester` constructor changed from keyword arguments for the `logger` to taking a `config` `ParameterSet` instead.

**Comment by Gornoka** [comment]
1.3.4 (maybe even 1.3.3) also had some Breaking changes regarding Exception names.
IIRC the Timeout exception now does not exist but throws a different generic exceptions. However importing the old timeout excetption is no longer possible and therefore breaks all old code that tried to manually handle it.

**Comment by kazunarikudo** [comment]
@StefanD986 Hi, I have just pushed the change to the following branch:

https://github.com/genicam/harvesters/tree/323-bump-major-version-for-non-backward-compatible-api-changes

In the branch, I have gotten the dropped public API back; no change in their deprecation status. If you can happy with that, I will merge it into the master and release it as 1.3.6 soon. This is just for your information, version 1.3.5 has been dropped from PyPI. Regards, Kazunari.

**Comment by StefanD986** [comment]
Great! I looked through it and tried it with our application and it works again. Thanks for the quick action.

**Comment by kazunarikudo** [comment]
@StefanD986 Hi Stefan, thank you for giving that a try, and for giving me an opportunity to bring up the perspective of dependency maintainability into my project. I appreciate that. Regards, Kazunari.
