### ISSUE TITLE
detect camera on different subnet or be able to change subnet

### ISSUE THREAD

**Issue by BaileyHelfer** [genicam/harvesters#333]
**What is the goal that you want to achieve by the request?**
Please describe a clear and concise description of what the motivation is. For example:

I'm not sure if there already is a way that I don't know about but being able to detect cameras on different subnets or being able to change the subnet through harvesters would be very useful. I've been able to get the subnet mask with GevInterfaceSubnetMask but if I go to change the value I get and error saying the node is not writable or something along those lines.

**Additional context**
This would be nice for mass setting camera ip address's even if they are not on the same subnet because they can be detected and configured through the GenTL Producer if they are on different subnet so I figured you could do the same within harvesters.

**Comment by olofsjo** [comment]
The support for doing GevDeviceForceIP has recently been added to Harvester by mr Kazunari by exposing the required node map without connecting to the device. If your device supports this or not is another question since it is an optional feature in the standard. 

The following code snippet is sample on how the functionality can be achived:
``` 
node_map = h.device_info_list[index].parent.node_map
node_map.GevDeviceProposeIP.execute()
node_map.GevDeviceForceIP.execute()
while not node_map.GevDeviceForceIP.is_done():
  time.sleep(0.1)
h.update()
```
After doing this you can connect to the camera and change the IP-settings permanently.

Which camera and cti-file are you using in your application? This is sometimes/often useful information.

**Comment by BaileyHelfer** [comment]
Thank you for your response. I am using Matrix Vision CTI file. I will have to try your solution and see if that is what I want accomplished. When I use GevInterfaceSubnetMask.set(4294967040) I get this error.
NotImplementedError: Wrong number or type of arguments for overloaded function 'IInteger_set'.
  Possible C/C++ prototypes are:
    GENAPI_NAMESPACE::IInteger::Set(uint8_t const *,int64_t,bool)
    GENAPI_NAMESPACE::IInteger::Set(uint8_t const *,int64_t)
But by the looks of it this has to do with the geniapi and not harvesters itself.

**Comment by kazunarikudo** [comment]
Quick question: How did you notice that the `GevInterfaceSubnetMask` is the feature node that you want to work with?

**Comment by BaileyHelfer** [comment]
Sure, I am not for certain that it is the feature node that I want to work with but I figured that it would be. I figured it would be because if I changed the subnet mask on for my Network Interface Card (NIC) to the same as camera then I can detect it. And when I print out the value of this feature node it is indeed the subnet mask of my NIC so I figured that it would be feature node to work with.

**Comment by kazunarikudo** [comment]
Ah, please excuse me: I had been mixed up this with another topic. However, the `GevInterfaceSubnetMask` is defined as a read-only node; see [this standard document](https://www.emva.org/wp-content/uploads/GenICam_GenTL_SFNC_1_2.pdf). Isn't it possible to set the subnet on the interface in advance without involving Harvester or other tools? You can change the IP address-related properties on the device side but as far as I check you can't on the other entities.

**Comment by BaileyHelfer** [comment]
Thank you for the information and the useful link. Yes it is possible to set it before hand but it could be useful to have a script to automate to check all or certain subnets for cameras and set their IP's to proper configuration but I believe this might be achievable by some other tools/libraries maybe? I just thought maybe it was possible in Harvesters.

**Comment by BaileyHelfer** [comment]
Is it possible to change the IP of a camera with access status as "No Access"? If the camera is on the same subnet I can see it but can't connect because it has different ip address. If I could change the IP without connection that would be useful so I can connect to it without having to change it manually.

**Comment by olofsjo** [comment]
If you are looking to change the IP-address of the camera prior to connecting to it my code snippet might be useful, we use it to change the camera IP settings when we detect a camera that we cannot connect to due to different subnets. If you want to change your local computers settings, that can also be done using Python but I assume not with Harvesters so then you need to look into using another library.

**Comment by BaileyHelfer** [comment]
I finally found what I was looking for.....
I had to use GevDeviceForceIPAddress.set_value(some ip) & GevDeviceForceSubnetMask.set_value(some ip)
and then use GevDeviceForceIP.execute() after. Thank you guys for all the help.

**Comment by kazunarikudo** [comment]
Thank you guys, keep happy coding.
