### ISSUE TITLE
Question: How to check if .cti file is correctly working with harvester?

### ISSUE THREAD

**Issue by neixlo** [genicam/harvesters#336]
First of all, thanks for harvesters!

## Background 

I have a question on how to check if the .cti file which I use is fully working with harvesters. 

I know that one shouldn't copy the .cti file into another location, because it "may need to retrieve relevant libraries to link".
I read issue #200 and also the [faq section](https://github.com/genicam/harvesters/wiki/FAQ#i-pointed-out-a-cti-file-but-harvester-says-the-image-doesnt-exist-part-2) about that point.

However for me it seems, that this strongly depends on the .cti implementation of the according vendor. 

I was able to copy the .cti file of Baumer (′libbgapi2_gige.cti.2.12.0′) into a location of my choice (This might be wanted if you don't want or can install full libraries due to their license).
And it is working without setting an additional environment variable, linking or other things. 

## Test
I checked the following script (modified  [example from the readme](https://github.com/genicam/harvesters#harvester-on-ipython)) with my camera (Daheng, GigEVision camera).

```
from harvesters.core import Harvester
import numpy as np  # This is just for a demonstration.

h = Harvester()

h.add_file("/home/me/Projects/GenICam/libbgapi2_gige.cti.2.12.0")

h.update()

h.device_info_list[0]

ia = h.create(0)
ia.remote_device.node_map.Width.value = 64

ia.remote_device.node_map.Height.value = 64

#ia.remote_device.node_map.PixelFormat.value = "Mono64"

ia.start()

with ia.fetch() as buffer:
    # Let's create an alias of the 2D image component:
    component = buffer.payload.components[0]

    # Note that the number of components can be vary. If your
    # target remote device transmits a multi-part information, then
    # you'd get two or more components in the payload. However, now
    # we're working with a remote device that transmits only a 2D image.
    # So we manipulate only index 0 of the list object, components.

    # Let's see the acquired data in 1D:
    _1d = component.data
    print("1D: {0}".format(_1d))

    # Reshape the NumPy array into a 2D array:
    _2d = component.data.reshape(component.height, component.width)
    print("2D: {0}".format(_2d))

    # Here are some trivial calculations:
    print("AVE: {0}, MIN: {1}, MAX: {2}".format(np.average(_2d), _2d.min(), _2d.max()))

ia.stop()
ia.destroy()
h.reset()
quit
```

Terminal Output was

```
(.venv) me@metoo:~/Projects/GenICam$ python ./launch_harvester_exp.py
1D: [0 0 0 ... 1 0 1]
2D: [[0 0 0 ... 1 0 0]
 [1 0 1 ... 0 0 1]
 [1 1 1 ... 1 0 0]
 ...
 [1 1 1 ... 1 1 0]
 [0 0 0 ... 1 1 0]
 [1 0 1 ... 1 0 1]]
AVE: 0.45751953125, MIN: 0, MAX: 1
```

I think I get the image data just as I should.
Different to the example in the readme is, that ′h.device_info_list[0]′ is not returning anything in the terminal. Not sure if this is normal and just related to the camera I'm using.

## Question

My actual question is:
**Is harvester fully working, if I use the .cti file as described above or is there anything I should be aware of?**

Unfortunately the available information in the internet is not very comprehensive for this specific topic. :/
@kazunarikudo can you help here?

**Comment by kazunarikudo** [comment]
Hi,
Doesn't even the following line display anything after the `h.update()` call?
```
print(h.device_info_list)
```

> Not sure if this is normal 

The list should contain one or more devices if there actually is a camera that the GenTL Producer can detect. As far as you can acquire an image then the GenTL Producer should have detected the camera. Since at least you can acquire images, maybe you should try to have an opportunity to check what each line does.

> I was able to copy the .cti file of Baumer (′libbgapi2_gige.cti.2.12.0′) into a location of my choice

I do not mind if it works for you: Again, however, you should keep in mind that you will need to know the GenTL Producer enough as its developer knows; at least I would like to emphasize that a client should not move a GenTL Producer around. Even if a feature did not work as expected, nobody can help you as long as the usage breaks the expected condition.

Feel free to come back here if you still have a question after you had a sufficient amount of time for learning.

Regards, Kazunari.

**Comment by neixlo** [comment]
Thanks @kazunarikudo for the response!


> Doesn't even the following line display anything after the `h.update()` call?
> 
> ```
> print(h.device_info_list)
> ```

If I add the print statement as you suggest, the following information is shown in the terminal:
 ```
[{'access_status': 1, 'display_name': 'MER-503-20GC-P', 'id_': 'devicemodul00_21_49_02_73_e9', 'model': 'MER-503-20GC-P', 'parent': <genicam.gentl.Interface; proxy of <Swig Object of type 'std::shared_ptr< GenTLCpp::TLInterface > *' at 0x7efc76e98c90> >, 'serial_number': 'QU0200110184', 'tl_type': 'GEV', 'user_defined_name': None, 'vendor': 'Daheng Imaging', 'version': None}]
 ```
It seems that the camera is correctly detected and also images can be acquired.




> I do not mind if it works for you: Again, however, you should keep in mind that you will need to know the GenTL Producer enough as its developer knows; at least I would like to emphasize that a client should not move a GenTL Producer around. Even if a feature did not work as expected, nobody can help you as long as the usage breaks the expected condition.

I think you're right, I need to ensure that the GenTL Producer works as expected.
