### ISSUE TITLE
Network usage 

### ISSUE THREAD

**Issue by centurions** [genicam/harvesters#347]
Hi thank Harvesters team for this great library .

Why network's usage is always 100% but with my camera's application It's about 5..6% ?

**Comment by kazunarikudo** [comment]
Hi, could you tell me the GenTL Producer that you're using now?

**Comment by kazunarikudo** [comment]
One more question: Do you mean the usage reaches 100% when you call the `ImageAcquirer.start` method? Would that turn quite once the image acquisition stops by the `stop` method call?

**Comment by kazunarikudo** [comment]
Closing. Please feel free to reopen if needed.
