### ISSUE TITLE
install.rst outdated / newest pip version incompatible with python 3.6

### ISSUE THREAD

**Issue by vinhill** [genicam/harvesters#349]
I believe, something is wrong with which version pip installs for python 3.6. Specifically, the newest Harvesters 1.3.8 uses features not present in python 3.6.

# Description

Following [this](https://github.com/genicam/harvesters/blob/master/docs/INSTALL.rst) tutorial, I get the following error message

```
>>>from harvesters.core import Harvester
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\Programme\Anaconda\envs\genicam\lib\site-packages\harvesters\core.py", line 22
    from __future__ import annotations
    ^
SyntaxError: future feature annotations is not defined
```

# Steps to reproduce

```
conda create -n genicam python=3.6
conda activate genicam
pip install harvesters
python
from harvesters.core import Harvester
```

**Comment by kazunarikudo** [comment]
Hi, I am afraid, Harvester does not support 3.6 anymore; I’m just following the official CPython development. This is just for your information, 3.6 has reached its end of life last year.

**Comment by vinhill** [comment]
Okay, then the install.rst should be updated, maybe I open a pull request later.

Also, maybe pip can be set up in a way to install an older harvesters version / give an error message, if one installs harvesters in an old python version?

**Comment by afiqmuzaffar** [comment]
Which version should I install to enable this feature?

**Comment by kazunarikudo** [comment]
As of today, please install Python 3.7 or newer.
