### ISSUE TITLE
ia.start() freezing?

### ISSUE THREAD

**Issue by jeong-jasonji** [genicam/harvesters#350]
**Describe the Bug**
Similar to the bug described in #348, #342, and #158 I am having trouble acquiring the images from the cameras through Harvester. I am using the examples in the tutorials and in the FAQs: https://github.com/genicam/harvesters#harvester-on-ipython

The code the way up to ia.start() seems to be working correctly as I can check devices, change node maps, and etc. However, when I try to start the acquisition using ia.start() it seems like nothing is happening for over 15+min and seems like it's frozen or stuck in an infinite loop. There are no error messages nor any outputs and python is telling me that previous command is running and I should wait for it to finish.

**Configuration**
OS: [Windows 10 Pro]
Python: [3.7.13]
Harvester: [1.3.8]
GenICam: [1.0.0]
GenTL Producer: [Active Silicon Firebird]
Camera: [JAI Ltd., Japan SP-5000M-CXP2]

**To Reproduce/Sample Code**

```
import numpy as np
from harvesters.core import Harvester

# instance Harvester
h = Harvester()
# load CTI file to communicate with the GenTL Producer
active_silicon_cti = r'C:\Program Files\Active Silicon\FireBird CXP\GenTL\win64\TLActiveSilicon.cti'
h.add_file(active_silicon_cti)
# check files
h.files
# update the harvester with the CTI file
h.update()
h.device_info_list
# create an image acquirer
ia = h.create()
# change image size
ia.remote_device.node_map.Width.value = 64
ia.remote_device.node_map.Height.value = 64
ia.remote_device.node_map.PixelFormat.value = 'Mono8'
# start acquiring images
ia.start()
with ia.fetch() as buffer:
    # Let's create an alias of the 2D image component:
    component = buffer.payload.components[0]

    # Note that the number of components can be vary. If your
    # target remote device transmits a multi-part information, then
    # you'd get two or more components in the payload. However, now
    # we're working with a remote device that transmits only a 2D image.
    # So we manipulate only index 0 of the list object, components.

    # Let's see the acquired data in 1D:
    _1d = component.data
    print('1D: {0}'.format(_1d))

    # Reshape the NumPy array into a 2D array:
    _2d = component.data.reshape(component.height, component.width)
    print('2D: {0}'.format(_2d))

    # Here are some trivial calculations:
    print('AVE: {0}, MIN: {1}, MAX: {2}'.format(np.average(_2d), _2d.min(), _2d.max()))
```
If applicable, please paste the actual output (its whole traceback, etc) here:
The only thing that outputs when running the code above is the following:
```
GenTL producer does not implement IFGetParentTL
GenTL producer does not implement DevGetParentIF
GenTL producer does not implement DSGetParentDev
GenTL producer does not implement DSGetNumBufferParts
GenTL producer does not implement DSGetBufferPartInfo
```

**Expected Behavior**
Just like the example: https://github.com/genicam/harvesters#harvester-on-ipython I expect some output like this:
```
1D: [123 124 125 126 127 128 129 130 124 125 126 127 128 129 130 131 125 126
 127 128 129 130 131 132 126 127 128 129 130 131 132 133 127 128 129 130
 131 132 133 134 128 129 130 131 132 133 134 135 129 130 131 132 133 134
 135 136 130 131 132 133 134 135 136 137]
2D: [[123 124 125 126 127 128 129 130]
 [124 125 126 127 128 129 130 131]
 [125 126 127 128 129 130 131 132]
 [126 127 128 129 130 131 132 133]
 [127 128 129 130 131 132 133 134]
 [128 129 130 131 132 133 134 135]
 [129 130 131 132 133 134 135 136]
 [130 131 132 133 134 135 136 137]]
AVE: 130.0, MIN: 123, MAX: 137
```
**Reproducibility**
This phenomenon can be stably reproduced.

**Actions You Have Taken**

- [X] Read the [Harvester FAQ page](https://github.com/genicam/harvesters/wiki/FAQ).
- [X] 
Read the various issue logs, especially #348, #342, and #158
- [X] Disconnected and reconnected camera
- [X] Restarted Computer
- [X] Double checked camera function through ActiveCapture (the Active Silicon Frame Grabber) and can see images
- [X] Tried different versions of python, Harvester, and numpy (python versions > 3.7 has compatibility issues with genicam while versions < 3.7 has numpy issues; I've tried different Harvester versions as well from 1.2.0 to 1.3.8)

- [X] Tested with Harvesters_gui and can access the camera through it but it also freezes with the following outputs:

```
C:\Users\Owner\anaconda3\envs\gentl_37\lib\site-packages\harvesters_gui\frontend\pyqt5.py:474: DeprecationWarning: please consider to use create() instead of create_image_acquirer().
  self.device_list.currentIndex()
C:\Users\Owner\anaconda3\envs\gentl_37\lib\site-packages\harvesters_gui\frontend\pyqt5.py:588: DeprecationWarning: please consider to use is_acquiring() instead of is_acquiring_images().
  if not self.ia.is_acquiring_images() or \
C:\Users\Owner\anaconda3\envs\gentl_37\lib\site-packages\harvesters_gui\_private\frontend\canvas.py:136: DeprecationWarning: please consider to use fetch() instead of fetch_buffer().
  buffer = self.ia.fetch_buffer(timeout=0.0001)
C:\Users\Owner\anaconda3\envs\gentl_37\lib\site-packages\harvesters_gui\frontend\pyqt5.py:582: DeprecationWarning: please consider to use start_acquisition() instead of start_image_acquisition().
  self.ia.start_image_acquisition()
C:\Users\Owner\anaconda3\envs\gentl_37\lib\site-packages\harvesters\core.py:2026: DeprecationWarning: please consider to use start() instead of start_acquisition().
  self.start_acquisition(run_in_background=run_in_background)
```

**Additional context**
I've looked in the tutorials and other issues and tried the specific configurations they mention but I can't even reproduce those errors in acquiring images as there seems to be compatibility issues I'm running against with python, numpy, and/or Harvester as mentioned above.

**Comment by kazunarikudo** [comment]
@jeong-jasonji Hi, thank you for the report. Would [this approach](https://github.com/genicam/harvesters/issues/348#issuecomment-1141194570) resolve the issue? Regards, Kazunari.

**Comment by kazunarikudo** [comment]
Hi,
> If I modify the code above to this:
> ...
> ia.start()
> print('after start')
> with ia.fetch() as buffer:
>     component = buffer.payload.components[0]
> ...

Could you point at the lines where you changed, please?

**Comment by jeong-jasonji** [comment]
The only lines from the [harvester-on-ipython](https://github.com/genicam/harvesters#harvester-on-ipython) that I changed (other than some comments for my own sake) is this:
```
# start acquiring images
ia.start()
print('after start')  ###<- added this line
with ia.fetch() as buffer:
    # Let's create an alias of the 2D image component:
    component = buffer.payload.components[0]
```

**Comment by kazunarikudo** [comment]
Well,

> if I modify the code above to this:
> ...
> I do not see the print statement at all and only see:

With your comments above, I had guessed you programatically "modified" the code. but had not interpreted inserting the single `print` function call as a modification... Anyway,
```
for buffer in buffers:
    data_stream.queue_buffer(buffer)  ###<- freezes here
    _logger.debug('queued: {0}'.format(_family_tree(buffer)))
```
I had never faced the reported case where the program freezes at that method call. Maybe it'd be better to ask the Active Silicon support for further investigation. I am sure that they will take this seriously. If the support hesitates to start working on it, then just please tell me. Cheers, Kazunari.

**Comment by jeong-jasonji** [comment]
What would I ask the people at Active Silicon? I'm not sure what the issue would be on the Active Silicon end nor how I should direct any enquiries...

**Comment by kazunarikudo** [comment]
> What would I ask the people at Active Silicon?

Please ask them a question as follows: "I'm working with your GenTL Producer with Harvester. On a simple image acquisition program, it hangs at the line where Harvester calls `DSQueueBuffer` function call. I have asked the Harvester maintainer a question and he recommended reporting the observation as mentioned earlier and asking you for help."

That should be fine for the icebreaker. By the way, you are working with a GenTL Producer from Active Silicon, right? If so, everything is ready to step out.

**Comment by jeong-jasonji** [comment]
Thank you so much for the suggestion! And yes, I am using the GenTL Producer from Active Silicon.

Hopefully they can get to the bottom of this.

**Comment by kazunarikudo** [comment]
You are welcome. I admit there always be a chance where any defect slips in Harvester. If there's inconsistency on Harvester's side then I will gladly fix the issue.

**Comment by jeong-jasonji** [comment]
Hi, I got in touch with Active Silicon and they essentially said that they essentially said that they can't help us without purchasing their tech support and/or their most recent SDK and that costs a decent amount.

Is there a way to verify that this `DSQueueBuffer` problem is on the side of Active Silicon and that purchasing their SDK (and probably getting their most recent *.cti file and maybe tech support as well) can resolve this problem?

**Comment by kazunarikudo** [comment]
Thank you for the update. I had thought you were working on an Active Silicon product that you purchased by yourself. I am sorry, but everybody is running his/her own business; I do not have anything that I can help you with this situation. I hope you understand the limitation. Thank you.

**Comment by michezio** [comment]
Hi, I'd like to step in since I'm having the same issue. In my case it works most of the times, but randomly it hangs a the same point as the OP said and I have to kill all Python processes and sometimes even reboot the machine to make it work again.

I am using the .cti from Matrix Vision (downloaded and installed from [here](http://static.matrix-vision.com/mvIMPACT_Acquire/2.46.2/)) and it happens both on Windows and Linux, so I guess it's not related to a specific .cti producer but to the library itself

Since my program is a bit (quite a bit) complex and it involves 2 cameras managed in independent threads spawned from yet another process that manages Harvesters (while other processes do other stuff), I'm now working on a minimal script that produces the same behaviour that I'll provide shortly
