### ISSUE TITLE
Set a grab timeout in trigger mode

### ISSUE THREAD

**Issue by tanzerlana** [genicam/harvesters#354]
Hi all!

I am facing a problem with my GigE camera...

i am using this code to set the camera in trigger mode, and start it, in order for the camera to wait for the hardware trigger:

```
        self.ia.remote_device.node_map.TriggerMode.value = 'On'
        self.ia.remote_device.node_map.PixelFormat.value = 'BayerRG8'
        self.ia.start()
        with self.ia.fetch() as buffer:
```

The Problem I am facing, is that if for any reason the hardware trigger does not arrive (for example machine in fault) the program just sits there and waits. Is there a way to define a timeout for the Trigger mode? The trigger usually arrives within 100 ms, so it would be great to have a timeout of 500ms...  Halcon has this feature, so I was wondering if it possible to do it with harvesters too..

thank you!

**Comment by kazunarikudo** [comment]
Hi, thank you for trying out Harvester. For your use case, you'd need to call the `try_fetch` method with the `timeout` parameter.
```
with self.ia.try_fetch(timeout=0.5) as buffer:
    if buffer:
        # an image has been delivered.
        # if it's None then it means the method call ended up
        # with time out.
```
Technically speaking, the `fetch(timeout=0.5)` method call also can indicate time out by raising the `genicam.gentl.TimeoutException`. If you prefer that way, please do not forget to catch the exception by the corresponding `except` clause. Cheers, Kazunari.

**Comment by kazunarikudo** [comment]
Closing. Please feel free to open this ticket when needed.

**Comment by tanzerlana** [comment]
Sorry for the late reply, was on vacation. thank you very much for your help!

**Comment by kazunarikudo** [comment]
No problem. I hope you enjoyed the vacation.
