### ISSUE TITLE
How to get nodemap tree?

### ISSUE THREAD

**Issue by batrlatom** [genicam/harvesters#367]
Hello,
I am building a GUI for harvesters related backend and need to have a tree of features in the way that it corresponds with the right category. For example feature Width is in the category Image Format Control. Is it possible? Thanks

**Comment by olofsjo** [comment]
I have personally not created a GUI with those features for Harvesters but have you taken a look at the Harvesters GUI? 
https://github.com/genicam/harvesters_gui

To me it looks like it has the features you are asking for:

![image](https://user-images.githubusercontent.com/61141629/185088494-c69e012e-8011-4f45-ac68-94ab67690339.png)

Hope this can give you some help.

**Comment by batrlatom** [comment]
it looks like what I need to build. Thanks, I will take a look into how it is done.
