### ISSUE TITLE
1.4.1 is very slow

### ISSUE THREAD

**Issue by HitoshiUchida** [genicam/harvesters#374]
I changed 1.4.0 to 1.4.1 with python 3.8.14 on Linux min 21.0.
GenTL is mvIMPACT_Acquire v2.47.0

The image getting process became very  slow with PySide6.
When back to 1.4.0, there no problems of speed.

**Comment by kazunarikudo** [comment]
@HitoshiUchida Hi, thank you for the report. Could you tell me the difference in numbers so that I can how much it is, please? I am planning to discontinue 1.4.1 later. Regards, Kazunari.

**Comment by kazunarikudo** [comment]
@HitoshiUchida I need to ask you one more favor: What would happen if your application does not involve PySide? I would like to ask you to try running an image acquisition script without PySide.

**Comment by kazunarikudo** [comment]
In version 1.4.1, Harvester can delegate the timer to be used for special applications such as PyQt. To let Harvester delegate a timer, you will need to pass the timer to Harvester with the following code:

```
from PySide.QtCore import QTimer
from harvesters.core import Timer
from harvesters.core import Harvester as HarvesterCore


class _Timer(Timer):
    def __init__(self):
        super().__init__()

    def sleep(self, value: Any):
        QTimer.sleep(value)


self._timer = _Timer()

config = ParameterSet({
    ParameterKey.TIMER: self._timer,
})
self._harvester = HarvesterCore(config=config)
```
If you do not pass any timer then Harvester will use the built-in timer and that's the original behavior. I had expected some other internal changes not to affect performance but as far as I hear your report I will need to investigate the issue.

**Comment by kazunarikudo** [comment]
By the way, why did you know that I have released 1.4.1? Do you frequently visit here or PyPI?

**Comment by HitoshiUchida** [comment]
Dear Kazunari

Sorry this is not a direct answer to your question, but in my opinion,
there is probably some interference with the timer in Pyside.
I am not sure why, because Dialog, which should be terminating normally, is
not terminating, and I need to force it to terminate.

I am attaching my code.

Regards
H. Uchida

2022年10月3日(月) 14:37 Kazunari ***@***.***>:

**Comment by jcormier** [comment]
In the meantime, Is it possible to get a version released with #374, without this problematic PySide change?

**Comment by jcormier** [comment]
Whoops I meant #369

**Comment by kazunarikudo** [comment]
@HitoshiUchida Hi Hitoshi, I need to ask you for a favor. Could you try with the latest master ([1f4fedd](https://github.com/genicam/harvesters/commit/1f4feddaca8eba3f2d2741a238f18697899c61b0)) and check if it still slows down your application, please?

**Comment by HitoshiUchida** [comment]
Ok, I will try.

2023年1月21日(土) 10:13 Kazunari ***@***.***>:

**Comment by kazunarikudo** [comment]
@HitoshiUchida Hi, excuse me, you don’t need to check that for now; it was a bit early to ask you. I’ll ask you again once the prototype turned available. Thank you!

**Comment by HitoshiUchida** [comment]
Sure, no problem.

2023年1月22日(日) 8:01 Kazunari ***@***.***>:

**Comment by HitoshiUchida** [comment]
Hi, Kazunari.
I had been tested on ver 1.4.2 for my previous reported codes. There are no troubles. 
Thank you for a Great Job !.
