### ISSUE TITLE
SWIG interface file

### ISSUE THREAD

**Issue by yuzjzj** [genicam/harvesters#380]
I want to rebuild some features of harvesters in C#.
Unfortunately, that it is difficult for me to call class from GenApi.dll(C++) in C#.
Can I request interface files(.i)?

BTW, why [genicam](https://pypi.org/project/genicam/) doesn't have a repository?

**Comment by kazunarikudo** [comment]
Hi,

Thank you for the message. I’ll inform your request in the next international machine vision meeting. Perhaps some developers may get interested in it.

We do have a repository for the `genicam` package but it’s protected by the license defined by the European Machine Vision Association, so called EMVA.

You can get access to it once you agree with the contract that they define. I would like to encourage you making contact with EMVA first.

Thanks, Kazunari

**Comment by jcormier** [comment]
> I want to rebuild some features of harvesters in C#.
> Unfortunately, that it is difficult for me to call class from GenApi.dll(C++) in C#.

Note that you can definitely call unmanaged c++ code from C#, you just need to make a c# wrapper class to hide some of the messiness.

There are many online results if you search for it.  This one for example. https://www.pluralsight.com/guides/invoking-unmanaged-code-csharp

Note that even if you were using the DLL with c++, it's still very helpful to write a wrapper class anyways.  So I'm not sure it's really that much more work.

Of course non of this has anything to do with harvesters, other than harvesters being a good example of a python wrapper class around the c++ dll.

**Comment by yuzjzj** [comment]
> > I want to rebuild some features of harvesters in C#.
> > Unfortunately, that it is difficult for me to call class from GenApi.dll(C++) in C#.
> 
> Note that you can definitely call unmanaged c++ code from C#, you just need to make a c# wrapper class to hide some of the messiness.
> 
I can using DllImport, But using classes and structs from c++ to c# is confusing for me.

I tried SWIG sample by class, that is work.
And genicam package was automatically generated by SWIG.
This is the main reason I ask for the interface file.

Maybe I try other solution, thanks for the reply:).
