### ISSUE TITLE
UserOutput0 deprecation warning

### ISSUE THREAD

**Issue by MathijsNL** [genicam/harvesters#388]
**Describe the Issue**
```
DeprecationWarning: Rewrite the code with LineSource.value = UserOutput0 instead.
  ia.remote_device.node_map.LineSource = "UserOutput0"
```

**To Reproduce**
1. Define a LineSource and you get this warning.

**Expected Behavior**
This should just accept a string as input. You can't just give the undefined variable as advised by the warning.

 - OS: [Ubuntu 20.04 arm64]
 - Python: [3.10]
 - Harvester: [1.4.0]
 - GenTL Producer: [MatrixVision]
 - Camera: [Daheng Imaging GigE camera]

**Reproducibility**

This phenomenon can be stably reproduced:

Yes, all you need to do is this on an ia object:
```
ia.remote_device.node_map.LineSource = "UserOutput0"
```

**Comment by MathijsNL** [comment]
Nevermind, I forgot the .value at the end -_-

**Comment by kazunarikudo** [comment]
@MathijsNL Hi, thank you for helping other Harvester users as always. I highly appreciate that. I’m glad to know that you’ve understood the expected solution. Thank you for your understanding. Regards, Kazunari.
