### ISSUE TITLE
Memory Leak on Starting and Stopping cameras

### ISSUE THREAD

**Issue by EuanHoll** [genicam/harvesters#399]
**Describe the Issue**
The starting and stopping of cameras creates a memory leak.

**To Reproduce**
See the given script

**Sample Code**
 I can show a piece of code that demonstrates the reported phenomenon:

- [X] Yes
- [ ] No
- [X] (Please select either yes or no.)

If yes, please provide a sample code:
```
import genicam
import cv2
import numpy as np
from harvesters.core import Harvester

log = logging.getLogger(__name__)

logging.basicConfig(
    stream=sys.stdout,
    level=logging.INFO,
    format='[%(asctime)s: %(levelname)s] %(message)s'
)

serial_number = '23043237'
cti_fn = '/opt/pylon/lib/gentlproducer/gtl/ProducerGEV.cti'

log.info("starting harvester")
harvester = Harvester()
harvester.add_file(cti_fn)
harvester.update()

log.info("acquiring camera")
camera = harvester.create({"serial_number": serial_number})
camera.remote_device.node_map.TriggerSource.value = "Software"

log.info("starting camera")
camera.start()

try:
    while True:
        log.info("stop/start")
        camera.stop()
        camera.start()
        time.sleep(0.1)
except:
    log.exception("exception")

log.info("Stopping")
camera = harvester.create({"serial_number": serial_number})
camera.remote_device.node_map.TriggerSource.value = "Line1"
camera.stop()
camera.destroy()
harvester.reset()
log.info("Done")
```
 
**Expected Behavior**
When starting and stopping a camera it creates a memory leak. The code above shows an extreme example of it. 8s of running on multiple PCs cause it to take 4GB of ram. For my use case, I have to change the settings on the camera often (quality control) with little downtime. So over the course of weeks, this does build up and lead to abnormal memory usage.

**Configuration**

 - OS: [Ubuntu 22.04]
 - Python: [3.10.6]
 - Harvester: [1.3.7]
 - GenTL Producer: [Basler]
 - Camera: [acA3088-16gc]

**Reproducibility**

This phenomenon can be stably reproduced:

- [X] Yes
- [ ] No.
- [X] (Please select either yes or no.)

**Actions You Have Taken**
 
- [X] I've read the [Harvester FAQ page](https://github.com/genicam/harvesters/wiki/FAQ).

**Comment by sunavlis** [comment]
Hi @EuanHoll 

Is your **Configuration** information correct? I can't reproduce the issue with _Harvester 1.3.7_. It seams also to work with version _1.4.0_.

But on _Harvesters 1.4.2_ I see exactly the same issue which you have described.

**Comment by kazunarikudo** [comment]
@EuanHoll Hi, please see my comments in the following code:
```
log.info("acquiring camera")
camera = harvester.create({"serial_number": serial_number})
camera.remote_device.node_map.TriggerSource.value = "Software"

log.info("starting camera")
camera.start()
[...]
camera = harvester.create({"serial_number": serial_number})  # why do you assign it again?
camera.remote_device.node_map.TriggerSource.value = "Line1"
camera.stop()
camera.destroy()
harvester.reset()
```
Please keep in mind that you need to take care of resource management for the `ImageAcquirer` objects; it is true for the `Harvester` object as well. The second assignment does not mean the former object is securely released. It is based on Python nature and you need to explicitly call the destroy method on the former object if needed; I believe you do not need to have the second assignment anyway though. If you do not want to take care of it then I would recommend using the `with` statement to have an explicit lifetime scope but it may not be applicable depending on the application.

**Comment by sunavlis** [comment]
Hi Kazunari,

The memory leak is not because of the end of the provided script. A simple loop of start/stop results in the issue described by @EuanHoll

I created a pull request to revert the commit 31ca2807a0668b328114d7a37e95c0bdec4412ee which doesn't revoke the buffer memory allocated in harvesters.

@creiter64 I was not able to reproduce your issue (#390) with the submitted merge request using the _mvGenTLProducer.cti_ producer.
