### ISSUE TITLE
Add support for RISC-V targets

### ISSUE THREAD

**Issue by keck-in-space** [genicam/harvesters#407]
**What is the goal that you want to achieve by the request?**

I would like to be able to use this library on RISC-V targets such as the PolarFire board by Microchip. Can it be built for this target? Python already runs on the PolarFire.

**Additional context**
Is this code totally open source? I was unable to find a C based library that implements Genicam or I would have attempted to build it myself.

**Comment by eudoxos** [comment]
>  I was unable to find a C based library that implements Genicam
Check out this: https://github.com/AravisProject/aravis/

**Comment by keck-in-space** [comment]
Oh I should close this! I ended up using Aravis. Great comment! Thanks!
