### ISSUE TITLE
Version Control

### ISSUE THREAD

**Issue by OptogeneticsandNeuralEngineeringCore** [genicam/harvesters#419]
**Describe the Issue**
Genicam 1.2.0 is required for harvesters. 

Genicam 1.2.0 requires python 3.7 or higher (pip install genicam will fail/install 1.1.0 on python3.6). So python 3.6 does not work.

Also, this all appears to work on 3.10, so recommend install just with that.

**Comment by sunavlis** [comment]
Yes Python 3.6 is not supported for GenICam 1.2.0.

We plan to support the actual Python versions according the official Python release cycle: https://devguide.python.org/versions/
