### ISSUE TITLE
genicam2 package?

### ISSUE THREAD

**Issue by aprowe** [genicam/harvesters#43]
Hello, 
genicam2 is listed as a dependency, but I can't seem to find this package anywhere.
Any hint on how to acquire it?

Thanks!

**Comment by aprowe** [comment]
Ok I found it here: https://pypi.org/project/genicam2
It might just not be installable for python 3.7?

**Comment by kazunarikudo** [comment]
Hi @aprowe , thank you for trying out Harvester! I'm sorry but I've not prepared anything for 3.7 so far. For now, I would like to ask you to try it out either of 3.4, 3.5, or 3.6.

**Comment by kazunarikudo** [comment]
Once we prepared a CI system to create binaries, 3.7 shuold be quickly supported!

**Comment by mitchbte** [comment]
Hello. Has this issue been resolved. I'm running python 3.7.2 and pip 19.0.1 on Windows 10 64bit, however python is 32 bit. Pip can't find a package to install... 
Thanks for you support!

Cheers. Mitch

**Comment by kazunarikudo** [comment]
Hi Mitch,

Thank you for trying out Harvester. Harvester consumes some language bindings (they are maintained by the GenICam committee and I'm one of the developers) and they have not been ported to any 32-bit architecture. They would be ported to there in the future but I can't tell you any specific date as of today so I hope you try out Harvester on 64-bit architectures with a 64-bit Python till then. Anyway, your issue is not relevant to this issue but this issue is relevant to more or less camera side including the lower image acquisition library.

Best regards,
Kazunari

**Comment by mitchbte** [comment]
Thank you sir. Will do!

**Comment by iPsych** [comment]
> Hi Mitch,
> 
> Thank you for trying out Harvester. Harvester consumes some language bindings (they are maintained by the GenICam committee and I'm one of the developers) and they have not been ported to any 32-bit architecture. They would be ported to there in the future but I can't tell you any specific date as of today so I hope you try out Harvester on 64-bit architectures with a 64-bit Python till then. And yes, I have already uploaded the `genicam2` module to PyPI for the 64-bit Python 3.7.
> 
> Best regards,
> Kazunari

Hello, is there any timeline for 32bit implementation in Windows?
Bests,
J.

**Comment by kazunarikudo** [comment]
Hi J.,

We as the GenICam committee is trying to release version 3.2 package which includes the first official version of the GenICam Python bindin which will also be uploaded to PyPI in the end. However, there still be technical difficulty and seems to take some more time. The development of the 32bit version will come after the version 3.2 release so it would be some time in 2020. Once it's released then Harvester will work on your 32bit target.

Thank you for your understanding and sorry having kept you waiting.

Best regards,
Kazunari

**Comment by Shorlaks** [comment]
hi @kazunarikudo 

> The development of the 32bit version will come after the version 3.2 release so it would be some time in 2020

well, GenICam is version 3.3 and it's 2021, I couldn't find any information on EMVA website regarding the 32 bit version.
Is it released yet?

Thank you,
Shorlaks

**Comment by glenbhermon** [comment]
Are ARM packages available on pip?
