### ISSUE TITLE
  raise LogicalErrorException( _genapi.LogicalErrorException: The target port does not hold any URL. update() 

### ISSUE THREAD

**Issue by pathu999** [genicam/harvesters#437]
**Describe the Issue**
After selecting CTI (Camera Transport Interface) for device communication, I am unable to establish a connection with the device. Instead, an error is encountered.

To Reproduce

1. Select CTI as the communication interface for the device.
2. Attempt to connect to the device.
3. Encounter an error preventing a successful connection.

**Expected Behavior**
I expected to establish a connection with the device after selecting CTI as the communication interface. There seems to be an issue preventing the connection, which needs to be resolved.

**Screenshots**
If applicable, add screenshots to help explain your problem; Note that it is not necessary to put everything as a screenshot! If the source is a text just paste the text because that is much helpful for us.

**Configuration**
 - OS: [Windows 11]
 - Python: [3.8.1]
 - Harvesters:  [ 1.4.2]
 - genicam        : [e.g. Muffle Donut API version 12.1, Itchy Inc.]
 - Camera: [e.g. Gong Hyperspectral, Scratchy AG]

**Reproducibility**
This phenomenon can be stably reproduced:

 Yes
 No
The error occurs consistently whenever attempting to connect to the device using CTI.
This phenomenon can be stably reproduced:

- [x] Yes
- [ ] No.
- [ ] (Please select either yes or no.)

The error occurs consistently whenever attempting to connect to the device using CTI.

**Actions You Have Taken**

- Checked the device connections to ensure they are properly set up.
- Verified the CTI configuration settings to ensure they are correct.
- Checked for device-specific requirements related to CTI communication.
- Consulted the CTI documentation and support resources for troubleshooting.
- Attempted to debug the code to identify the source of the error.

**Additional context**
The specific error message encountered during the CTI connection attempt would be essential in diagnosing the problem accurately. Additionally, checking the CTI documentation or contacting CTI support for any device-specific nuances related to CTI communication might provide valuable insights.

**Comment by L0VEUU** [comment]
Hello! Have you solved this problem. Now I have the same problem.

**Comment by pathu999** [comment]
no
