### ISSUE TITLE
Can you give me some Pointers based on your experience?

### ISSUE THREAD

**Issue by gpr7172** [genicam/harvesters#449]
I am a student in school. Due to my lack of skills, I have encountered some difficulties when using  A camera caller Gobi640 . These difficulties are difficult to find answers on the network, so I would like to ask you, please spare some time to answer me.

My specific question is this: Gobi640 is used by Xenics, a highly integrated software. But we want to use the camera to further process the existing video, such as enhancement, further noise reduction and so on. Therefore, we need to process the video frame obtained by the camera. Other vendors, for example, provide SDKS in various languages for call. It may be that I am not good at academics, but I did not find the SDK I needed in Xenics.

Secondly, there is a software package called GigEVisionHardware in Matlab. To my surprise, he does not need to know the details. After importing into MATlab, he can change the IP address of the network port camera in the code part to realize the camera call.

Following this idea, I investigated some Gige protocols, and here are some of my attempts: Harvester is available for Python but requires a.CTI file, which I did not see in the Xenics file directory. For c++, it seems possible to connect the.dll library to implement camera calls, I refer to the relevant content in the manual, "clseremc.dll, Clseripx. DLL, clsernat. DLL, x25_wxwdck. DLL, x25_wxwplt. DLL, x25_wxwprg. DLL, x25_wxwsci. These dl ". The DLL file is simply a phrase in the manual is introduced to make me feel confused.
Can you give me some Pointers based on your experience?

**Comment by sunavlis** [comment]
Hi @gpr7172 

Harvesters acts as GenICam consumer and requires a GenICam producer (*.cti file). Usually, the camera vendor provides the *.cti file as part of there camera driver (if it GenICam compatible).

Another standard in the machine vision industry is GigE Vision. But this is not directly accessible within Harvesters. 

You will find more information about the two standards here:
[GenICam](https://www.emva.org/standards-technology/genicam/)
[GigE Vision](https://www.automate.org/vision/vision-standards/vision-standards-gige-vision)
