### ISSUE TITLE
IDS camera trigger mode not working

### ISSUE THREAD

**Issue by stanrusnak** [genicam/harvesters#77]
**Describe the bug**
When using IDS GV-504 in hardware triggered mode, only first frame is triggered. After grabbing the first image, cameras are running like if they were in freerun. Images are out of sync. If I stop acquisition and start again after each frame grabber, camera is waiting for trigger again

**To Reproduce**

```
h = Harvester()
h.add_cti_file('C:\\Program Files\\IDS\\IdsVisionSuite\\gevgentl\\64\\ids_gevgentlk.cti')
h.update_device_info_list()
   
cam = h.create_image_acquirer(i)
cam.device.node_map.AcquisitionMode.value = 'Continuous'
cam.device.node_map.TriggerSource.value = 'Line0'
cam.device.node_map.DeviceLinkThroughputLimit.value = 120000000
cam.device.node_map.TriggerMode.value = 'On'
cam.start_image_acquisition()
while 1:
        with camera.fetch_buffer() as buffer:
                component = buffer.payload.components[0]
               
                if camera.device.node_map.PixelFormat.value == 'BGR8Packed':
                    _2d = component.data.reshape(
                            component.height,
                            component.width,
                            3
                            )
                    
                if camera.device.node_map.PixelFormat.value == 'BayerRG8':
                    _2d = component.data.reshape(
                            component.height,
                            component.width,
                            1
                            )
                    _2d = cv2.cvtColor(_2d, cv2.COLOR_BAYER_RG2RGB)
```
                   
**Expected behavior**
Camera should stay in triggered mode all the time.

**Desktop (please complete the following information):**
 - OS: Windows 10 pro

**Comment by kazunarikudo** [comment]
Hi,

Thank you for trying out Harvester.

Regarding the reported issue, I recommend you to make sure the phenomenon can be reproduced by only Harvester. If it is really triggered by Harvester, then you should be able to show us something valuable that is different from the code above. To be honest, at least, I don’t think the presented code snippet proves that the issue is caused by Harvester.

 In addition, I know it’s just a typo but you should use a valid code.

Regards,
Kazunari

**Comment by drewm1980** [comment]
I'm on the same team as Stano. He's busy so I'll go ahead and share some more information.

RE the quality of the code snippet, you always have to start somewhere. Sometimes a small snippet is enough if you're obviously using a library the wrong way, and a fully runnable example might not be any better if you need hardware to reproduce the issue anyway.

The same cameras work with hardware triggering with HALCON. I'm not sure if HALCON is using IDS's driver, the reference implementation, or their own implementation. Maybe Stano knows.

We're going to try hardware triggering with harvester and another Allied Vision GeniCam camera we have here, and will post back if we can reproduce the same issue on other hardware.

Is hardware triggering known to work properly with harvester on other cameras? In the compatibility table it just says "Tested" but there's no note on what functionality was tested.

**Comment by mverstra** [comment]
We were able to get the expected behavior with an IDS camera on a ubuntu system. Possibly this is something windows specific.

**Comment by kazunarikudo** [comment]
Hi. Thank you for the update. I’ll be waiting for the next one. Thanks!

**Comment by mverstra** [comment]
I tried on windows 10 with an Allied Vision camera and the vimba cti file.
About 80% of the time harvester is not capturing any frames (independent of freerun/hardware triggered mode). This was tested both with the harvester_gui and the script mentioned above.

In the ReadMe, you mention that Allied Vision was tested. Could you elaborate on what cti file and what windows version you were using?

Thanks!

**Comment by kazunarikudo** [comment]
At least I have not tested any Allied camer or GenTL Producer by myself. Maybe I heard it from someone who tried to use them but not sure who was he anymore. Please excuse me.

Regarding the reduced acquisition rate issue, could you try with Matrix Vision's GenTL Producer, please? You can download the installer at the following URL:

    http://static.matrix-vision.com/mvIMPACT_Acquire/2.30.1/mvGenTL_Acquire-x86_64-2.30.1.exe

In addition, I would appreciate if you could tell me the camera model name. 80% sounds so large and it puzzles me. By the way, how about the result from an iDS on Ubuntu? Was that also give you 20%, too?

**Comment by mverstra** [comment]
The Matrix Vision Producer seems to interfere with the Vimba software, and since I'm testing on a system that's been used by others, I can't try this for now. Will get back on that later.

The model name is Mako G-125B (5054). 

IDS on ubuntu was successful (both freerun and hardware triggered).

**Comment by kazunarikudo** [comment]
This just to make sure but could you check that you’re not involving any 100Mb equipment such as cables or hubs in your test environment?

**Comment by erik-mansson** [comment]
We had the same or a very similar issue with an Optronis CP70-1-M-1000. For remote_device.node_map.AcquisitionMode it does not have a 'MultiFrame', but the 'SingleFrame' can be used also with an unlimited number of frames (like 'Continuous' but external trigger).

The problem is that ImageAcquirer.start_acquisition sets _num_images_to_acquire to 1 when I use 'SingleFrame' and therefore Harvesters stops after the first frame.

Without changing default behaviour, I attach a quick fix that adds an optional force_unlimited_count argument that allows me to call 
`ia.start_acquisition(force_unlimited_count=True)`
which sets _num_images_to_acquire to -1 as in the 'Continuous' mode. With this fix it works for me. 

[allow_SingleFrame_mode_without_actually_stopping_after_first.diff.txt](https://github.com/genicam/harvesters/files/4594304/allow_SingleFrame_mode_without_actually_stopping_after_first.diff.txt)

I suspect this patch might be useful for issue #150 too but not equally sure.

**Comment by kazunarikudo** [comment]
@erik-mansson Hi, Erik. Thank you for your comment. Okay, I see your point but may I ask you a question? Doesn't your Optronis camera allow you to acquire images by the external trigger with `AcquisitionMode.value = Continuous`? I know there are cameras that just wait for being triggered even if its AcquisitionMode is Continuous. I interpret `SingleFrame` and `MultiFrame` are the modes that automatically stop the image acquisition engine in at least the camera once the camera acquired the required number of images. I would appreciate it if you could point at a reference for me that explains why my interpretation is not correct. Thanks. /Kazunari

**Comment by erik-mansson** [comment]
Hi @kazunarikudo and thanks for all your work on Harvesters which has saved our project much time!

For the Optronis CP70-1-M-1000, AcquisitionMode.value='Continuous' means that it generates internal/software triggers based on the configured frame rate, i.e. not waiting for external trigger. We have been using that for testing our program but for real use we need the triggered mode. As a reference for the acquisition modes of this camera you can see page 20 in the manual https://www.optronis.com/InkDownloads/Manuals/CXP/1875-SU-01.pdf They say for SingleFrame that "the camera uses an external signal to generate frames" (note the plural on frames). Using the Genicam browser provided by Optronis, SingleFrame uses the external trigger and does not stop after the first frame. With harvesters it did however stop after the first frame. After a while of debugging my simple addition to Harvesters' core.py allows me to do the same via our Python program that uses Harvesters. (I also tried things like calling the node_map.AcquisitionStart.execute() from my Python code after ia.fetch_buffer() but that gave errors too, so after reading the code of ImageAcquirer.start_acquisition() I concluded that it was Harvesters and not the camera that stopped the acquisition after the first frame)

I don't know the Genicam specification details (just that it does list MultiFrame that our camera does not allow) and can't tell you whether Optronis use of SingleFrame for "unlimited number of externally triggered frames" is formally correct or incorrect. The name clearly doesn't sound like it should give multiple frames ;) but I guess one can argue that it gives a single frame _per trigger pulse_. Unless there is a different solution for using it in Harvesters (at high rate, we need 1 kHz) I suggest you/we accept that different manufacturers have some strange interpretations/limitations and just ensure there is some way of configuring Harvesters to work with it. I implemented the patch with an optional argument precisely to not affect anyone not explicitly choosing to enable this behaviour.

I doubt that it would be good or reliable enough to try to _automatically_ enable this variant of unlimited-SingleFrame mode by looking for other features to identify cameras that work like ours, e.g. node_map.AcquisitionMode not listing 'MultiFrame' as allowed for the enumeration, no node_map.AcquisitionFrameCount attribute existing, or maybe simply DeviceVendorName 'Optronis'. It would make it easier for new users of these cameras, but it could screw things up if the conditions match other cameras too or just make it surprising for the programmer that the behaviour differs.
