### ISSUE TITLE
Install procedure OSX/Mac and GenTL Producers

### ISSUE THREAD

**Issue by Daimakaimura** [genicam/harvesters#79]
Could you please clarify how to install the GenTL producer in OSX? In the installation instructions you suggest to install mvIMPACT_Acquire from [http://static.matrix-vision.com/mvIMPACT_Acquire/2.29.0/](http://static.matrix-vision.com/mvIMPACT_Acquire/2.29.0/) but inside the directory there is not mvIMPACT_Acquire installer, only debug symbols files. 

Another question is regarding the GenTL, you suggest to use Matrix Vision GenTL, will this work for any camera o will I need a specific GenTL file from the specific manufacturer? Thanks a lot for your work.

**Comment by kazunarikudo** [comment]
Hi. (1) MATRIX VISION does not support macOS. (2) Their GenTL Producer works with any GenICam compliant U3V or GEV camera as far as I know. I tend to suggest people to use their producer but please note that other manufacturers also produce their own excellent ones. You should know that this is also a valid option to use your camera manufacturer's GenTL Producer to keep your lifeline available. -Kazunari

**Comment by Daimakaimura** [comment]
Thanks a lot for your answer. Any recommendation for OSX? I've check JAI and Stemmer and none provide OSX producers (as far as I understand).

**Comment by kazunarikudo** [comment]
Let me list a few just for your information: Probably OMRON Sentech. Basler might support macOS for U3V, too. However, they would block other 3rd party cameras.

**Comment by Daimakaimura** [comment]
Thanks again, I am starting to realise that Max/OSX might not be the best option to work with this cameras anyway.

**Comment by ducciopiovani** [comment]
Hello I am having the same issue on Mac. Did you make it ?

**Comment by kazunarikudo** [comment]
@ducciopiovani Hi, thank you for being interested in Harvester. I am afraid but I am not a person who develops GenTL Producers. However, I could tell you more or less practical: The machine vision market should be smaller than you expect. It means just making an inquiry to those possible software manufacturers (or camera manufactures) of 10 or so then you could get an answer you would like to hear. Some of them might just avoid to publicly announce that they have macOS GenTL Producer. /Kazunari
