### ISSUE TITLE
Do you support Telelyne Dalsa Ginie Nano c1930

### ISSUE THREAD

**Issue by Sonymon** [genicam/harvesters#80]
I am using c1930 Telelyne Dalsa Ginie Nano c1930

Installed SDK, harvester and harvester-gui

`from harvesters.core import Harvester

h = Harvester()

# ATTENTION! Please use the CTI file in the original location!

# Why? Visit https://github.com/genicam/harvesters/wiki/FAQ and
# read "I pointed out a CTI file but Harvester says the image doesn't
# exist (Part 2)."

h.add_cti_file("C:\\ProgramData\\Anaconda3\\Lib\\site-packages\\genicam2\\TLSimu.cti")
print(h.cti_files)
h.update_device_info_list()
print(h.device_info_list)
`

Output

![image](https://user-images.githubusercontent.com/6533100/54687898-afbf8600-4b42-11e9-9242-4b2c6b73fa6c.png)

Kindly help.

**Comment by kazunarikudo** [comment]
Hi. Perhaps something could be wrong but note that TLSimu is just a simulator that is used to test Harvester. You can't control your Ginie though it. Please get an apropriate GenTL Prodcuer first and make a try. Thanks. -Kazunari

**Comment by Sonymon** [comment]
@kazunarikudo Kindly help me to find the proper GentTL producer, I am unable to find the same.
Kindly tell me if Harvester is already tested on Teledyne Dalsa Ginie Nano Models.

**Comment by kazunarikudo** [comment]
You may want to take a look at [this page](https://github.com/genicam/harvesters#gentl-producers). I have ever been consulted by a guy who wanted to use a Ginie so you should also be able to use that.

**Comment by gevero** [comment]
I can confirm that GenieNano M2420 works with harvesters and Matrix Vision producer in ubuntu 18.04.
