### ISSUE TITLE
Port the source code to the genicam module

### ISSUE THREAD

**Issue by kazunarikudo** [genicam/harvesters#83]
**Is your feature request related to a problem? Please describe.**
The GenICam committee is going to officially release their Python Bindings as the `genicam` module in 2019. Having that plan, Harvester should also use the module.

**Describe the solution you'd like**
Port the current code that relies on a prototype version, `genicam2`. The `genicam2` module will be frozen until it is really needed again in the future.

**Describe alternatives you've considered**
None.

**Additional context**
This change should not affect to the current Harvester users.

**Comment by jmargeta** [comment]
Hey @kazunarikudo , this would be great.
Any chance that the updated Python bindings would be also compatible with ARM?
Currently on PyPI there is only an x86 build. If so, is there any timeline and any way to contribute?

**Comment by kazunarikudo** [comment]
@jmargeta Hey Jan! How have you been? I hope you've been great! Regarding the support of ARM, we as the GenICam committee have already noticed there are people who want to use the GenICam Python Bindings on ARMs. Having noticed that fact, we are trying to port the Bindings to ARMs. Hopefully it could be released in a year 2020 release.
