### ISSUE TITLE
 provided buffer is too small to receive the expected amount of data.

### ISSUE THREAD

**Issue by seb5g** [genicam/harvesters#86]
at startup when grabing images of a given size => all is fine
then, reducing the features width/height of the image acquirer => all is fine

then increasing the features width/height of the image acquirer generates this exception:
_GenTL exception: Buffer used is too small for operation. (Message from the source: A provided buffer is too small to receive the expected amount of data.) (ID: -1016)_

**Expected behavior**
How is defined the buffer size and what should be done to update it?

**Desktop (please complete the following information):**
 - OS: Win7, python 3.7
Camera: Omron Sentech STC-MBS500U3V

**Comment by kazunarikudo** [comment]
Hi Sebastien,

Which GenTL Producer are you using now? SENTECH's one?

-Kazunari

**Comment by kazunarikudo** [comment]
Harvester updates the buffer size every time you call the `start_image_acquisition` method of the `ImageAcquire` object inquiring the sufficient value to the GenTL Producer. If you are using vendor's GenTL Producer, then I would like to suggest you to try with a 3rd party GenTL Producer, such as MATRIX VISION's one.

**Comment by seb5g** [comment]
Hi Kazunari, thanks for the quick answer. I'm using Sentech's one indeed. I'll try Matrix Vision's but will it work with Sentech camera??? 
Cheers

**Comment by kazunarikudo** [comment]
Yes, it should work!

**Comment by seb5g** [comment]
I just got this camera as a test and never used Harvester before ;-) but so far very quick to include it in my set of modules. If you're interested: www.pymodaq.cnrs.fr Harvester will be used as a wrapper for a 2D detector plugin for all compatible cameras! Will save tons of time!!

**Comment by kazunarikudo** [comment]
Thanks for the info. I'll be happy if Harvester can help you anyhow. :-)

**Comment by seb5g** [comment]
@kazunarikudo I've tried the Matrix Vision producer, its works really well! Thanks again
