### ISSUE TITLE
Trouble updating statistics

### ISSUE THREAD

**Issue by recon56** [genicam/harvesters#89]
**Describe the bug**
When the GenTL Producer doesn't  support the "BUFFER_INFO_TIMESTAMP_NS" command the "_gentl.Buffer__get_timestamp_ns(self)" throws an "ErrorException" exception, which is not caught by the try/except. This problem can be solved by adding an except for "gentl.ErrorException" in the except starting in line 84 of statistics.py. 

**To Reproduce**
1. Connect to camera
1. Fetch a buffer from an image acquirer. 

**Expected behavior**
ErrorException to be caught.

**Desktop (please complete the following information):**
 - OS: Windows10 x64
 - Python: 3.7
 - Harvester: 0.2.12
 - GenTL Producer: sensor2image
 - Camera: sensor2image gige-server

**Comment by kazunarikudo** [comment]
Hi. Thank you for the report. I will fix that in the next release. Thanks again! /Kazunari
