### ISSUE TITLE
Python crashes when starting image acquisition, no error message

### ISSUE THREAD

**Issue by optika19** [genicam/harvesters#91]
When trying to use start_image_acquisition() either in basic demo code or with harvesters_gui, python crashes with a generic Windows crash error and no error message generated.

**To Reproduce**
1. Successfully list connected camera using its cti file from the JAI SDK
2. Try running start_image_acquisition() or in the GUI, pressing the "start image acquisition" play button
3. Crash window appears, program stops

**Expected behavior**
Acquisition to begin

**Desktop (please complete the following information):**
 - OS: Windows 10 version 1607
 - Python: 3.6.8 and 3.7.3, both have the same issue
 - Harvester: latest from pip, assumed 0.2.12
 - GenTL Producer: JAI
 - Camera: 2400-PGE

**Additional context**
I'm using a conda environment as recommended, tried one with python 3.7.3 and 3.6.8 and both result in the crash

**Comment by kazunarikudo** [comment]
Hi. Thank you for the report. Do you have any chance to try another camera to check if the camera also be able to reproduce the phenomenon? -Kazunari

**Comment by optika19** [comment]
I do not have access to another camera. I tried every .cti file included in my camera manufacturer's SDK (JAI) as well as the .cti file included in "mvGenTL_Acquire" linked in the readme. Only one .cti from the JAI SDK results in listing the camera, and the mvGenTL_Acquire cti does not list the camera. Here's the Windows Event Viewer output for the crashes:

```
Faulting application name: python.exe, version: 3.6.8150.1013, time stamp: 0x5c6f5f71
Faulting module name: VCRUNTIME140.dll, version: 14.15.26706.0, time stamp: 0x5b3efc77
Exception code: 0xc0000005
Fault offset: 0x000000000000c719
Faulting process id: 0x1fb0
Faulting application start time: 0x01d52c3f86d01352
Faulting application path: C:\Users\[username]\Anaconda3\envs\genicamDOS\python.exe
Faulting module path: C:\Users\[username]\Anaconda3\envs\genicamDOS\VCRUNTIME140.dll
Report Id: 3779003d-8f57-4b36-a6c5-5601f2634135
Faulting package full name: 
Faulting package-relative application ID: 
```

**Comment by kazunarikudo** [comment]
Hi. Have you applied MV's driver when you try to list the camera? If not, please make a try.

**Comment by optika19** [comment]
Can you provide more details? I do not see anything about MV's driver in the documentation here. Thanks.

**Comment by kazunarikudo** [comment]
I'm not a MV employee but you should be able to find your camera as a USB device in the Windows Device Manager. Or, perhaps MV could have provided you a utility tool which help you to apply their driver to yours.

**Comment by optika19** [comment]
Is MV a company or an acronym of a company? The camera works with the JAI software that comes with the SDK (I can use it to show a live view of the camera), so I can confirm that it has a functioning driver installed.

**Comment by kazunarikudo** [comment]
Ah, excuse me. MV: Matrix Vision.

**Comment by kazunarikudo** [comment]
In addition, it is not always true but you have to use a proprietary driver that comes with the manufactuer's SDK. If you use JAI then you'd use JAI's driver. If you go with MV, then you'd use their dirver. By the way, are you trying to acquire images from a USB3 Vision device, aren't you? (Sorry, I'm going to leave here soon, it's midnight.)

**Comment by optika19** [comment]
No, my camera is connected via Ethernet or RJ45. In Device Manager, I do not see a separate entry for the camera, only my Ethernet port. Using the JAI GevTL cti file, my device is listed but the crash occurs when I try starting image acquisition. Thanks for all your help.

**Comment by kazunarikudo** [comment]
Sorry about that. So many people come to consult with me and leave these days so I tend to mix up an issue with another. Okay, you are using a GEV camera. So have you enabled the Jumbo Frame option?

**Comment by optika19** [comment]
Yes, I have Jumbo Frames enabled. As per the JAI SDK instructions, I also turned on Interrupt Moderation, set the Interrupt Moderation Rate to Extreme, and set the Receive Buffers setting to 2048.

**Comment by kazunarikudo** [comment]
Okay, so does this phenomenon always, I mean, does this phenomenon happens every frame?

**Comment by optika19** [comment]
I am never able to start collecting frames, so I assume so. Using the harvesters_gui, the crash occurs immediately when I press the play button which has a tooltip that labels it as "Start image acquisition".

**Comment by kazunarikudo** [comment]
Okay, thanks. Another question I had was, you told me other SDK from other manufacturers do not list your camera, right? It can happen if the device is a USB3 Vision camera but I assume every general GEV SDK can list up your camera without any treatment. This is the reason I misunderstood that you were using a USB3 Vision camera.

**Comment by optika19** [comment]
Right, I could not get any other manufacturer's SDKs or cti files to recognize the camera, which is connected via ethernet.

**Comment by kazunarikudo** [comment]
If a camera is compliant with the GEV standard then it must reply to the device discovery command form the host. The camera can't be controlled if the camera has already been controlled by another camera but this is another story. The device must reply anyway. Yes, this is also another story but I feel it's very strange and does not make sense.

**Comment by kazunarikudo** [comment]
By the way, I have noticed the error is an access violation. The most possible case would be Harvester accessed an invalid memory area where is inconsistent with the actuall memory llocation. I would not say Harvester is not guilty but in general Harvester just dissects the full-filled image buffer following to the information that the coworking GenTL Producer provides. If the information is inconsitent, then Harvester will do an illegal action such as access violation.

**Comment by optika19** [comment]
Can I elevate Harvester's permissions somehow? I was trying to figure out what VCRUNTIME140.dll was but did not get far.

**Comment by kazunarikudo** [comment]
Could you install the distribution package using the following installer, please?
https://www.microsoft.com/en-us/download/details.aspx?id=48145

**Comment by kazunarikudo** [comment]
Technically speaking, there actually are SDKs which block cameras from competitors due to a business/political reason. However, at least MV's SDK does not block any camera as long as the camera is compliant with a correspoinding machine vision standard.

**Comment by optika19** [comment]
I have newer versions of that distribution package installed (2017 versions), and other programs that depend on them. Is it safe to uninstall those versions and install that older (2015) version? It looks like MV's included program for viewing camera output works with my camera, however I get several popups about being unable to detect a GigE Vision camera.

**Comment by optika19** [comment]
I successfully uninstalled the 2017 distribution packages, installed the 2015 package, and still got the same crash behavior.

**Comment by divyasaxenaa** [comment]
@optika19 @kazunarikudo
Please help me for below issue(same like mentioned above):

When trying to use start_image_acquisition() , python crashes stating error message "Process finished with exit code -1073741819 (0xC0000005)". After debugging, I found out that issue occurred at def queue_buffer  for announced_buffers in core.py i.e. " Access Violation Writing location".
Successfully listed connected camera using it's cti file from the JAI SDK.

Desktop (please complete the following information):

OS: Windows 10 
Python: 3.6
Harvester: 1.2.8
GenTL Producer: JAI
Camera: AD 080 GE
