### ISSUE TITLE
A simple source code to open camera and acquire frames in form of numpy array

### ISSUE THREAD

**Issue by sedhha** [genicam/harvesters#93]
I just wanted to know a decent source code as an example to acquire images in while loop in form of numpy array of the depth camera and then process it accordingly and show them.

Thanks in Advance

**Comment by kazunarikudo** [comment]
HI. Check out [this](https://github.com/genicam/harvesters/blob/master/src/harvesters/test/test_tutorials.py) page. It should work for you. /Kazunari
